### ISSUE TITLE
Pan troglodytes

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/stdpopsim#1000]
- **Name:** *Pan troglodytes*
- **Common name:** Chimpanzee

**Description:** any other discussion or useful background? (optional)

*Note: Maybe you don't know a lot of the things below - but, that's OK!
The criteria are that (a) the choice is reasonable, and (b) the rationale is clear.
What we want is a "reasonable estimate" (or, "best guess") - if you were to use a number in a paper,
what would you use and how would you justify it to your collaborators?
For instance, for "generation time", best would be to cite a paper that actually measures
or estimates generation time. But most species don't have this;
next best would be to give a number used in the literature, and provide a citation that used it
(and hopefully the publication gives a justification also).
Lacking this, you might provide a number from a related species (and a citation for this).*

*Here is the checklist of things that we need to add a species to the catalogue.
Each thing should be provided, with a justification (maybe short) and a citation.*

**Demographic information:**

- generation time in years: 25 ([Langergraber et al. 2012](https://doi.org/10.1073/pnas.1211740109))
- "default" population size: 15000 ([de Manuel et al. 2016](https://doi.org/10.1126/science.aag2602))

**Chromosome structure:**

*Note:* The assembly should be *chromosome-level*, i.e., not composed of thousands of scaffolds.

- ensembl assembly ID: Pan_tro_3.0

*Note: species in Ensembl can be found in one of these lists:
[vertebrates](https://uswest.ensembl.org/info/about/species.html),
["metazoa"](https://metazoa.ensembl.org/species.html),
[plants](https://plants.ensembl.org/species.html),
[fungi](https://fungi.ensembl.org/species.html),
[protists](http://protists.ensembl.org/species.html),
or [bacteria](http://bacteria.ensembl.org/species.html).*

**Recombination rates:**

- genetic map of recombination rates (as a hapmap or csv file): [Auton et al. 2012](https://doi.org/10.1126/science.1216872)
- genome-wide mean recombination rate (which will be used as the default): 0.7e-8 ([Stevison et al. 2016](https://doi.org/10.1093/molbev/msv331))

**Mutation rate:**

- genome-wide mean mutation rate: 1.20e-8 ([Kong et al. 2012](https://doi.org/10.1038/nature11396))

**Demographic model:**

- as a list of population sizes, growth rates, migration rates, etcetera. **(optional)**
- citation:
    - [de Manuel et al. 2016](https://doi.org/10.1126/science.aag2602)
    - [Kuhlwilm et al. 2019](https://doi.org/10.1038/s41559-019-0881-7)

**Other information:**

These are things we don't currently use, but will want to use in the future:

- sex determination system, and which chromosomes are the sex chromosome(s): XY
- ploidy: diploid

**Comment by grahamgower** [comment]
Pan troglodytes is in!
