### ISSUE TITLE
String evaluation for species, genetic_map, models

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/stdpopsim#1031]
One useful feature would be to evaluate the strings that the users provide, and see if that string 
is somewhat close to the specified in the catalog. 
For now, we only give an error when it does not match, but we could be more informative than that. 
so evaluate:
* whether the user's string and the catalog agrees on Uppercase and lowercase instances
* what index(es) do the two strings differ
* and give a suggestion

Will be implementing this with Vince B.

**Comment by vsbuffalo** [comment]
This PR (https://github.com/vsbuffalo/stdpopsim/commit/3b825d808caf854f339b2fdb5bdbb9a53b0465d0) lists the catalog for `get_species()` and `get_genetic_map()` when the requested key isn't found, and Izabel is adding this to feature to demographic models.

**Comment by grahamgower** [comment]
I think something like this has already been proposed in #753 and #754.

**Comment by izabelcavassim** [comment]
Thanks @vsbuffalo! I am closing this issue!
