### ISSUE TITLE
Output masking feature

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#104]
On the conference call today, we decided to implement a feature to mask the tree sequences that we simulate from genetic maps. 

1. Provide an option for the user to specify a set of genomic intervals (as a bed file, I guess?), which we "delete" (see below) from the simulated tree sequence.
2. By default, when we simulate from a genetic map we compute a simple mask based on regions of zero recombination within this map. We will derive some heuristics for this which may or may not be organism/chromosome specific.

A planned feature for the next version of stdpopsim would be to curate a set of masks and provide methods to download and cache these transparently, like we do for genetic maps.

The 'delete' (or maybe 'dice' - we're still discussing what it should be called) operation will take the tree sequence simulated under the raw recombination map, and remove all topology and site data from the masked regions. Therefore, any statistics computed on this will not be affected by the zero recombination rate sections.  Anything plotted against genome coordinates will show big gaps (which is what we want, right?). This is being developed at https://github.com/tskit-dev/tskit/pull/261

**Comment by grahamgower** [comment]
Should we close this since #664 has been merged, or should we consider adding a curated set of mask files? @jeromekelleher

**Comment by jeromekelleher** [comment]
Let's close
