### ISSUE TITLE
add SLiM dependency

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#1043]
I don't think we list SLiM as a dependency yet 😱 -- can pip handle this for us?

**Comment by grahamgower** [comment]
Hmm, no, unfortunately we can't do this with pip as it only doesn Python packages. But SLiM is on conda, so we can use it there in any conda environment.yml files (and in CI). We should definitely think about having a conda stdpopsim package for the next stdpopsim release.
