### ISSUE TITLE
cannot layer DFEs

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#1044]
The problem, is that by default contigs are created with a `genomic_element_type` for neutral mutations which spans the contig length and as currently implemented this creates a clash with any intervals handed to `add_DFE()`

**How to reproduce the problem:**
```
import stdpopsim
import numpy as np

species = stdpopsim.get_species("HomSap")
contig = species.get_contig("chr1")
contig.genomic_element_types
```
returns:
```
[GenomicElementType(mutation_type_ids=[0], proportions=array([0.]), intervals=array([[        0, 248956422]]))]
```
now if I add on selected mutations in a given range and look at the `genomic_element_types`
```
dfe = species.get_dfe("Gamma_K17")
gene_interval = np.array([[2000, 20000]])
contig.add_DFE(gene_interval,dfe)
contig.genomic_element_types
```
i see this
```
[GenomicElementType(mutation_type_ids=[0], proportions=array([0.]), intervals=array([[        0, 248956422]])),
 GenomicElementType(mutation_type_ids=[1, 2], proportions=array([0.3, 0.7]), intervals=array([[ 2000, 20000]]))]
```
so I can see that the default, neutral elements haven't been altered. this will lead to an error where intervals overlap when I simulate

```
ValueError: Intervals must be non-overlapping.
```

**Suggested fixes:**
Some possible fixes:

1. we could do something like the last DFE takes precedence over all other elements, so we effectively over write chunks
2. we could skip simulating neutral mutations altogether and instead use msprime for that. this could open the opportunity to use a mutation rate map too.

other ideas? @grahamgower @petrelharp @jeromekelleher @mufernando @izabelcavassim

**Comment by petrelharp** [comment]
`add_DFE` is not broken; it's the API that is, um, not ideal. You haven't done `contig.clear_genomic_mutation_types()`.

I'm going to rename this issue to reflect the underlying issue: how do we layer DFEs? (you're trying to layer two DFEs, one of which is "flat neutral".

**Comment by andrewkern** [comment]
> Two questions:
> 
> * should we allow layering of two non-neutral DFEs? (yes?)
> * do we want to specify the overall mutation rate, and have neutral mutations fill in the remainder? Or specify the neutral mutation rate? (the first thing?)

**Comment by andrewkern** [comment]
> I vote that for now when you use `add_DFE` it clears the contig of any previous GETs and MTs, adds the specified DFE and then fills out the neutral mutation rate automatically (by subtracting the sum of all the other GETs to a total mutation rate).

this sounds good. would we want to do all neutral mutation in msprime? how can we make this compatible with a mutation rate map?

**Comment by andrewkern** [comment]
closing this issue as #1078 add this functionality
