### ISSUE TITLE
Document API for adding selection

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1053]
I'd propose adding a new top-level section to the API page in the docs about annotations and selection. First let me try to take stock of things.

The basic thing that we want to be able to do is to say how the selection coefficent (mabye zero) of a new mutation is drawn, depending on where it is in the genome. We might also want to be able to label mutations (e.g., "coding" and "noncoding") beyond just their selection coefficients. (This leaves the overall *rate* of mutations to be specified separately.)
To do this, we need to somehow specify:
- a collection of intervals, and
- in each interval, what different "types" of mutations might happen, in what proportions, where each "type" has associated a distribution of selection coefficients (and, dominance coefficient(s)).

To do this, we've got the following classes, closely following how SLiM does it:

- [`MutationType`](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/ext/selection.py#L5): a "type" of mutation; carries a distribution of fitness effects, a dominance coefficient, and a label

- [`GenomicElementType`](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/ext/selection.py#L5): an assignment of 
*proportions* of various MutationTypes to a set of intervals. The MutationTypes are not actually carried along, but rather indices of these (see Contig).

- [`Contig`](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/ext/selection.py#L5) objects carry a *list* of GenomicElementTypes along with them. The intervals of each of these GenomicElementTypes need to be nonoverlapping. The Contig is *also* what actually carries the list of MutationTypes, I guess so that multiple GenomicElementTypes can produce mutations of the same MutationType.
 
- finally, we also need a [mutation rate](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/ext/selection.py#L5); since everything above specified *proporitons* of different types of mtuations, we need to determine the overall rate. Note that currently the mutation rate is just a number, but there's no conceptual obstacle to it being a RateMap.

As a way of *specifying* these things, we also have:

- the [DFE class](https://github.com/popsim-consortium/stdpopsim/blob/927d7a9b9733f0f20f78949a1c32f3249e1aaf25/stdpopsim/models.py#L308), which carries a list of MutationTypes and corresponding proportions

- the [Annotation class](https://github.com/popsim-consortium/stdpopsim/blob/927d7a9b9733f0f20f78949a1c32f3249e1aaf25/stdpopsim/annotations.py#L14), which will return an [array of intervals](https://github.com/popsim-consortium/stdpopsim/blob/927d7a9b9733f0f20f78949a1c32f3249e1aaf25/stdpopsim/annotations.py#L78) using the `get_chromosome_annotations` method.

Observation: this all seems very confusing, and seems like we have more layers than we need just to say "intervals plus distributions on these".

However, note that DFE + Annotation = GenomicElementType. So, I think the *user* should only ever have to work with DFEs and Annotations - the GenomicElementTypes are implementation details (that are very SLiM-specific, for one thing). They might want to know about MutationTypes, for analyzing the data; this is viewable from the DFE.

So - here's two alternative proposals:

1. Contigs carry with them a list of (DFE, Annotation) pairs. This list is in order of precedence, so that when intervals overlap the earlier ones in the list apply. Under the hood, this is collapsed into a list of nonoverlapping GenomicElementTypes, one per (DFE, Annotation) pair, but this is invisible to the user.

2. As we have now, Contigs carry with them only a list of GenomicElementTypes. Adding a (DFE + Annotation) to the Contig will add another GenomicElementType, and *remove* all bits of the intervals of previous GenomicElementTypes that overlap with this newly added one (so, later-added ones take precedence). If we go with this one I propose to rename `GenomicElementType` something more descriptive like `AnnotatedDFE` or `DFEandIntervals`.

The main difference between the two is that in (1) the Contig would know the *names* of its DFEs and Annotations. It's probably a bit more flexible down the road, also. 

Note that in either of these proposals, we'd need to do like in #1045: intially, the chromosome has neutral mutations everywhere, but adding a DFE would override this default neutral DFE with a new one, on some intervals.

Also, I propose that:
 
- The Contig has a list of MutationTypes (like currently), but this would be invisible. In this list, the first one is special - it is always the "neutral" MutationType, and will be added by msprime. Other than this one, MutationTypes are *not* shared between different DFEs. We'd tell which MutationTypes are this special neutral type either (a) with a special flag or (b) checking if they're of type `f`ixed with value 0.0.

**Comment by nspope** [comment]
@petrelharp Can this be closed now that #1078 is merged?

**Comment by petrelharp** [comment]
Yep; we've got [API docs](https://popsim-consortium.github.io/stdpopsim-docs/latest/api.html#selection-and-dfes) and [examples](https://popsim-consortium.github.io/stdpopsim-docs/latest/tutorial.html#incorporating-selection).
