### ISSUE TITLE
implement QC for DFEs

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1055]
... following that for DemographicModels.

**Comment by xin-huang** [comment]
We should add a `register_qc()` similar to https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/models.py#L171 in `dfe.py`?

**Comment by xin-huang** [comment]
Hi @petrelharp 

I started to implement the DFE QC 

https://github.com/popsim-consortium/stdpopsim/pull/1292

**Comment by petrelharp** [comment]
This was closed in #1292
