### ISSUE TITLE
Require proportions of mutation types to always be 1.0

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1071]
Following on #1062 - the proposal is that for DFEs,

-    proportions of different mutation types always sum to 1
-    whether or not mutations are added by msprime is not a property of the contig, since is behavior of the simulation engine
-    we should just always have the SLiM engine pass neutral mutations off to msprime, and not even have an option that controls this behavior, since why would someone want to turn it off
-    so, the SLiM engine is responsible for correctly not simulating neutral mutations but then adding them back in

**Comment by petrelharp** [comment]
I'm thinking we'll *define* the mutation types, just not use them.

**Comment by andrewkern** [comment]
pretty sure this was now closed by #1078 

feel free to reopen if not
