### ISSUE TITLE
make intervals and annotations code consistent and make all intervals integer-valued

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1079]
There's a number of operations on intervals in `utils.py` that are public but mostly undocumented. These are:
- `check_intervals_array_shape`
- `check_intervals_validity`
- `build_intervals_array`
- `mask_intervals`

Of these, I think that `check_intervals_array_shape` and probably `check_intervals_validity` should be private, and we should document the others.

Also, right now it's easy to get very confusing errors trying to pass in interval arrays having floats rather than ints. I think we should require that intervals are *always* of integer type, and give informative errors if they are not. We should also make sure we give an informative error in the case where nested lists are passed in instead of a numpy array. 

I'm of two minds whether we want to convert, say `[[0, 2.0], [4.0, 10]]` to the integer-valued numpy array.

**Comment by petrelharp** [comment]
Furthermore, right now `Annotations` returns an array of floats. Is this desired, or do we want to *always* have intervals be ints? Options are:
- intervals are floats: easier, as RateMaps have float coordinates and contig.length is a floa and indeed all other coordinates in msprime/tskit, Conversion to int happens in the SLiM code.
- intervals are ints: more consistent as we're always doing things with integer coordinates actually.

**Comment by petrelharp** [comment]
Also - I think that `contig.add_DFE( )` should take an Annotation object for the `intervals=` argument, in which case it Does the Right Thing.

**Comment by grahamgower** [comment]
I vote for integers. I think floats are a legacy that we should try to remove. In particular, contig.length is a float to support the `length_multiplier` params, which should be deprecated as discussed in #670.

**Comment by andrewkern** [comment]
> Also - I think that `contig.add_DFE( )` should take an Annotation object for the `intervals=` argument, in which case it Does the Right Thing.

+1 -- i think we should definitely do this
