### ISSUE TITLE
Print for mutation and recombination rates using the scientific notation

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/stdpopsim#1093]
**Short description of the problem:**
when we print recombination rate it prints the round value:

**How to reproduce the problem:**
```
species = stdpopsim.get_species("DroMel")
contig = species.get_contig("chr2L")
print(contig.recombination_map)
```
which produces
```

┌──────────────────────────────────────────────┐
│left  │right     │       mid│      span│  rate│
├──────────────────────────────────────────────┤
│0     │23513712  │  11756856│  23513712│  0.00│
└──────────────────────────────────────────────┘
```
(recombination_rate is shown to be `0.00`, but is actually just very low.)

**Suggested fixes:**
not sure where this is located but I would be glad to fix it when I find out the print method for both recombination and mutation rate

**Comment by petrelharp** [comment]
Ah, this is in msprime, actually.

**Comment by petrelharp** [comment]
I think I've got this fixed up over at https://github.com/tskit-dev/msprime/pull/1906 although it won't take effect until the next msprime release.

**Comment by petrelharp** [comment]
I'm going to close this, anyhow.
