### ISSUE TITLE
add gene conversion rates to the SLiM engine

### ISSUE THREAD

**Issue by fbaumdicker** [popsim-consortium/stdpopsim#1114]
**Enable stdpopsim to pass the gene conversion rate and mean gene conversion tract length to SLiM engine**
*Gene conversion is an important but often overlooked mechanism, not only for haploids but also for diploids.*

**Rationale and considerations:**
*in #1106 we are currently adding gene conversion as two parameters of the species/contigs that are passed to the msprime engine. It would make sense to also pass the gene conversion rate and the mean gene conversion tract length to the SLiM engine.*

**Comment by petrelharp** [comment]
Now that #1106 is in, we should do this.

**Comment by nspope** [comment]
Related to #1332, I think there may be some parameterization differences to reconcile.

**Comment by nspope** [comment]
Closed by #1355.

**Comment by jeanrjc** [comment]
Hello,
I'm late to the party, but has this feature (Bacterial recombination in SLiM engine) been implemented yet ? I did not find it after a quick look at the different related issues/PR.

In the paper about adding species in stdpopsim, it's written that it's done (or at least, this is how I understand it): 

> To address this [bacterial recombination], we made use of features of the msprime and SLiM simulation engines for modeling non-crossover recombination.

Best

**Comment by igronau** [comment]
I think that It's possible to model bacterial recombination in SLiM by setting the proportion of non-crossover recombination to 1. Am I right, @petrelharp?
