### ISSUE TITLE
Correct labels of populations on demesdraw figures?

### ISSUE THREAD

**Issue by sunyatin** [popsim-consortium/stdpopsim#1123]
Dear all,

I feel like the ordering of population labels for several of the Homo sapiens demographic models (eg. PapuansOutOfAfrica_10J19, OutOfAfricaArchaicAdmixture_5R19) that are represented in the [doc](https://popsim-consortium.github.io/stdpopsim-docs/main/catalog.html#sec_catalog_HomSap_models) are suspicious... I feel like they correspond to the order of the populations_configuration, but not to the actual ordering that demesdraw performs. For instance, for [OutOfAfricaArchaicAdmixture_5R19](https://popsim-consortium.github.io/stdpopsim-docs/main/_images/sec_catalog_homsap_models_outofafricaarchaicadmixture_5r19.png), the pops are ordered in the figure, from left to right as:

CHB, YRI, Neanderthal, ArchaicAFR, CEU

But I would rather see:

ArchaicAFR, YRI, CEU, CHB, Neanderthal

What do you think?

Cheers,
Rémi

**Comment by grahamgower** [comment]
Yes I think you're right. Ping @aabiddanda.

**Comment by aabiddanda** [comment]
Great spot @sunyatin - it was a remarkably simple fix and an oversight on my part. I've put in a PR to fix this: #1124 just now. If you have any comments on the catalog or the images feel free to let me know!

**Comment by grahamgower** [comment]
Closed by #1124.
