### ISSUE TITLE
Create a DFE debugger

### ISSUE THREAD

**Issue by izabelcavassim** [popsim-consortium/stdpopsim#1147]
*This template is a suggestion that may not fit your issue: delete/modify anything!*

**Short description of what you'd like added:**
Create a DFE debugger as suggested by @mufernando. The idea is to follow more or less the demography debugger 
such as model.get_demography_debugger().print_history()
The function get_demography_debugger().print_history() is actually not working under the current version, instead 
one can use print(model.model.debug()). See #992 for details.

basically it would display information about where selection is placed, what proportions of neutral vs nonneutral mutations were used, what DFE model used, and demographic model used, what mutation rate, what recombination rate, what genetic map if any. Anything else? Ben Haller said that there is something like that already implemented in SLiM: "in SLiM if you click the button (right-pointing hand icon) to open the “object tables” auxiliary window, and you hover the mouse over an entry in the mutation types table there for a second or two, it will show a little graph of the DFE function defined for that mutation type".

We would want to do it in python and the CLI mode, right? 
Any other thoughts?

**Comment by petrelharp** [comment]
This is a nice idea. What is it a method of? Perhaps this is just a more informative `print( )` method for `Contig`? Looking at an example, 
```
species = stdpopsim.get_species("HomSap")
dfe = species.get_dfe("Gamma_K17")
contig = species.get_contig("chr20")
model = species.get_demographic_model("OutOfAfrica_3G09")
samples = model.get_samples(100, 100, 100)  # YRI, CEU, CHB

exons = species.get_annotations("ensembl_havana_104_exons")
exon_intervals = exons.get_chromosome_annotations("chr20").astype("int")
contig.add_dfe(intervals=exon_intervals, DFE=dfe)

engine = stdpopsim.get_engine("slim")
ts = engine.simulate(
    model,
    contig,
    samples,
)
```
... note that we pass in separately `model` and `contig`, so there's no further-downstream thing we could provide a summary method for besides the `ts`.
