### ISSUE TITLE
store annotation information in metadata

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1148]
Proposal (with @mufernando):
In the SLiM script we know what mutation type goes in each genomic region, but we don't use that information later when adding neutral mutations with msprime.
So, we should in fact store that information in top-level metadata, and use the information to tell msprime which mutation types to add.

To do this, we need to:

1. store in metadata, for each DFE, (a) the intervals it applies to, (b) and the mutation types it has, including the SLiM ID and whether it's being simulated by SLiM
2. 
2. when we add mutations with msprime, we no longer have to re-compute the msp_rate_map, instead we loop over the mutation types within each dfe, and, if it's neutral, we add the mutations with msprime.

**Comment by nspope** [comment]
Closing as I think we have this in the metadata (it's used during recapitation). Although, we may not want to document as it could well change.
