### ISSUE TITLE
Specify interval to simulate from genetic map

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#117]
It would be nice to be able to specify an interval from a genetic map in Species.get_contig. This could be done by adding an ``interval`` argument, and using this to pull out the subsets of the recombination map in question, setting the flanking recombination rates to 0.

**Comment by andrewkern** [comment]
would be great to do this in *physical* coords, so that the `sequence_length` of the simulation followed naturally from the `interval` argument.

**Comment by jeromekelleher** [comment]
Superceded by #402
