### ISSUE TITLE
proportion of neutral mutations in Kim DFE?

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1189]
This is currently [set to 30%](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/dfes.py#L42), but we think this was just based on a rough guess. We should at least document the rough guess, and probably make a better one.

**Comment by apragsdale** [comment]
I think the ratio that they used is 2.31:1 (nonsyn:syn), so 0.3 is pretty much right (1/3.31 = 0.302).

**Comment by mufernando** [comment]
aha, that is exactly what I assumed.

> [Murillo Fernando Rodrigues](https://app.slack.com/team/U01CAUEC2LE)  [4:40 PM](https://popsimgroup.slack.com/archives/C026K1JFAMQ/p1626291648032200)
I did something analogous to this I think?
[4:41](https://popsimgroup.slack.com/archives/C026K1JFAMQ/p1626291669032700)
note I say the proportion oof mutations that have their fitness drawn from the kim dfe to be 70%
[4:41](https://popsimgroup.slack.com/archives/C026K1JFAMQ/p1626291677033100)
that is 2.31/3.31

**Comment by mufernando** [comment]
note though that that is an assumption of the Kim DFE, not something that they estimated necessarily. https://academic.oup.com/genetics/article/206/1/345/6064197?login=false

We won't be able to do better, I don't think... Unless we want to completely specify a nucleotide mutation model and ancestral sequence...

**Comment by ckyriazis** [comment]
The 2.31:1 ratio comes from Huber et al. 2017 - this is the relevant text from their SI:

> The nonsynonymous and synonymous sequence lengths (LNS, LS) depend
on the transition/transversion ratio and CpG mutational bias. We assumed a
transition:transversion ratio of 2:1 in Drosophila (3, 4) and 3:1 for human exons (5, 6). Further,
we assumed a 10x mutational bias at CpG sites in humans, but no such effect in Drosophila (7).
This leads to multipliers of LNS = 2.85 x LS in Drosophila, and LNS = 2.31 x LS in humans.

**Comment by petrelharp** [comment]
Ok, we ought to document this somewhere. (And, make some more information appear about DFEs in the catalogue?)

**Comment by grahamgower** [comment]
Wasn't this just translated from the 2.31:1 ratio of weights in my original KimDFE selection example? https://github.com/popsim-consortium/stdpopsim/blob/380ab4f00e3110b94f551fcdd3048704872d562a/docs/selection_example.py#L144-L156

**Comment by izabelcavassim** [comment]
I think we can close this one based on #1198
