### ISSUE TITLE
add log file to SLiM output

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1190]
As discussed yesterday at the meeting, it would be useful to have an optional logfile output from SLiM that writes out periodically the mean and SD of fitness per population. I'd propose adding an argument `logfile_interval` to the SLiM engine that defaults to `0`, meaning "don't log", but can be set to something positive to enable logging. I can do a PR up for this.

**Comment by andrewkern** [comment]
sounds good to me

**Comment by izabelcavassim** [comment]
It should be closed by #1200
