### ISSUE TITLE
Update stdpopsim docs

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/stdpopsim#1229]
The stdpopsim documentation should be updated.
For example, `update_ensembl_data.py` no long exists https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#adding-updating-a-genome-definition

And the following species have demographic models and their parameter tables should be added into catalog.
- [ ] AnaPla
- [ ] AnoGam
- [ ] BosTau
- [ ] PanTro

**Comment by nspope** [comment]
Looks like both these issues have been resolved. 

#1391, #1389, and follow-ups will do a once-over the docs to make sure the text and code blocks are up-to-date.
