### ISSUE TITLE
Update catalog and "preliminary/pre-QC" designation?

### ISSUE THREAD

**Issue by lauterbur** [popsim-consortium/stdpopsim#1230]
The catalog docs need to be updated with all of the species added in the past year or so. 

In addition, there should be some way of flagging "preliminary" species/models in the catalog (those that have been merged but not yet QC'd, as described here https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#demographic-model-review-process) vs. fully QC'd species/models.

These are the species in the codebase but not in the catalog:

| Species | Issue | QC status | Merged | In catalog |
|------------|------------|------------|------------|------------|
| PanTro | https://github.com/popsim-consortium/stdpopsim/issues/1220 | not started | yes | no |
| HelAnn | https://github.com/popsim-consortium/stdpopsim/issues/1219 | not started | yes | no |
| AnoCar | https://github.com/popsim-consortium/stdpopsim/issues/895 | finished | yes | no |
| ChlRei | https://github.com/popsim-consortium/stdpopsim/issues/890 | finished | yes | no |
| AedAeg | https://github.com/popsim-consortium/stdpopsim/issues/889 | finished | yes | no |
| AnaPla | https://github.com/popsim-consortium/stdpopsim/issues/888 | finished | yes | no |
| StrAga | https://github.com/popsim-consortium/stdpopsim/issues/881 | not finished | yes | no |
| HelMel | https://github.com/popsim-consortium/stdpopsim/issues/880 | not finished | yes | no |
| DroSec | https://github.com/popsim-consortium/stdpopsim/issues/873 | not finished | yes | no |
| AnoGam | https://github.com/popsim-consortium/stdpopsim/issues/859 | not finished | yes | no |
| BosTau |  https://github.com/popsim-consortium/stdpopsim/issues/559 | finished | yes | no |
| ApiMel | https://github.com/popsim-consortium/stdpopsim/pull/1025 | not started | yes | no |
| CaeEle | https://github.com/popsim-consortium/stdpopsim/issues/1226 | not started | yes | no |
| GasAcu | https://github.com/popsim-consortium/stdpopsim/issues/1091 | not started | yes | no |

**Comment by grahamgower** [comment]
Note that there are also pending QC issues for PonAbe (#544), HomSap (#543), and AraTha (#539).
