### ISSUE TITLE
upload C. elegans RockmanRIAIL_ce11 genetic map to AWS

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#1234]
Ping @attrna. Can you please coordinate with @andrewkern to upload the Rockman genetic map file to Amazon Web Services and update the url in the stdpopsim code? (currently it points at http://sesame.uoregon.edu/~ateterina/rockman2009_maps.tgz)

**Comment by petrelharp** [comment]
This has been done... but there was an error, @chriscrsmith will send @andrewkern the new ones.

**Comment by grahamgower** [comment]
Great. Can we please have the genome assembly id in the tarball filename too?

**Comment by andrewkern** [comment]
closing this issue. pretty sure this is all done.
