### ISSUE TITLE
Set DFE neutral mutations to happen only in exons

### ISSUE THREAD

**Issue by JesseGarcia562** [popsim-consortium/stdpopsim#1237]
**Short description of the problem:**
Hi, 

I'm trying to simulate some models with a DFE that has neutral synonymous mutations and selected nonsynonymous mutations. I would like these mutations to only occur in exons. I thought I had this set up correctly but I'm seeing neutral mutations occurring outside of the exon regions and all along the contig. Is there a way to set up a simulation with a DFE that has neutral mutations that only occur in exon regions and not the whole contig? I am using stdpopsim version '0.1.3b2.dev37+g1c48909'

**How to reproduce the problem:**
```

import stdpopsim
import pandas

def simple_dfe_creator(selection_coefficient, dominance_coefficient):
    
    id = f'This DFE has deleterious variation at s = {selection_coefficient}, with h ={dominance_coefficient}.'
    description = f'Deleterious DFE. This DFE has deleterious variation at s = {selection_coefficient}, with h = {dominance_coefficient}.'
    long_description = f"""
    Return neutral and negative MutationType()s representing a fixed DFE. 
    Fixed deleterious variation at s = {selection_coefficient}, with h = {dominance_coefficient}.
    """
    citations = [
        stdpopsim.Citation(
            author="Not Published.",
            year=2022,
            doi="No Paper"
        )
    ]

    synonymous_proportion = 1/3.31
    nonsynonymous_proportion = 2.31/3.31
    neutral = stdpopsim.MutationType()
    omega_1 = stdpopsim.MutationType(
        dominance_coeff=dominance_coefficient,
        distribution_type="f",  
        distribution_args=[selection_coefficient],
    )
    
    return stdpopsim.DFE(
    id=id,
    description=description,
    long_description=long_description,
    mutation_types=[neutral, omega_1],
    proportions=[synonymous_proportion, nonsynonymous_proportion],
    citations=citations,
    )

exon_interval = {"exon_start": [450000] , "exon_end": [650000] }
exon_interval = pandas.DataFrame.from_dict(exon_interval)
selection_coefficient = -0.0001
dominance_coefficient = 0.5
average_recombination_rate = 1e-08
mutation_rate = 1.5e-08
window_length = 1e6
slim_scaling_factor = 10
seed = 32

exon_intervals = exon_interval[["exon_start", "exon_end"]].to_numpy()
species = stdpopsim.get_species("HomSap")

## In this DFE I don't know how many neutral synonymous mutations are being made.
dfe = simple_dfe_creator(selection_coefficient,dominance_coefficient )
contig = stdpopsim.Contig.basic_contig(length=window_length, mutation_rate=mutation_rate, recombination_rate=average_recombination_rate)
model = species.get_demographic_model("OutOfAfrica_3G09")
samples = model.get_samples(100)  # YRI

## I thought this line meant the DFE was only applied to the exon interval
contig.add_dfe(intervals=exon_intervals, DFE=dfe)

engine = stdpopsim.get_engine("slim")
tree_sequence = engine.simulate(model, contig, samples, slim_scaling_factor=slim_scaling_factor, seed = seed)

## Inspect the vcf and see that mutations occur at positions that are not within 450,000bp ("exon_start") and 650,000bp ("exon_end")

with open("output.vcf", "w") as vcf_file:
    tree_sequence.write_vcf(vcf_file)

```

**Suggested fixes:**
I think there are some issues (#646 & #999) that kind of relate to this, but I'm not too sure. Maybe updating my stdpopsim version will fix this? I tried this, but I couldn't find a tutorial for adding a DFE with the new DFE class. Let me know what you think.

Thanks,
Jesse

**Comment by grahamgower** [comment]
Hi @JesseGarcia562. The DFE functionality in stdpopsim is still quite new and there may yet be bugs lurking. So you should definitely use the latest version. I checked the version you're using (1c48909, from December last year), and there have been some DFE-related fixes made since then. However...

> I thought I had this set up correctly but I'm seeing neutral mutations occurring outside of the exon regions and all along the contig.

This is expected. The DFE is applied to the intervals specified, but all parts of the contig outside those intervals have neutral mutations applied with the nominal rate.

> Is there a way to set up a simulation with a DFE that has neutral mutations that only occur in exon regions and not the whole contig?

What exactly are you trying to achieve by not having any neutral mutations? Maybe @izabelcavassim or @xin-huang can suggest a good way to do this?

**Comment by JesseGarcia562** [comment]
Hi,

Okay, I will update. Thanks!

I am trying to have neutral mutations in my simulations, but only have neutral mutations occur in the exon intervals. This is mainly because I want to model neutral "synonymous" mutations and not mutations that are neutral and not in exon intervals. One reason I would like to do this is that I have an estimate of the ratio of new synonymous to new nonsynonymous mutations (1 : 2.31) that occur,  but not an estimate of the ratio of neutral mutations that happen all along a contig to nonsynonymous mutations. 

Does this make more sense?

**Comment by mufernando** [comment]
@JesseGarcia562 why are you simulating a non-exon portion if you don't care about it? might be easier to just simulate the exon. otherwise you could remove the non-exon portions from the tree sequence before creating your VCF using tskit's `delete_intervals` https://tskit.dev/tskit/docs/stable/python-api.html?highlight=interval#tskit.TreeSequence.delete_intervals

**Comment by JesseGarcia562** [comment]
Ah good question. In my actual simulations, I have multiple exons on a contig and a human based recombination rate map. If I don't simulate the non-exon portion, then I'd need to worry about adjusting the recombination rate map to reflect the absence of non-exon base pairs. 

I think your delete intervals suggestion could work. But one question, would the ratio of neutral mutations that occur in exons to selected mutations that occur in exons be the ratio specified by the DFE? I'm mostly concerned that by using `delete_intervals` I won't be able to discern the neutral mutations that are occurring from the DFE and the neutral mutations with which the whole contig is being filled with neutral mutations. 

More specifically, I would imagine that some neutral mutations that are not specified by the DFE will occur in exon regions, and `delete_intervals` will not remove them from the tree sequence.

**Comment by mufernando** [comment]
ah, I see. I think it isn't clear how the DFEs work. by default, a neutral DFE is added that spans the whole contig. when you call:

```## I thought this line meant the DFE was only applied to the exon interval
contig.add_dfe(intervals=exon_intervals, DFE=dfe)
````

That means that the DFE in those intervals will now be replaced with your specified DFE. there won't be any mutations in `exon_intervals` which are not in your `dfe` object.

Note though that in the DFE you specify the proportions with which each mutation type can happen within a set of intervals. This does not imply that the ratio of mutation types at the end of a simulation will be the same (because selection will change the probability of loss of a new mutation).

I don't think you'll need `delete_intervals` actually. But when you count up your mutations in the VCF you will only look at sites within your intervals (and ignore everything else). In the future it will be possible to only simulate one portion of a chromosome, so your pipeline would be much easier to implement!

**Comment by JesseGarcia562** [comment]
Oh ok, that makes so much more sense! Just to be clear, there's a neutral DFE that exists along the whole contig when you create the contig, but when you use `contig.add_dfe(intervals=exon_intervals, DFE=dfe)` the whole contig neutral DFE gets removed for the exon intervals specified in `exon_intervals`. Only the mutations specified by the DFE I created will exist in those `exon_intervals`. 

And yeah! That's what I'm thinking. The proportions I set in the DFE specify the ratio at which _new_ mutations occur, but not the rate with which they persist. 

Thanks for your help, my fix will be to only analyze the mutations in the intervals and not use `delete_intervals`. I have one last question, if I wanted to do a sanity check or write some tests in my code that made sure that only mutations specified by my DFE and not the default DFE exist in the exon intervals (or my analysis) would you have any suggestions? I mostly want to make sure I'm not making any 'off-by-one' errors when doing the interval stuff and wondering if there are any characteristics/attributes/metadata associated with the mutations that are generated by the default neutral DFE.

**Comment by mufernando** [comment]
> Oh ok, that makes so much more sense! Just to be clear, there's a neutral DFE that exists along the whole contig when you create the contig, but when you use `contig.add_dfe(intervals=exon_intervals, DFE=dfe)` the whole contig neutral DFE gets removed for the exon intervals specified in `exon_intervals`. Only the mutations specified by the DFE I created will exist in those `exon_intervals`.

correct!

> have one last question, if I wanted to write some tests in my code that made sure that only mutations specified by my DFE and not the default DFE exist in the exon intervals (or my analysis) would you have any suggestions?

this will depend on which version of stdpopsim you have. Recently I added all the information wrt to DFEs to the top-level metadata of tree sequences produced by SLiM engine in stdpopsim https://github.com/popsim-consortium/stdpopsim/blob/5e67d7167b1e0f0c94616f3f9ada83eb3d0fe2f7/stdpopsim/slim_engine.py#L639

Here https://github.com/popsim-consortium/stdpopsim/blob/5e67d7167b1e0f0c94616f3f9ada83eb3d0fe2f7/tests/test_slim_engine.py#L1020 you can see how to access the metadata. You can call

```
ts.metadata["stdpopsim"]["DFEs"]
```

**Comment by JesseGarcia562** [comment]
Beautiful, thanks!
