### ISSUE TITLE
QC for SinglePopSMCpp_1W22 (Papio_anubis)

### ISSUE THREAD

**Issue by saurabhbelsare** [popsim-consortium/stdpopsim#1254]
**PR for new model:** https://github.com/popsim-consortium/stdpopsim/pull/1216
**Original paper:** https://doi.org/10.1093/gbe/evac040
**Parameter values:** Section "LD-based Recombination Estimates" in methods of above paper has the description of the inference procedure. I obtained the file containing the actual parameters from the authors directly. Sharing with @chriscrsmith  who is doing the QC directly. 
**Population indices:** There is only one population

**Potential issues that might lead to differences between the model implementations:**

**QC'er requests:**

**Comment by petrelharp** [comment]
Closed in #1261
