### ISSUE TITLE
404 error in mybinder

### ISSUE THREAD

**Issue by xin-huang** [popsim-consortium/stdpopsim#1255]
**Short description of the problem:**
I got `404` error after clicking `launch binder` in `README.md`

**How to reproduce the problem:**
Click `launch binder` in `README.md`

**Suggested fixes:**
looks like `stdpopsim_example.ipynb` is missing

**Comment by petrelharp** [comment]
Hm - do you know where that file went and how to put it back where it's supposed to go?

**Comment by grahamgower** [comment]
It was deleted in b7cd71fe2fe4ebf101cf1132e3efb2c0f91c2443 (#1042). I guess this was accidental and we can just put it back? ping @andrewkern

**Comment by andrewkern** [comment]
yes this must have been completely accidental!
