### ISSUE TITLE
should `samples` be diploid?

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1282]
*Edit:* the question here is whether to make "sample numbers" count numbers of diploids? This would be a substantial change, but arguably less confusing, especially as it's matching msprime and SLiM.

As noted over in #1281, the `samples` argument in msprime now produces by default diploid samples, although we produce individuals with `ploidy=1`, and so sp `write_vcf` now fails if given the `ploidy` argument.

**Comment by petrelharp** [comment]
HOWEVER, currently [samples are *not* diploid](https://github.com/popsim-consortium/stdpopsim/blob/3166eadd31097771c6b1dc4dd2ce8e0792f02220/stdpopsim/models.py#L207). We need to (a) think about changing this, and (b) clearly document what we do.

In fact, currently using the msprime engine we ask for *haploid* samples, so in the resulting tree sequence we get individuals with ploidy=1. This is confusing (for diploid species anyhow). In SLiM we get diploid individuals (the same number of chromsomes, though.

I really do want to switch to samples being diploid, but then that'd be not backwards compatible, so we probably don't want to do that, actually. BUT it's inconsistent with both SLiM and msprime now, so maybe we do?

**Comment by bhaller** [comment]
In cases like this, I suggest breaking with backward compatibility in a way that forces the user to confront the change.  In other words, don't just change the meaning of an existing parameter from haploid to diploid; that will surprise people and hide the fact that a change occurred.  Instead, deprecate the old parameter (either breaking it entirely, or supporting it with a warning and a "compatibility mode" that converts from haploid to diploid by dividing by two, I guess) and introduce a new parameter.

Opinions vary on this, but personally I am not a fan of the perspective that an API, once released, must be supported forever; that leads to stale APIs based upon bad and regrettable choices that are frozen in stone forever.  Instead, a smart deprecation policy should be adopted that helps users move forward to newer and better APIs.

(@petrelharp you saw the consequences of not properly deprecating and shifting first-hand, with my incorrect handling on the `scriptBlocks` property!  Whoops!)

**Comment by jeromekelleher** [comment]
I agree with @bhaller - we can't silently change the meaning. It may be best to consider a different API entirely.

We also need to consider the CLI.

**Comment by petrelharp** [comment]
Yep - or, leave it the same.

**Comment by petrelharp** [comment]
We discussed this in the meeting yesterday, and the consensus seemed to be that we should change it. A big argument in favor is that currently the msprime and SLiM engines produce tree sequences with haploid and diploid individuals, respectively, and so doing `write_vcf( )` with the two gives fairly different results. This seems not so good.

So, to make the change we would need to figure out a new API for specifying samples.
- In python, the interface is via the [`DemographicModel.get_samples( )` method](https://popsim-consortium.github.io/stdpopsim-docs/latest/api.html#stdpopsim.DemographicModel.get_samples); so we'd just need a new name for this, really. (maybe `.sample_setup( )`? or `.sampling( )`?)
- But, in the CLI the number of samples is a positional parameter, like `stdpopsim DroMel 4 --options`. So I think our options are to either make a breaking change, document it a lot, and count on people noticing they're getting twice as many genomes as before, or make the number of samples not posititional any more (`e.g., `--samples`).

But, we'd like to get some more thinking about this - @jeromekelleher, @bhaller?

**Comment by petrelharp** [comment]
Also note this relates to #1111.

**Comment by bhaller** [comment]
> But, we'd like to get some more thinking about this - @jeromekelleher, @bhaller?

I don't think I have any opinion beyond what I wrote above, sorry.  Whether people will notice the change or not is hard to guess; and I don't have a sense of whether a non-positional argument for this would be a step forwards or backwards.  :->

**Comment by grahamgower** [comment]
How about `get_individuals()` and `--individuals`?
