### ISSUE TITLE
log-normal DFE doesn't allow negative values

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1308]
Over in #1292 I turned on the test that actually simualted from all of the defined DFEs. The [`DroMel.LognormalPlusPositive_R16`](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/DroMel/dfes.py#L53) model uses a lognormal distribution for deleterious mutations. However, the simulation run errored because the selection coefficients that it produced were positive, and sometimes very very large. The problem is that we're trying to use something like `rlnorm(meanlog=-3, sdlog=2)` to get negative numbers. That's in fact how many distributions work in eidos: passing a negative mean for a positive distribution gets you numbers drawn from that distribution multipied by -1. However, the arguments to `rlnorm( )` are the mean and SD on a log scale, i.e., `mean(log( rlnorm(10000, -2, 4) ))` will be close to -2. (and so `mean(rlnorm(10000, -2, 4))` will be close to `exp(-2)` which is `>0`)

So, we need to fix up our underlying log-normal implementation somehow to allow this possibility.

I've also commented out the DFE so it doesn't error (in that PR). I think there are other issues with it (for instance, in the code it calls the meanlog and sdlog parameters the "shape" and "scale", which they are not).

As for the fix: recall that for most distributions we can use SLiM's built-in distribution types, e.g. `"e"` for exponential; however, it doesn't have a built-in log-normal, so we provide that one [in eidos code](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/dfe.py#L111).  I propose *removing" the `"l"` distribution type (which is what we used for "log-normal", and replacing it with "lp" for "positive log-normal" and "ln" for "negative lognormal".

**Comment by andrewkern** [comment]
> As for the fix: recall that for most distributions we can use SLiM's built-in distribution types, e.g. `"e"` for exponential; however, it doesn't have a built-in log-normal, so we provide that one [in eidos code](https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/dfe.py#L111). I propose *removing" the `"l"` distribution type (which is what we used for "log-normal", and replacing it with "lp" for "positive log-normal" and "ln" for "negative lognormal".

seems like a perfectly fine fix to me. in practice, are people fitting models of this sort?

**Comment by petrelharp** [comment]
Well, I ran into this because Ragsdale et al used a (negative) log-normal? So, yes?

**Comment by andrewkern** [comment]
👍
