### ISSUE TITLE
AraTha DFE

### ISSUE THREAD

**Issue by chriscrsmith** [popsim-consortium/stdpopsim#1321]
**Short description of what you'd like added:**
The catalog would benefit from a DFE(s) for Arabidopsis.

**Rationale and considerations:**
In particular, we'd like to have this for the analysis2 pipeline and paper.

**Comment by chriscrsmith** [comment]
Opened a QC issue for this: #1344

**Comment by petrelharp** [comment]
Closed in #1324.
