### ISSUE TITLE
Fix checkpointing behavior in SLiM rejection sampling

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1328]
As described in #1325, checkpointed rejection sampling can easily produce incorrect simulations. The only situation where checkpointing is "safe" is when a mutation is drawn and there are no other extant mutations that are being conditioned on.

I think the following would fix the issue:

- Remove `save` option from python API (extended event python classes)
- Remove save mechanics from SLiM engine for `ConditionOnAlleleFrequency` events
- In `slim_makescript`, sort `DrawMutation` events by time and set `save` flag only at the first event

**Comment by petrelharp** [comment]
I agree, this sounds like the right thing to do!
