### ISSUE TITLE
should SLiM follow msprime in doing Jukes-Cantor mutations?

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1334]
Since msprime 1.0, `sim_mutations( )` has by default produced JC mutations (and hence, nucelotide mutations). Questions:

1. Do we want to do JC for msprime mutations? (I think yes?)
2. Do we want to do JC for *SLiM* mutations? (I also think yes?)
3. Do we want to convert the output of SLiM simulations so that the ancestral and derived states are nucleotides rather than lists of SLiM IDs (which produce technically invalid and at least weird VCFs)? We'd do this with [`pyslim.convert_alleles( )`](https://tskit.dev/pyslim/docs/latest/python_api.html#pyslim.convert_alleles). (I'm not sure? maybe by default but with an optional parameter?) This would mean that the tree sequences that get output *can't* be loaded back into SLiM (unless there's an optional parameter that is toggled).

**Comment by petrelharp** [comment]
We discussed this in the meeting this week, and I think the answer is "yes" to all of these. Do you see any issue with this, @bhaller? @jeromekelleher?

**Comment by jeromekelleher** [comment]
I'd say yes - the majority of users won't know anything about SLiM and will expect to get VCFs out the other end with ACGT alleles.

**Comment by bhaller** [comment]
It generally makes sense to me.  The only gotcha is that an ancestral state of A and a mutation back to A are not the same thing in SLiM, nor are two different mutational lineages to T at the same position that arose independently.  So you may want to think about various "uniquing down" strategies if you want stdpopsim to really make complete biological sense when selection is involved – IBS rather than IBD.  The SLiM manual has quite a bit of discussion about this in version 4.0, including example recipes for various types of uniquing down, etc.  In my opinion it's a weakness in SLiM's design, and maybe I will try to address it at some point.  For now, users have to worry about it.  Besides that, yes – getting ACGT out from stdpopsim by default makes good sense.

**Comment by petrelharp** [comment]
Hm - looking at the details, it's going to quite annoying to actually shift the script to being a nucleotide model. HOWEVER, since all we want is Jukes-Cantor mutations, we could equivalently just call [`pyslim.generate_nucleotides`](https://tskit.dev/pyslim/docs/latest/python_api.html#pyslim.generate_nucleotides) on the tree sequence afterwards. I think this is definitely what we want to do, since changing the SLiM code would also require re-doing how the testing code works; probably in the future someone will want to mess around with nucleotide mutations more, and can get into the details at that point.

My only question about this is how slow the calls to `generate_nucleotides` and `convert_alleles` will be - they both loop over the mutations and do nontrivial things in python.

**Comment by bhaller** [comment]
Hmm.  At that point, it sounds to me like maybe this ought to be optional, or just left up to the user to do if they want to.  If it's a time-consuming operation that the user may or may not want, and if it's easy for them to do it themselves, then maybe just leave it up to them, and document how they would do it?  Or at a minimum I'd suggest making it the default behavior but having a way to turn it off, for users who either (a) don't even want nucleotides, or (b) don't want to pay the price in terms of speed?

**Comment by petrelharp** [comment]
We should see how time-consuming it is, but yes.

**Comment by nspope** [comment]
Hmm, `generate_nucleotides` and `convert_alleles` seem prohibitively expensive ... for example,
```python
import stdpopsim
import pyslim
import time

#from test_slim_engine::TestAPI::test_recombination_map
engine = stdpopsim.get_engine("slim")
species = stdpopsim.get_species("HomSap")
contig = species.get_contig("chr1", genetic_map="HapMapII_GRCh37")
model = stdpopsim.PiecewiseConstantSize(100)
samples = model.get_samples(10)

start_sim = time.time()
ts = engine.simulate(
    demographic_model=model,
    contig=contig,
    samples=samples,
    slim_burn_in=0.1,
)
print(f"engine.simulate {time.time() - start_sim} seconds")

start_gen = time.time()
ts = pyslim.generate_nucleotides(ts)
print(f"pyslim.generate_nucleotides {time.time() - start_gen} seconds")

start_conv = time.time()
ts = pyslim.convert_alleles(ts)
print(f"pyslim.convert_alleles {time.time() - start_conv} seconds")

print(f"num_mutations {ts.num_mutations}")
```

```python
#engine.simulate 2.703385829925537 seconds
#pyslim.generate_nucleotides 533.7081677913666 seconds
#pyslim.convert_alleles 520.3803863525391 seconds
#num_mutations 3288
```

**Comment by petrelharp** [comment]
OMG. Well, this is probably something we should look at doing more efficiently, somehow. Let's leave this open.

**Comment by petrelharp** [comment]
OK, over at https://github.com/tskit-dev/pyslim/pull/299 we're making `convert_alleles` go fast. And, if we use nucleotide models in SLiM, then we don't need `generate_nucleotides`. (I'm sure the latter can go faster, but we don't yet need it to?) I'll do a pyslim release with the faster version once it's sorted.
