### ISSUE TITLE
Allele frequency conditioning with multiple `DrawMutation` events at the same locus

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1337]
Relates to #608.

If multiple `DrawMutation` events with the same single site id are supplied to the SLiM engine, then multiple mutations of the same type will be generated. If these mutations make it into the sampled individuals, they will ultimately end up as different alleles (integer codes) in the outputted tree sequence.

This creates a bit of a dilemma for `ConditionOnAlleleFrequency`. What exactly should be conditioned on? Some options are:

1. The simulation could abort if there's more than one `DrawMutation` event at the same site. This is *de facto* what happens currently -- if there's more than one extant mutation at a site when the AF condition is evaluated, then SLiM will exit with a rather ambiguous error message. So we'd just need to add a check for overlapping `DrawMutation` events in `slim_makescript` and exit with an informative error.
2. The allele frequency condition could apply to the sum of frequencies of derived alleles.
3. The allele frequency condition could apply independently to all derived alleles. This seems useful in some cases, like for conditioning on the survival of all derived alleles. However we'd need some additional checks to ensure that the condition is possible to satisfy.
4. Separate conditions could be applied to separate alleles. I think the only reasonable way to allow this would be to permit multiple mutation types at the same "single site" (in which case alleles could have separate fitness coefficients) -- but this would require more infrastructure, testing, etc.

My vote is for (1) as this will require very little work to implement, and should cover many use cases (?). Ultimately it'd be nice to extend this to (4).

**Comment by petrelharp** [comment]
I vote for (1) also!
