### ISSUE TITLE
require SLiM version 4.0++

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1343]
Over in https://github.com/MesserLab/SLiM/issues/347 is described a bug leading to memory leaks and possible crashes in the case where reloading from a .trees file while there are Remembered individuals. We would only hit this if there historical samples and a condition on allele frequency. So, this just means we'll want to require SLiM version 4.01 (or whatever the next release that fixes this is).

It could also affect older sims, but as the conditioning code wasn't released, and we're only supporting SLiM v4 moving forward, we needn't worry about it.

**Comment by petrelharp** [comment]
This needs to be changed in `requirements/` and at https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/slim_engine.py#L1552

**Comment by nspope** [comment]
There's also a hardcoded check here that could be updated:

https://github.com/popsim-consortium/stdpopsim/blob/3166eadd31097771c6b1dc4dd2ce8e0792f02220/stdpopsim/slim_engine.py#L1551-L1552

**Comment by nspope** [comment]
Fixed by #1567
