### ISSUE TITLE
Mention species inclusion criteria in development docs

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1347]
If there are going to be criteria for including species in the catalog (e.g. to avoid fragmented assemblies), these should be mentioned in the [Adding a new species](https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#adding-a-new-species) section of the documentation, similarly to the [What models are appropriate to add](https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#what-models-are-appropriate-to-add) blurb for demographic models.

**Comment by igronau** [comment]
This is now mentioned in the clean version in #1397. Once we merge in that PR, this issue can be closed.
