### ISSUE TITLE
deprecate `--length-multiplier` CLI option

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#1349]
`--length-multiplier` doesn't compose well with other options, and specifying a fixed length is an easier way to get short-running tests.

**Comment by grahamgower** [comment]
Also deprecate/remove the `length_multiplier` options to `Species.get_contig()` and `Contig.species_contig()`. No one should be using these outside our test suite.

**Comment by nspope** [comment]
Length multiplier via `-l` is used pretty heavily in the CLI portion of the tutorial, these examples should use `--left` and `--right` once #1348 is merged.
