### ISSUE TITLE
Add ploidy to `Adding new species` in developer docs

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1374]
With #1361, ploidy is an attribute of species and chromosome, but there's no indication of this in the developer docs wrt adding a new species.

**Comment by igronau** [comment]
I now mention this in the modified version of the docs (#1397). See the updated example for *A. thaliana*. I didn't explicitly mention that you need to mention ploidy for the _species object separately to the chromosome-level ploidy in the _genome object. Do you think we should mention this?

**Comment by nspope** [comment]
I think it's clear enough as is, thanks!

**Comment by igronau** [comment]
So I guess once I'm done with my edits to the docs and we merge that PR, this issue could be closed.

**Comment by nspope** [comment]
Closed by #1397
