### ISSUE TITLE
make list of tutorials

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#139]
Let's brainstorm a wish list of tutorials that should be written, and make issues for those: how about this -

1. a fixed-size generic model (like what we have but with more words), then outputting to (a) a tped file and (b) a vcf

2. samples of human chromosome 1 from one-pop model, and computing the SFS, compared to the standard expectation, with tskit

3. samples of human chromosome 1 from some demographic model with multiple populations and some recomb map (talking through looking at choices for those), computing the matrix of pairwise divergences between samples from the populations with tskit

4. samples from drosophila two-pop model, and doing PCA on the result with scikit-allel

Are there other features of stdpopsim or easy things to demonstrate doing with the output?

**Comment by gtsambos** [comment]
btw, @agladstein89 and I are thinking of getting on this soon -- so please let us know if there's more you'd like in time for this paper!

**Comment by gtsambos** [comment]
I think we also need a few more examples of tutorials from of the specific demographic models (rather than just the generic ones).

**Comment by jeromekelleher** [comment]
Yes, definitely. I just added the Generic model example because people needed to use them straight away for the analysis repo. As I said in another thread, the Generic models are much less important than the standard models from the Catalog.

**Comment by agladstein** [comment]
@jeromekelleher suggested tutorial "how to interpret the data".

**Comment by agladstein** [comment]
Should we add any more tutorials? Or is this good for now? There is currently an empty space under https://stdpopsim.readthedocs.io/en/latest/tutorial.html#running-a-prexisting-model

**Comment by jeromekelleher** [comment]
I think we can close this now. Any more tutorials we need can go into specific issues.
