### ISSUE TITLE
When using `left`/`right`, output coordinate system is relative to start of contig

### ISSUE THREAD

**Issue by nspope** [popsim-consortium/stdpopsim#1404]
The options `left`, `right` in `Species.get_contig` allow a portion of a chromosome to be simulated (in contrast to simulating an entire chromosome and "masking" everything outside of `[left, right]`). When adding DFEs/inclusion masks/sweeps/etc to the contig, the coordinate system used is that of the original chromosome.

However, the coordinate system of the output tree sequence will be relative to the start of the contig, not of the original chromosome. So for example, if I simulate chr22 from 30 Mb to 50 Mb then dump a VCF, the coordinates of variants won't reflect their positions on the original chromosome.

Instead, should the output tree sequence span the entire chromosome and have missing data outside of `[left, right]`?

**Comment by jeromekelleher** [comment]
> Instead, should the output tree sequence span the entire chromosome and have missing data outside of [left, right]?

Probably yes I think, it's the less bad option.

**Comment by nspope** [comment]
Should be able to do this by removing `trim=True` from [here](https://github.com/popsim-consortium/stdpopsim/blob/b1383cce4eac2a0fea92b660fdca88b8c4ad5928/stdpopsim/genomes.py#L507), and removing the coordinate "shifting" for DFEs and exclusion masks, I think.

**Comment by dschride** [comment]
We discussed this a bit in the hackathon at the meeting before prob gen and my argument was that for many uses people will be interested in generating simulated data that "look like" some region and then plugging that into some pipeline that would want coordinates starting with 1. (E.g. calculating summary stats on a bunch of sims before running ABC.)

So one option is to leave the current behavior as is, while warning the user that the rest of the chrom is not simulated, and maybe add in another flag for having the tree seq span the whole chrom and doing the missing data thing as proposed above.

**Comment by nspope** [comment]
If we're outputting the original coordinate system with "flanks" outside of the simulated window set to missing, then trimming to the window (thus resetting the coordinate system) is as simple as ``ts_new_coord = ts.trim()``. So, I'm not sure we'd need to provide an option for this in the API, we could just mention ``trim`` method in the docstring.

**Comment by hyanwong** [comment]
I have just encountered this problem and it confused me, because I wanted to add a reference sequence to the simulated genome. I agree with @nspope and @jeromekelleher that we should not "trim by default", and we should attempt to preserve the coordinate system of the simulated chromosome, in case the positions are used e.g. for annotations etc.
