### ISSUE TITLE
Missing dependency on scipy

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#1412]
We import scipy in a couple of places (e.g. [here](https://github.com/popsim-consortium/stdpopsim/blob/8def1f731183c111b1a6a970e0aa7da6cb5aafdc/stdpopsim/qc/HomSap.py#L1476)) but it's not in the list of requirements.

Scipy is a heavy dependency, but given we're already depending on pandas we're pulling in a lot of the data science stack anyway so maybe not worth worrying about. 

We'll need to push out a new version to fix this, an so we can get a conda package working.

**Comment by grahamgower** [comment]
It looks like scipy and pandas are only used in that one demographic model, so I'd vote to modify that model to remove this code. Pandas dataframes can be replaced with lists. Scipy is only used for the gamma pdf, and the std lib has the gamma function `math.gamma()`, so the pdf is a one liner.

As an aside, I'm a bit suspicous that this model and its qc model have indentical nested functions `extended_pulse()`.
