### ISSUE TITLE
load QC models only when the tests are run

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#1418]
Right now we load all QC models from `stdpopsim/__init__.py`, which means `import stdpopsim` loads all the QC models. This is (almost) unnecessary. Only the test suite makes meaningful use of the QC models---to confirm the QC model matches the main model. However, the CLI also looks at the `DemographicModel.qc_model` field to see if a model has been QCed and prints a warning if a user tries to simulate a model that hasn't been QCed. Right now, all our demographic models have been QCed (hooray!), so this warning doesn't apply.

Options:
1. Keep the status quo - loading all QC models at runtime.
2. Remove the warning about non-QCed models from the CLI.
3. Seprate the "this model has been QCed" logic from the QC model itself. This could be done by changing the register_qc_model() method to accept a function that returns the qc model, rather than the model object itself (ie. a very small code change to remove `()` in lots of places). The test suite would call that function. The CLI logic just checks that the qc_model attribute is not None, so this wouldn't need to be changed at all.

Thoughts?

**Comment by jeromekelleher** [comment]
Option 3 sounds great to me!

**Comment by nspope** [comment]
Talking with @petrelharp, it seems like this is a moot point now (see #1419), feel free to reopen if we're wrong
