### ISSUE TITLE
Installation docs

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#147]
Add docs on installation.

sub-issue of #137

**Comment by agladstein** [comment]
Should `pip install stdpopsim` work yet? because it doesn't for me.

**Comment by jeromekelleher** [comment]
No, we haven't released it yet. We should soon though!

**Comment by agladstein** [comment]
I was just going through @ndukler's PR https://github.com/popgensims/stdpopsim/pull/165 and gonna try out his tutorial. And the CLI wasn't installed with the `python3 -m pip install -r requirements/development.txt`.

Will `pip install stdpopsim` also install the CLI? If not, we will also need to add instructions for installing the CLI.

**Comment by jeromekelleher** [comment]
Yes, installing the stdpopsim package will install the CLI, so that it's available as ``python3 -m stdpopsim`` and also ``stdpopsim`` (if your paths are setup correctly).

**Comment by jeromekelleher** [comment]
Running `` python3 -m pip install -r requirements/development.txt`` just installs the required packages for developers, it's not for end users.

**Comment by agladstein** [comment]
Okay good. Just making sure. 
This issue is essential before publication! 
(you can put it under the initial release milestone)

> Running ` python3 -m pip install -r requirements/development.txt` just installs the required packages for developers, it's not for end users.

I know. I was just providing my environment.

**Comment by andrewkern** [comment]
just checking in on this issue as we get ready to ship v0.1.0 ... @agladstein how are you feeling about these docs?

**Comment by jeromekelleher** [comment]
I'll do it -- it's a copy-paste from other docs.

**Comment by agladstein** [comment]
Once v0.1.0 is released on pip (and conda?), just update the installation docs!
