### ISSUE TITLE
Inconsistent factors of 2 in human gamma DFE models?

### ISSUE THREAD

**Issue by RyanGutenkunst** [popsim-consortium/stdpopsim#1477]
**Short description of the problem:**
For Humans, the Gamma_K17 and Gamma_H17 are inconsistent in their factor of 2 adjustments.

**How to reproduce the problem:**
An obnoxious factor of two to worry about is that SLiM defines 1+s to be the fitness of homozygote, whereas dadi (and some other tools) define 1+2s to the the fitness of the homozygote. So a selection coefficient of 0.01 in dadi is equivalent to a selection coefficient of 0.02 in SLiM.

Thus to convert a DFE from dadi units to SLiM units, the scale/mean of s must be multiplied by 2. This is done in Gamma_K17 https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/HomSap/dfes.py#L36 but not in Gamma_H17.

The papers do not make it crystal clear (at least to me) whether they define s in the SLiM way or the dadi way, but since they both used dadi for inference, I assume they're using the dadi way.

**Suggested fixes:**
@klohmueller, can you weigh in?
I think Gamma_H17 needs another factor of two in mean s. But currently K17 has a mean of roughly 0.013 versus H17 currently at 0.014, so another factor of two would make them more different.
If I'm wrong, maybe some more comments would help explain the inconsistency here.

**Comment by klohmueller** [comment]
Both Kim 2017 and Huber 2017 are indeed parameterized like Dadi (where 1+2s is the fitness of the homozygote).

These 2 DFEs are in fact different. They were inferred from different populations EA vs. YRI. But, perhaps more importantly, the mutation rates assumed in the inference are different. Kim used 1.5e-8 and the Huber DFE in Gamma_H17 uses 2.5e-8. We also looked at a lower mutation rate of 1.5e-8 in Huber et al. and found E[s] to be 0.00839. This is closer to 0.013/2.

**Comment by RyanGutenkunst** [comment]
Thanks @klohmueller . Should be fixed in https://github.com/popsim-consortium/stdpopsim/pull/1478

**Comment by petrelharp** [comment]
Damn, good catch.

**Comment by petrelharp** [comment]
This was fixed in #1478.
