### ISSUE TITLE
add discretized h-s relationship DFE

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1488]
We have discussed using the "uniform" DFE (from #1481) to add a DFE with a h-s relationship; Kirk says on Slack that 
> here's the reference for the discritized h-s relationship: https://www.biorxiv.org/content/10.1101/2022.08.12.503792v1.supplementary-material
and that
> The "best available" (also sometimes called "this paper") model is the one that I would recommend using....it's implemented in this SLiM script: https://github.com/ckyriazis/simulations_review/blob/main/simulation_scripts/SFS_scripts/SFS_newDFE_040422.slim

That's for humans; there's also an h-s relationship estimated in arabidopsis, but from the meeting:
> Linh: would this DFE be for human and Arabidopsis?
> Kirk: probably just human? Chris fit h/s distribution from Arabidopsis and tired to fit to human but didn't fit well. Too many weak recessive deleterious mutations present in the data relative to the model. Models that fit better have more additive, weakly del mutations. The model that is posted to slack is fit specifically to humans, checked on 1kg SFS- reasonable fit, also reasonable fit to estimated human inbreed load.

**Comment by ckyriazis** [comment]
I can add more about the somewhat hacky way of implementing an h-s relationship here - my experience is that implementing an h-s relationship with the mutationEffect() callbacks in SLiM (e.g., see lines 67-75 [here](https://github.com/ckyriazis/simulations_review/blob/main/simulation_scripts/SFS_scripts/SFS_kardos_040422.slim)) is super slow, so Ben helped me think of a way to speed this up by creating different mutation types and discretizing the gamma distribution as seen in the script above. 

There may still be a better way of doing this but this is the solution I've converged on for now! Happy to discuss further if anything isnt clear.

**Comment by petrelharp** [comment]
The approach makes perfect sense. If I run into issues I'll ping you. Thanks!

**Comment by petrelharp** [comment]
Note that a problem for (1) is: how would we QC it?
