### ISSUE TITLE
bug in adding mutations to the recapitated portion of the tree sequence

### ISSUE THREAD

**Issue by mufernando** [popsim-consortium/stdpopsim#1496]
We will have a similar issue that `pyslim` had to deal with because of the time in the metadata from SLiM tree sequences.

https://github.com/popsim-consortium/stdpopsim/blob/5f319a5bbe4f0ffa3be8ce235307f662008eab7e/stdpopsim/slim_engine.py#L1813

See https://github.com/tskit-dev/pyslim/pull/308#issuecomment-1592070514 and https://github.com/tskit-dev/pyslim/pull/311 for the fix

**Comment by nspope** [comment]
Gosh, thanks for noticing-- this only affects the mutations and not the genealogies, right?

**Comment by mufernando** [comment]
I don't think it does and @petrelharp agrees. He found this bug btw!

**Comment by petrelharp** [comment]
And hence very minor - it just results in no mutations for 1 or 2 generations, I think.

**Comment by andrewkern** [comment]
@mufernando or @petrelharp will one of you submit a patch?

**Comment by petrelharp** [comment]
As discussed in https://github.com/tskit-dev/pyslim/pull/308#issuecomment-1592070514 there is no bug if we set up in `early` and write out in `late`, which is what we in fact do :tada:.
