### ISSUE TITLE
remove python 3.7 from CI?

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1499]
So, python 3.7 is in ["end-of-life"](https://devguide.python.org/versions/), and in gettin CI to work over in #1498 I'm running into the following issue: scikit-allel 1.3.5 does not install via pip with python 3.8, and scikit-allel 1.3.6 (the current one) doesn't with python 3.7. We could do conditional package versions based on python version but I'm voting to just remove 3.7.

Any objections?

**Comment by nspope** [comment]
SGTM!

**Comment by petrelharp** [comment]
This has been done; closing.
