### ISSUE TITLE
link to model code in catalog docs

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#150]
Would it be possible to link to the model code in the catalog docs. That someone can easily find the simulation code and look at it themselves if they want. Anyone can find it with some digging on GitHub, but would make it easier, if it was linked right there in the docs.

sub-issue of #137

**Comment by jeromekelleher** [comment]
Good idea --- it would be nice to do, but it involves understanding the guts of docutils and sphinx a bit better than I do at the moment. See also #120

**Comment by agladstein** [comment]
I can do some digging and see what I figure out on linking.

**Comment by jeromekelleher** [comment]
Having delved around in the guts of sphinx, I think this would be tricky. Perhaps we can do some sort of link up with (sphinx-viewcode)[https://www.sphinx-doc.org/en/master/usage/extensions/viewcode.html#module-sphinx.ext.viewcode].

**Comment by jeromekelleher** [comment]
I don't think we can do this in the current catalog structure, so going to close.
