### ISSUE TITLE
add vaquita

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#1508]
As discussed today, vaquita has a good assembly and various demographic models. It even has a DFE inferred, but @klohmueller says that it doesn't fit significantly better than the human-inferred one added in #1505.

Here's the info:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9881057/
and see Table S2 for demographic parameter estimates.

**Comment by petrelharp** [comment]
@igronau has volunteered to do this! <3 <3

**Comment by igronau** [comment]
I'm pretty much done implementing the species. I'm just missing a recombination rate estimate. Couldn't find anything reported for this species or anything closely related. In analyses, studies appear to use 'reasonable values for mammals', or even the human average recombination rate. Will try to sort this out in the next stdpopsim meeting

**Comment by petrelharp** [comment]
@igronau discussed with @ckyriazis; they decided that the recombination rate is okay.

**Comment by igronau** [comment]
The species has been added and is now QC'd. This issue can be closed @petrelharp.

**Comment by igronau** [comment]
I now published a PR with the 2-epoch demographic model. See #1526. @petrelharp - Can you merge?

**Comment by ckyriazis** [comment]
Hi Ilan - sorry for the slow reply. I wasnt actually aware I'd been tasked with the DFE implementation and I'm not sure I'll be able to get to it any time soon. I'm currently trying to finish up some projects before ending my time at UCLA at the end of this month, and will be out all of December before starting a new position in January. Apologies for any miscommunication.

**Comment by petrelharp** [comment]
Wow, congratulations, Chris!

I think maybe your name was mentioned as a possibility; we'll turn up someone else.

**Comment by igronau** [comment]
Congrats Chris @ckyriazis and good luck with wrapping up in UCLA!

**Comment by petrelharp** [comment]
Closed in #1560 (and other PRs).
