### ISSUE TITLE
Catalog docs explain population numbering

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#151]
I'm not sure that it is apparent what the population numbering means in the Catalog docs.

Populations
0. 1000 Genomes YRI (Yorubans)
1. 1000 Genomes CEU (Utah Residents (CEPH) with Northern and Western European Ancestry
2. 1000 Genomes CHB (Han Chinese in Beijing, China)

How will this (0, 1, 2) relate to the output the user gets?

sub-issue of #137

**Comment by gtsambos** [comment]
Yes, I agree this will be quite confusing for people who have never used msprime/SLiM before and who don't realise that populations have numbered IDs.

What operations within stdpopsim require the user to know what these population numbers mean? If they are doing any raw analyses of the outputted tree sequence, they'll defs need this. Do any of the built-in analyses require this also?

As an aside -- I think it'd be useful to give users an option of simulating samples under only a subset of the populations in a given model.

**Comment by jeromekelleher** [comment]
> What operations within stdpopsim require the user to know what these population numbers mean? If they are doing any raw analyses of the outputted tree sequence, they'll defs need this. Do any of the built-in analyses require this also?

This is all for enabling the user to analyse the resulting tree sequence. There is also some metadata in there to help. This is probably something we want a tutorial on: how to interpret the data.

The ordering of the populations also matters when specifying the samples. Try out the CLI for, say, "ooa_3" to see how this works.

> As an aside -- I think it'd be useful to give users an option of simulating samples under only a subset of the populations in a given model.

This is built in to the CLI and Python API (see last point)

**Comment by jeromekelleher** [comment]
Has this been covered now @agladstein, @gtsambos?

**Comment by jeromekelleher** [comment]
This is pretty well covered now, I think. We can reopen if someone disagrees.
