### ISSUE TITLE
Error on import: ModuleNotFoundError: No module named 'scipy

### ISSUE THREAD

**Issue by gregorgorjanc** [popsim-consortium/stdpopsim#1515]
**Short description of the problem:**
With a fresh install on OSX (`stdpopsim-0.2.0-py3-none-any.whl` - installing via pip) I get this error

```
(base) ggorjanc@mvm-eb-m19002 ~ % python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import stdpopsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/stdpopsim/__init__.py", line 28, in <module>
    from .catalog import *  # NOQA
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/stdpopsim/catalog/HomSap/__init__.py", line 6, in <module>
    from . import demographic_models  # noqa: F401
  File "/usr/local/Caskroom/mambaforge/base/lib/python3.10/site-packages/stdpopsim/catalog/HomSap/demographic_models.py", line 3, in <module>
    from scipy import stats
ModuleNotFoundError: No module named 'scipy'
```

**Suggested fixes:**
Should scipy be added to requirement/config?

**Comment by gregorgorjanc** [comment]
Looking at https://github.com/popsim-consortium/stdpopsim/blob/d89010fe3489f1ee6f44d02871a5ef2ae33815c0/requirements/CI/requirements.txt#L18 I see `scipy` is mentioned!?

**Comment by petrelharp** [comment]
Hm - I see that the most recent release (0.2.0) did indeed use `scipy` but did not have `scipy` under `install_requires` in `setup.cfg`. That was an error, looks like - and I don't know why that didn't get caught by something. Seems like we need an additional installation check in CI somewhere.

However, since then we've removed `scipy`, so this won't be a problem for the next release?

**Comment by petrelharp** [comment]
So - I think we can close *this*, but this can be replaced by #1518?

**Comment by gregorgorjanc** [comment]
Thanks @petrelharp !
