### ISSUE TITLE
QC for DomesticusEurope_1F22, MusculusKorea_1F22, and CastaneusIndia_1F22 (MusMus)

### ISSUE THREAD

**Issue by igronau** [popsim-consortium/stdpopsim#1528]
**PR for new model:** [#1485](https://github.com/popsim-consortium/stdpopsim/pull/1485)
**Original paper:** [Fujiwara et al. 2022](https://academic.oup.com/gbe/article/14/5/evac068/6582302)
**Parameter values:** Fig 3 - sent by authors to @peterdfields 
**Population indices:** three separate 1-pop models

**Potential issues that might lead to differences between the model implementations:**
NA

**QC'er requests:** I manually inspected model already. Now, I just have to write the QC code.

**Comment by igronau** [comment]
I implemented the QC tests for the three demographic models. See PR #1531 I ran the tests locally and they pass. It'll be good if someone can have another look before this is merged  (@petrelharp :-)).

**Comment by nspope** [comment]
Closing as the QC is merged
