### ISSUE TITLE
QC for DFE model Gamma_R22 for Vaquita (PhoSin)

### ISSUE THREAD

**Issue by igronau** [popsim-consortium/stdpopsim#1548]
**PR for new model:** [#1547](https://github.com/popsim-consortium/stdpopsim/pull/1547)
**Original paper:** [Robinson et al. (2022)](https://www.science.org/doi/10.1126/science.abm1742)
**Parameter values:** taken from pages 9-13 of [supplement of Robinson et al. (2022)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9881057/bin/NIHMS1864134-supplement-Supplementary_material.pdf)
**Population indices:** {description of population indices}. See comments below

**Potential issues that might lead to differences between the model implementations:**
The gamma shape was taken directly from the reported estimate.
The gamma mean was taken from the value reported in simulations. This was derived from the inferred shape and scale + the estimated Na, but since the estimated Na is not reported, I couldn't confirm the reported mean.
The h-s relationship is based on what was used in simulations (see top of page 13 in supp).

**QC'er requests:** @ckyriazis / Kirk Lohmueller / @petrelharp

**Comment by ckyriazis** [comment]
Hi Ilan - sorry for being slow to get to this. This looks good to me with one correction - the gamma mean should be -0.0257 rather than -0.00971. As noted near the bottom of page 12 in the supplement, -0.0257 is the value when assuming the estimated mutation rate of 5.8-9 (the default rate used throughout the paper) whereas -0.00971 is used under sensitivity analysis when assuming an alternative mutation rate of 2.2e-9.

Everything else looks correct, including the h-s relationship parameters and the ratio of synonymous to nonsynonymous mutations. Let me know if there are any other questions!

**Comment by petrelharp** [comment]
Thanks, Chris. Hm, so this was a code review more than a QC. (Recall that a
QC reimplements the models blind.) Any chance you could get the QC code in,
@ckyriazis?

**Comment by ckyriazis** [comment]
Hi Peter - sorry for the misunderstanding...I looked at the docs for info on how to [QC a DFE model](https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#reviewing-a-dfe-model) and it seemed to suggest that the current process is a simple code review. I might have time next week to put the QC code in, but given that I've already looked at Ilan's code, it wouldnt really be a blind implementation. What do u suggest?

**Comment by petrelharp** [comment]
Whoops, missed this! Looks like the docs are out of date; there is a re-implementation QC procedure, see https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/qc/HomSap.py#L1696 for an example.

**Comment by ckyriazis** [comment]
Hi all - sorry again for the delay in looking at this. I've gone ahead and implemented the QC of the vaquita DFE in the same manner as the Huber DFE above, but I am a bit unsure of what sort of tests to include in `test_PhoSin.py`. For instance, I dont see any tests of the Huber DFE in `test_HomSap.py`. What would you suggest here?

**Comment by petrelharp** [comment]
Ah, great! Our automated tests *should* test all the DFEs, so I think you don't need to write any specific tests - just the QC implementation. How about put what you have in a PR and I'll have a look, and finish off whatever needs to be done?

**Comment by ckyriazis** [comment]
Ok great! [Here](https://github.com/popsim-consortium/stdpopsim/pull/1560) is the PR. Note again that the gamma parameters differ slightly from what Ilan coded up, so I am surprised that it doesnt seem to be failing any tests.

**Comment by petrelharp** [comment]
Closed in #1560.

**Comment by igronau** [comment]
> Hi Ilan - sorry for being slow to get to this. This looks good to me with one correction - the gamma mean should be -0.0257 rather than -0.00971. As noted near the bottom of page 12 in the supplement, -0.0257 is the value when assuming the estimated mutation rate of 5.8-9 (the default rate used throughout the paper) whereas -0.00971 is used under sensitivity analysis when assuming an alternative mutation rate of 2.2e-9.
> 
> Everything else looks correct, including the h-s relationship parameters and the ratio of synonymous to nonsynonymous mutations. Let me know if there are any other questions!

I agree with this correction. The Gamma mean should be -0.0257 and the shape should be 0.1314
