### ISSUE TITLE
Arabidopsis model catalog docs

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#155]
- Arabidopsis thaliana needs a model name in the catalog docs. 
- model needs more description.
- params need to be listed.

sub-issue of #137

**Comment by andrewkern** [comment]
i think this will be closed by https://github.com/popgensims/stdpopsim/pull/225

**Comment by jeromekelleher** [comment]
I think the docs are still light here. If you look though the [catalog](https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_aratha) there's bunch of TODOs. We need more than a sentence to describe models, there should be enough here to give someone who doesn't know the paper some idea of what's going on.

**Comment by andrewkern** [comment]
I'm afraid there is little detail as to how the `SouthMiddleAtlas_1D17` model was arrived at. The person we need here is @arundurvasula. 

I can add a bit more detail about the Huber Models to the docs

**Comment by arundurvasula** [comment]
Hi! Happy to help here! I expanded the description a bit: 

> This model comes from MSMC using two randomly sampled homozygous individuals (Khe32 and Ifr4) from the South Middle Atlas region from the Middle Atlas Mountains in Morocco. The model is estimated with 32 time periods. Because estimates from the recent and ancient past are less accurate, we set the population size in the first 7 time periods equal to the size at the 8th time period and the size during last 2 time periods equal to the size in the 30th time period.


Is there any other info anyone can think of to add?

**Comment by jeromekelleher** [comment]
Can you review what's in [the catalog](https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_AraTha) for Arabadopsis, and open a PR to update please @arundurvasula ? We want the same level of detail as we have for the human models, ideally.

**Comment by arundurvasula** [comment]
> Can you review what's in [the catalog](https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_AraTha) for Arabadopsis, and open a PR to update please @arundurvasula ? We want the same level of detail as we have for the human models, ideally.

Hi Jerome, getting this done now. Do I need to rebuild the docs before sending in a pull request? I edited the documentation in the file `stdpopsim/catalog/arabidopsis_thaliana.py`.

**Comment by andrewkern** [comment]
hey @arundurvasula- yes that should work, as long as it's sympatico with https://github.com/popsim-consortium/stdpopsim/blob/master/docs/catalog.rst

**Comment by jeromekelleher** [comment]
> Hi Jerome, getting this done now. Do I need to rebuild the docs before sending in a pull request? I edited the documentation in the file stdpopsim/catalog/arabidopsis_thaliana.py.

It's good to build the docs locally so you can see how it renders @arundurvasula. There's a little documentation on doing this [here](https://stdpopsim.readthedocs.io/en/latest/development.html#documentation). If it's not working for you, feel free to open a PR and we can give guidance there.

**Comment by jeromekelleher** [comment]
Bumping this thread: has the issue been resolved?

**Comment by agladstein** [comment]
Looks like this was resolved in 
https://github.com/popsim-consortium/stdpopsim/pull/389

**Comment by jeromekelleher** [comment]
Great, thanks @agladstein.
