### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by jiseonmin** [popsim-consortium/stdpopsim#1562]
Hi, I was using MallardBlackDuck_2L19 model, and it looks like the migration matrix is symmetric in stdpopsim (version 0.2.0), but the documentation says the migration is 10^-6 times 0.84 (Black-Mallard) and 1.10 (Malard-Black). (https://popsim-consortium.github.io/stdpopsim-docs/stable/catalog.html#sec_catalog_AnaPla_models)

**Comment by andrewkern** [comment]
huh this isn't good. the model param csv file doesn't match the code...

**Comment by jiseonmin** [comment]
I see the source paper (https://onlinelibrary.wiley.com/doi/10.1111/mec.15343) and the code (https://github.com/popsim-consortium/stdpopsim/blob/main/stdpopsim/catalog/AnaPla/demographic_models.py) both have a symmetric migration rate (2.82 migrants per generation). 

Checking the commit history, I see only one commit by @petrelharp 3 years ago (https://github.com/popsim-consortium/stdpopsim/commit/6b3d7bbe75f2e15685d2cdf84725f89b1fdea187)... Do you know what happened here?

**Comment by petrelharp** [comment]
Well, here's what happened: #883, #920, #921, #1021. But, my guess the reason for this discrepancy is that (a) first I had thought migration rates were forwards-time, and so needed to be scaled by modern pop sizes (and thus asymmetric); but then (b) figured out they weren't, and forgot to update the parameter table. So, I think we just need to fix the parameter table. Thanks!
