### ISSUE TITLE
complete all citations

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#207]
Need to make sure everything that requires a citation has a citation.
For example, 

```
(stdpopsim_env) Ariellas-New-MacBook-Pro:docs agladsteinNew$ stdpopsim homsap -c chr22 -o foo.ts 2
```
Gives:
```
If you use this simulation in published work, please cite the following papers:
******************
Simulation engine:
******************
msprime:
        Kelleher et al. 2016
        https://doi.org/10.1371/journal.pcbi.1004842
******************
Genetic map:
******************
        TODO
```

Genetic map has a TODO.

sub-issue of https://github.com/popgensims/stdpopsim/issues/137

**Comment by gtsambos** [comment]
yup, agreed. Also see #192 -- there are default values for generation sizes, population sizes etc that look sort of arbitrary and need some csupporting citations.

**Comment by agladstein** [comment]
Yes, we did discuss sorting out those citations on the call.
Anyone want to claim it?

**Comment by grahamgower** [comment]
I'll address the TODO in `write_citations()` observed above. I already have a unit test for this in pr #218.

**Comment by grahamgower** [comment]
See pr #219.

**Comment by jeromekelleher** [comment]
Is the presence of Citations for things that should be cited checked in CI? I think that'd be a good way to close off this issue.

**Comment by grahamgower** [comment]
I think write_citations() is doing everything it needs to now, and species citations are copied across into models where appropriate. But that doesn't mean the citations are actually provided. Probably there should there be CI checks like this:
```
for species in all_species():
    sefl.assertGreater(species.generation_time_citations, 0)
    self.assertGreater(species.population_size_citations, 0)
```
None of the species will currently pass this check.

**Comment by jeromekelleher** [comment]
Good idea, that's exactly what we want I think. We probably need to start hassling people for these citations!

**Comment by jeromekelleher** [comment]
I'll open a bunch of issues to track the various species. Once these are closed, then perhaps we can add this check to CI and close off the issue.

**Comment by agladstein** [comment]
Anyone know if this can be closed?

**Comment by grahamgower** [comment]
I think there are a few outstanding `Genome.recombination_rate_citations` and `Genome.mutation_rate_citations` entries that need to be filled.

**Comment by andrewkern** [comment]
it would be great to get of list of these together so that people can knock them out easily

**Comment by grahamgower** [comment]
`mutation_rate_citations` needed for arabidopsis and e_coli. 
`recombination_rate_citations` needed for all species.

A species with both entries should look something like this:
```
_some_citation_A = stdpopsim.Citation( ... )
_some_citation_B = stdpopsim.Citation( ... )

_genome = stdpopsim.Genome(
    chromosomes=_chromosomes,
    mutation_rate_citations=[
        _some_citation_A.because(stdpopsim.CiteReason.MUT_RATE),
        ],
    recombination_rate_citations=[
        _some_citation_B.because(stdpopsim.CiteReason.REC_RATE)
        ])
```

I think most of the sources should be easily found. Either its written as a comment in the catalog file (e.g. arabidopsis), or the recombination rate comes from one of the genetic maps (e.g. humans).

**Comment by grahamgower** [comment]
And then its just a matter of confirming that you see a "recombination rate" and/or "mutation rate" tag listed for the citation when you run a simulation that uses it.

**Comment by jeromekelleher** [comment]
I think we can close this now. We can open issues for specific things that are missing as we see them.
