### ISSUE TITLE
tutorial showing SFS analysis

### ISSUE THREAD

**Issue by gtsambos** [popsim-consortium/stdpopsim#254]
the tutorial wishlist in #139 lists this:

> 2. samples of human chromosome 1 from one-pop model, and computing the SFS, compared to the standard expectation, with tskit

I'll tackle this next. Btw @petrelharp , by the 'standard expectation' did you just mean the expectation under neutrality?

cc @agladstein

**Comment by petrelharp** [comment]
> by the 'standard expectation' did you just mean the expectation under neutrality?

Yes - compared to the coalescent calculation. (the Ewens sampling formula)
