### ISSUE TITLE
[slim-engine-dev] Output slim script to stdout, instead of specifying another file.

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#261]
The --slim-script-file accepts a FILE parameter at the moment. This should be removed, in favour of printing the SLiM script to stdout.

**Comment by jeromekelleher** [comment]
We should think about how this interacts with the ``--dry-run`` option discussed in #199. It's not a big issue, just something to bear in mind.

**Comment by grahamgower** [comment]
Closed by #400.
