### ISSUE TITLE
[slim-engine-dev] add population metadata to tree sequences

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#263]
I don't think SLiM provides any script-based control over the metadata in the tree sequence output file. But the population metadata can be added via pyslim. Probably this will create unwanted provenance duplications, which could be cleaned up.

Maybe there any other important tree sequence metadata differences between msprime and SLiM?

**Comment by jeromekelleher** [comment]
@petrelharp, any thoughts here?

**Comment by petrelharp** [comment]
Well, SLiM *uses* the metadata. The best place to see exactly what is set, currently, is in the SLiM manual (section 25.4, titled "SLiM additions to the .trees file format"; see example below), but it's on the list to [write it out in the pyslim docs](https://github.com/tskit-dev/pyslim/issues/50).  Metadata fields for mutations, nodes, individuals, and populations are all used to record structured binary data, so there is not currently support for adding additional information, unfortunately. It does seem like an oversight to not allow space for additional things, like labels. What exactly would we like to do?

![Screenshot from 2019-12-18 20-49-36](https://user-images.githubusercontent.com/1046249/71145885-f7f5fc80-21d7-11ea-861e-26c13cdb03d9.png)

**Comment by grahamgower** [comment]
Thanks @petrelharp, I was mostly thinking about the human readable population labels. But I didn't know if there was anything else that should be done to improve consistency between the msprime and SLiM tree sequences.

**Comment by petrelharp** [comment]
Human-readable labels would be great. Adding those would require an addition to slim, though, and some work keeping the file format backwards compatible. This seems like a minor annoyance, but something to keep in mind in the future. I can't think of anything else here; should we close this?

**Comment by grahamgower** [comment]
Are you suggesting this can't just be added with tskit or pyslim?

**Comment by petrelharp** [comment]
> Are you suggesting this can't just be added with tskit or pyslim?

Is "this" human-readable labels for populations? If so then - yes, you *can* modify the metadata... *but* if you do, the tree sequence won't bee a valid "SLiM tree sequence" any more (which you can e.g. load back into SLiM). And, I don't think we want to do that.

**Comment by grahamgower** [comment]
Well that's unfortunate. As population labels are not likely to be resolved as part of stdpopsim, I'll close this issue.
