### ISSUE TITLE
homsap generation_time/population_size values and citations

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#289]
We need citations for the generation time and population size in humans. These are defined [here](https://github.com/popgensims/stdpopsim/blob/master/stdpopsim/catalog/homo_sapiens.py#L71)

Can someone who knows about these things propose the correct values and citations for these please?

**Comment by jeromekelleher** [comment]
Ping @andrewkern --- you mentioned something about 1998 in #192?

**Comment by jeromekelleher** [comment]
See also discuss in #96, some papers linked in there.

**Comment by jeromekelleher** [comment]
@apragsdale, what are your thoughts here?

**Comment by apragsdale** [comment]
I usually use 29 or 30 years for the human generation time (https://doi.org/10.1086/302770). I'm not sure where exactly the 25 or 27 numbers come from.

I like the idea of using some old estimate of Ne=10^4 from the 90s (Takahata 93 or Hammer 95?). Not sure what the usual citation for those old number.

We probably also need to pick and cite a mutation rate. It seems like mutation rate estimates are converging to around 1.25-1.3e-8 (https://doi.org/10.1016/j.ajhg.2019.09.012), (though I still get suspicious that 1.25e-8 is a bit too low).

**Comment by andrewkern** [comment]
I agree- I like the old 10^4 number for Ne, and I think Takahata 1993 is a fine reference.

**Comment by jeromekelleher** [comment]
SGTM @apragsdale. Anyone like to follow up these with a PR?

**Comment by apragsdale** [comment]
Sounds good. Yeah I can handle the PR for it. I can push something in the next day or two.

**Comment by jeromekelleher** [comment]
Great, thanks. All yours.
