### ISSUE TITLE
pongo generation_time/population_size values and citations

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#292]
We need citations for the pongo species [attributes](https://github.com/popgensims/stdpopsim/blob/master/stdpopsim/catalog/pongo.py#L67)

**Comment by apragsdale** [comment]
Update - the genetic map was not available from the authors for this species, but the first author did send me the average recombination rates they estimated over each chromosome. I'll update `_chromosome_data` with them, and also include citations for the other attributes while I'm at it.

**Comment by apragsdale** [comment]
Update - I pushed a PR to include generation time and pop size citation schemes.

As far as recombination maps: From the author of a recent orangutan study (doi:10.1016/j.cub.2017.09.047), I was sent a link to recombination maps that they inferred using LDhat for two orangutan species. However, these aren't maps that are in a public repository as far as I can tell (even though they didn't mind sharing when I asked). Should we even include one or both of these genetic maps, if they aren't easily found in a public repo?

**Comment by jeromekelleher** [comment]
Thanks @apragsdale --- can you open a separate issue to track the genetic map problem please?
