### ISSUE TITLE
Automated model testing and QC status

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#305]
We should make it simpler for users to add new models, that automatically get put through basic tests.

Probably, each Model object should have a ``qc_complete`` attribute that defaults to False. If  ``qc_complete`` is True, the tests will ask the ``qc`` module for a model with the same ``species/id`` key, and check if it's identical (as we do now). Thus, all the model implementer needs to do is write a function that returns the model and add it to the species.

Should be done after #122, #303 (if it's done), and possibly as part of #304. Not necessary for 0.1.0

**Comment by agladstein** [comment]
Any idea on what the timeframe of this is? I was confused about the model testing - not much is currently written in the docs about it (from https://github.com/popsim-consortium/stdpopsim/pull/482)

I'm just wondering if I should elaborate on what the current process is for https://github.com/popsim-consortium/stdpopsim/issues/495, or if it makes more sense to wait for this issue to be sorted out.

**Comment by grahamgower** [comment]
I don't think it will be too much work, so I'll try to get a PR submitted for this issue by the end of the week.
