### ISSUE TITLE
Define requirements for Population IDs in DemographicModels and enforce

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#332]
Presumably should be
- A valid identifier in Python
- Be descriptive
- Be unique within model.

Should it be CamelCase also for consistency with Species, DemographicModel, etc?

**Comment by andrewkern** [comment]
we will also need to add this to the naming convention section in the docs of course.

**Comment by agladstein** [comment]
Looks like that is included in the docs now.
https://stdpopsim.readthedocs.io/en/latest/development.html#naming-conventions
