### ISSUE TITLE
Update documentation with new IDs

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#336]
The tutorial and catalog section contain examples that are now out of date.

**Comment by jeromekelleher** [comment]
Need to wait on the outcome of #337 as it updates genetic maps.

**Comment by gtsambos** [comment]
Yes, I spotted some things that need to be changed when I was writing my new tute -- ping me when #337 is done and I'll do the rest.

**Comment by jeromekelleher** [comment]
Thanks @gtsambos, but I'll take this. Basically ready to release now.

**Comment by gtsambos** [comment]
Thanks @jeromekelleher -- I think you might forgotten a few small changes (mostly to do with the fact that ``--models`` is now ``--demographic-models`` in the CLI). Have made a pull request (#350) to fix this up.
