### ISSUE TITLE
Pongo recombination map

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/stdpopsim#342]
As of #338, pongo is more or less up and running. It is only missing a recombination map. In looking for a published map, I contacted the first author of a study that inferred maps using LDhat for both P. pygmaeus and P. abelii (doi: 10.1016/j.cub.2017.09.047), and he sent me a link to download them.

So we could include them if we want. Is there an issue with us making these maps publicly available, when I had to ask the authors if they were available since they weren't included in the supp material or an easy-to-find repo?

**Comment by andrewkern** [comment]
Would you mind asking the authors what they think? I'm actually just working on the changes to push the PonPyg documentation live

**Comment by apragsdale** [comment]
Ok, I'll do that. It would be very nice to include them.

**Comment by andrewkern** [comment]
and I'm going to push ahead with the documentation. should be ready for a PR in a minute and maybe you could review it for me?

**Comment by apragsdale** [comment]
Picking this back up -- I'd like to get the Pongo species(es) sorted out (and finally resolve PR #363), including getting the two recombination maps cached in our map repository.

Do we now have an independent location to store recombination maps (did this get resolved in #335), and is there information about what format these need to be in? Even if the storage isn't sorted out yet, I can reformat the Pongo maps into whatever we need for them.

**Comment by grahamgower** [comment]
I don't know about the repository, but the file format is described here: https://msprime.readthedocs.io/en/stable/api.html#msprime.RecombinationMap.read_hapmap

**Comment by apragsdale** [comment]
Maps now included from PR #363
