### ISSUE TITLE
Field lists don't look as good on RTD

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#346]
Field lists like the species properties are rendered differently locally to how they look on RTD. Specifically, the fields are output one per line with the local RTD theme, which is much better for what we want.

Can we force the RTD theme to look the same somehow?

**Comment by gtsambos** [comment]
Mine looks the same? (left side is the RTD version, right side is my local version)
Maybe it's something to do with the local versions of sphinx packages installed on your machine?

![Screen Shot 2019-12-19 at 11 15 10 am](https://user-images.githubusercontent.com/17755074/71134029-e13fbc00-2250-11ea-879a-0c08e59bac2e.png)

**Comment by gtsambos** [comment]
![Screen Shot 2019-12-19 at 11 19 21 am](https://user-images.githubusercontent.com/17755074/71134206-6fb43d80-2251-11ea-9f0a-0beab991635c.png)

**Comment by jeromekelleher** [comment]
Ah, thanks @gtsambos. Looks like I have an older version of sphinx-rtd-theme on my machine. Hmmm.

**Comment by agladstein** [comment]
Looks fine to me on RTD. @jeromekelleher you can probably close this.

**Comment by andrewkern** [comment]
I'm gonna close this. Works on a whole bunch of systems.
