### ISSUE TITLE
Conda package/installation instructions

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#348]
A conda package is in development: https://github.com/conda-forge/staged-recipes/pull/10464

This should get merged and turned into a fully-fledged package soon (but I'm not sure when; the conda-forge folks are **super** busy, and we shouldn't hassle them).

Once the conda-forge package exists, we can update the installation docs and close this issue.

**Comment by jeromekelleher** [comment]
And we have a [conda package](https://anaconda.org/conda-forge/stdpopsim)!

The feedstock is here: https://github.com/conda-forge/stdpopsim-feedstock

Would some conda users (@agladstein, @gtsambos?) mind trying this out to see how it goes? @ndukler, I seem to remember you're a windows user. Any chance you could try this package out on Windows?

**Comment by agladstein** [comment]
It installed and imported! Both API and CLI. (on a mac)
I'm still planning to go back through the RTD and tutorials and while I do that I can make sure that both the pip and conda versions work as expected.

**Comment by andrewkern** [comment]
sounds like we can update the `analysis` repo install instructions too

**Comment by gtsambos** [comment]
It worked for me also, but see #356

**Comment by gtsambos** [comment]
Hmm, actually, I tested this in a new virtual environment and ran into some problems. Everything installed fine, but when I tried to run it I got this error:

```
(stdpopsim_env) Georgias-MacBook-Pro:~ gtsambos$ stdpopsim --help
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/miniconda3/bin/stdpopsim", line 6, in <module>
    from stdpopsim.cli import stdpopsim_main
  File "/miniconda3/lib/python3.7/site-packages/stdpopsim/__init__.py", line 11, in <module>
    from . genetic_maps import *  # NOQA
  File "/miniconda3/lib/python3.7/site-packages/stdpopsim/genetic_maps.py", line 13, in <module>
    import msprime
  File "/miniconda3/lib/python3.7/site-packages/msprime/__init__.py", line 24, in <module>
    import tskit
  File "/miniconda3/lib/python3.7/site-packages/tskit/__init__.py", line 23, in <module>
    import _tskit
ImportError: numpy.core.multiarray failed to import
```

**Comment by andrewkern** [comment]
@gtsambos can you show us output from `conda list`?

**Comment by gtsambos** [comment]
I just broke a few things trying to reproduce this error, then it worked again once I fixed them 😅 🤷‍♂  I might not be the best person to test this, as I don't use conda much. Will try again later and report back!

**Comment by jeromekelleher** [comment]
This is a Python-only package, so we shouldn't specify any versions for numpy. We should pin msprime all right though --- the next version will fix this.

I'm going to close this issue as I think @gtsambos's problems were due to general conda borkage (sadly common).
