### ISSUE TITLE
PonPyg is wrong ID

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#354]
Genome we have is actually PonAbe. This is a bug in first release, but only the identifier / name is affected.

**Comment by jeromekelleher** [comment]
Ideal thing to do would be to fix PonPyg and add another species for PonAbe

**Comment by jeromekelleher** [comment]
Simplest fix would be to temporarily remove Pongo and push out a quick release. We can figure out the right thing to do afterwards. Having a multispecies model does break our assumptions about how the whole thing is set up, so we should consider it carefully before committing to supporting something.

**Comment by andrewkern** [comment]
agreed

**Comment by dschride** [comment]
> Having a multispecies model does break our assumptions about how the whole thing is set up

Well, there are species, and then there are _species_.

**Comment by apragsdale** [comment]
I agree with Jerome that we should have two different species defined, in that each has their own genome attributes. Will need to think about how to share demographic models between them.

Sorry that I made a mess of the pongo species.. I kind of arbitrarily picked which to use for chromosome lengths, and I'm waiting still to hear back about whether we can include the two recombination maps for them.

I'm still mostly away from the computer this week, but I'll start trying to clean some of this up over the next few days and play with some ideas of sharing the same demographic model across the two species.

**Comment by andrewkern** [comment]
no worries @apragsdale-- easy enough to hint at Pongo being next in the manuscript.

**Comment by jeromekelleher** [comment]
Yeah, no worries @apragsdale, this is a small detail easily fixed.

**Comment by apragsdale** [comment]
Fixed with #363.
