### ISSUE TITLE
"unexpected keyword argument 'kw_only'"

### ISSUE THREAD

**Issue by juanjo75es** [popsim-consortium/stdpopsim#357]
When I try to run any example I always get that error. For example if I run 
`stdpopsim HomSap -c chr22 -o foo.ts 2`
I get:

> Traceback (most recent call last):
>   File "/home/juanjo/.local/bin/stdpopsim", line 6, in <module>
>     from stdpopsim.cli import stdpopsim_main
>   File "/home/juanjo/.local/lib/python3.6/site-packages/stdpopsim/__init__.py", line 12, in <module>
>     from . models import *  # NOQA
>   File "/home/juanjo/.local/lib/python3.6/site-packages/stdpopsim/models.py", line 144, in <module>
>     @attr.s(kw_only=True)
> TypeError: attrs() got an unexpected keyword argument 'kw_only'

**Comment by andrewkern** [comment]
strange. can you post a bit of info about your python install? did you use the pip install?

**Comment by gtsambos** [comment]
Thanks @juanjo75es! Can you see if you still have this problem after manually upgrading the `attrs` package?
Eg. if you use pip,

```
pip install attrs --upgrade
```
@andrewkern , @jeromekelleher: I think this is to do with [this](https://github.com/python-attrs/attrs/pull/281), but the latest version of `attrs` should have fixed this.
