### ISSUE TITLE
MultiSpeciesModel class?

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#371]
hey all- I've been thinking about https://github.com/popsim-consortium/stdpopsim/issues/354 a bit and the complication of having multi-species models in `stdpopsim`. 

I propose that we implement a new class, MultiSpeciesModel, that would have one or more species associated with it, along with a demographic model. mutation rates and genetic maps could be shared between the species modeled. How do folks feel about this?

**Comment by apragsdale** [comment]
I was just thinking about this with this PR (#363). Do we need to define a new class for this feature? Would it make more sense to just have multi-species models defined as functions that can then be imported for each species that needs it, and then added to that species using `_species.add_demographic_model(_loaded_ model)'? I'm not sure exactly why a class would be needed, but I may be misunderstanding something basic about how species and demographic models interact.

**Comment by jeromekelleher** [comment]
Multi-species model class seems complicated to me, and I'm not sure what we'd gain from it. @apragsdale's idea seems like a good one. I think this is a good agenda item for the next call, let's get the conversation going about what we're trying to model here, etc.

**Comment by andrewkern** [comment]
closing this out
