### ISSUE TITLE
document the QC process for adding a species

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#374]
I want to add a new species (dog), but didn't see any documentation for the species QC process.

**Comment by jeromekelleher** [comment]
This is important all right, and we need to systematise it. Propose this as an agenda item for Tuesday's call.

**Comment by grahamgower** [comment]
@ndukler has written some great documentation for how to go about adding a species into the catalog. But there is still no formal or even informal process for QC of a species. Just to highlight why this really is important, I'll note that the AraTha recombination rate has been out by a factor of 10 until #527 was merged today.

**Comment by jeromekelleher** [comment]
Can you open an issue explaining the problem with AraTha recomb rate please @grahamgower? We'll want to mention this in the changelog for 0.1.2, and it's best to point to issues.

**Comment by grahamgower** [comment]
How about we just have a QC checklist for species definitions? A QC reviewer would need to confirm correctness of each item one by one. Where relevant, this would mean identifying a parameter value matches a value given in the listed citation. Below is a proposed checklist. Many items on this list will be easier or unnecessary after #385.

- [ ] Documented (e.g. comment, docstring) reference assembly/version that is being targeted.
- [ ] Number of chromosomes.
  - Non-autosomal chromosomes included? Should they be?
- [ ] Chromosome lengths.
- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

Citations required for:
- Genome reference assembly.
- Mutation rate.
- Recombination rate.
- Recombination map(s) (if relevant).
- Population size.
- Generation time.

For each citation, check:
- [ ] Doi link.
- [ ] Is publication a preprint? Is there a peer-reviewed publication instead?
- [ ] Is the year correct.
- [ ] Is the author correct (spelling, accents/ligatures/etc.)

**Comment by jeromekelleher** [comment]
This is excellent @grahamgower - maybe we could add this as a PR template called "Add a new species"? The documentation is much easier then - we just say, please use the PR template and follow the checklist.

**Comment by jeromekelleher** [comment]
(Or as the QC issue, as you suggested - either way).
