### ISSUE TITLE
random_seed doesn't fix the simulation output

### ISSUE THREAD

**Issue by gtsambos** [popsim-consortium/stdpopsim#381]
Note the output from the notebooks below:

![Screen Shot 2020-01-10 at 4 53 34 pm](https://user-images.githubusercontent.com/17755074/72129343-00ea8000-33ca-11ea-9c24-f71b1c7c0be2.png)

(I've never had this problem with msprime before, so I'm assuming it's internal to stdpopsim?)

**Comment by grahamgower** [comment]
I think the parameter should be `seed`, instead of random_seed.

**Comment by gtsambos** [comment]
oops, thanks @grahamgower 😅
