### ISSUE TITLE
[slim-engine-dev] document the internals of the SLiM engine

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#382]
The SLiM engine is large and getting larger. We need some developer documentation that describes how the backwards-time msprime API is mapped to forwards-time SliM code.

**Comment by jeromekelleher** [comment]
Is this covered @grahamgower, or do we need a follow up PR to improve the docs?

**Comment by grahamgower** [comment]
I think its mostly covered in the header of the slim_engine.py file. If its insufficient or found to be unclear, we can open a new issue when/if that becomes apparent.
