### ISSUE TITLE
Building documentation locally

### ISSUE THREAD

**Issue by arundurvasula** [popsim-consortium/stdpopsim#390]
To build the docs locally, I needed to install the following packages `pip install sphinx sphinx-argparse sphinxcontrib-programoutput sphinx-issues sphinx_rtd_theme`

Could be useful to add this to the documentation about contributing documentation?

**Comment by andrewkern** [comment]
hey @arundurvasula-- list is all included in the `requirements/development.txt` and documented in the dev docs [here](https://stdpopsim.readthedocs.io/en/latest/development.html#installation) i believe.

**Comment by arundurvasula** [comment]
Ahhh ok must have missed that. Thanks!
