### ISSUE TITLE
Inconsistency in growth rate docs for HomSap

### ISSUE THREAD

**Issue by hyanwong** [popsim-consortium/stdpopsim#395]
In the [catalog docs](https://stdpopsim.readthedocs.io/en/latest/catalog.html#sec_catalog_homsap_models_outofafrica_3g09) for the `OutOfAfrica_3G09` model, there is:

```
Growth rate (per gen.) | 0.4 | CEU pop. growth rate (per gen.)
Growth rate (per gen.) | 0.55 | CHB pop. growth rate (per gen.)
```

which (after some digging) I find to be in *percentages*, so that the real `msprime` parameters are [0.004 and 0.0055](https://github.com/popsim-consortium/stdpopsim/blob/349ecca46a70989750c507f0017634786634c61f/stdpopsim/catalog/homo_sapiens.py#L244). The table should clarify the units, especially as in the `OutOfAfrica_2T12` model which is the next one listed in the docs, the rates seem to be proportions instead:

OutOfAfrica_2T12:

```
Growth rate (per gen.) | 0.00307 | EU pop. growth rate 1st expansion
Growth rate (per gen.) | 0.0195 | EU pop. growth rate 2st expansion
```

**Comment by andrewkern** [comment]
closing this issue as this edit has been made
