### ISSUE TITLE
[slim-engine-dev] Use conda package on OSX

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#397]
SLiM now has a [conda package](https://anaconda.org/conda-forge/slim). Update the TravisCI config to install it from conda-forge.

There won't be a Windows package for SLiM for a good long while, so let's ``unittest.skip`` the SLiM engine unit tests on windows.

**Comment by jeromekelleher** [comment]
I don't think it's worth changing the CircleCI config to use the conda package, as this would get quite complicated and would basically require a rewrite of the Circle setup.

**Comment by grahamgower** [comment]
Closed by #400.
