### ISSUE TITLE
Add option to use specific chrom region, and random region with given length

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#401]
For CLI parameters, I think the length should be `-L` and the chromosomal region should should be `-r chr:from-to` to match samtools, etc. It should be possible to specify, e.g `-L 1000 -r chr1`.

**Comment by grahamgower** [comment]
Not sure why I thought that we should add `-r`, when we already have `-c`. I'll use `-c`.

**Comment by jeromekelleher** [comment]
I think it would be better to have ``--start`` and ``--end`` to specify the region to be simulated precisely. Parsing the samtools regionspec is a pain, and more recent protocols (e.g. [htsget](https://academic.oup.com/bioinformatics/article/35/1/119/5040320)) use start and end coordinates.

**Comment by petrelharp** [comment]
This would also be an option to `engine.simulate( )`, right? (or do we already have a way to do it?)

**Comment by grahamgower** [comment]
> This would also be an option to `engine.simulate( )`, right? (or do we already have a way to do it?)

See the `get_contig()` thread over in #670. I don't think we want this to be an option to engine.simulate().

**Comment by petrelharp** [comment]
Oh, right, sorry - I figured this out after I opened this issue.

**Comment by grahamgower** [comment]
Reopening because it's not done yet. (And it it should be done)

**Comment by nspope** [comment]
Closing -- this was done in #1348 by adding `left=...` and `right=...` to `Species.get_contig`. There's no API for getting a random interval; but that seems like the sort of thing people can do themselves easily enough given the basic infrastructure?
