### ISSUE TITLE
merge slim-engine-dev into master

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#404]
I don't think there's much more that needs to be done for merging. There are some very small merge conflicts. Moving the slim specific CLI parsing from slim_engine.py into cli.py will create additional conflicts, so I'm happy to do that as part of the merge commit.

Anything else that you think is missing @jeromekelleher?

**Comment by jeromekelleher** [comment]
I think it's ready to go @grahamgower. There's probably some polishing we need to do docs wise, but let's do them as follow-ups on master and get the big branch merged.

I'd like to rebase the slim-dev branch and make it a standard PR on master (so it will look like a standard (very big, with lots of commits) PR in the history). Should I do this, or would it be better if you made a copy of the slim-dev branch in your fork, rebased that and opened a PR on master?

**Comment by grahamgower** [comment]
I can do the slim-dev rebase (once i fix the recapitation pr and that's merged), and will leave the final pr to master for you.

**Comment by jeromekelleher** [comment]
OK, ping me when it's ready to go so.

**Comment by jeromekelleher** [comment]
I had a go at rebasing the slim-dev branch and made a mess of it. Would you mind making a copy of the branch, rebasing it against upstream/master and opening a PR please @grahamgower? Once that's merged we can then delete the dev branch.

**Comment by grahamgower** [comment]
Ah, shit, sorry. I just merged without rebase before. And github has been buggy all afternoon too... Uggh..

**Comment by grahamgower** [comment]
#409 merged.
