### ISSUE TITLE
Badges in README point to popgensims

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#410]
The badges in the README weren't updated after we changed the GitHub team to popsim-consortium. Need to go through and fix.

**Comment by grahamgower** [comment]
Well, travis is still not playing ball. Clicking through to the [travis builds](https://travis-ci.org/github/popsim-consortium/stdpopsim) shows successes, but the badge still is unknown.  @jeromekelleher, maybe there's something in your travis dashboard that needs poking, as per: 
https://stackoverflow.com/a/48632145

**Comment by jeromekelleher** [comment]
Thanks @grahamgower. Fixed now, I just needed to turn on the branch builds.
