### ISSUE TITLE
Minor restructuring of tutorial needed

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#414]
One of the review comments is that the tutorial is slightly confusing. Looking at the overall structure I think this is true -- the sectioning is a bit weird (we have an empty section in the Python API bit) and there's not really much of a logical progression.

Should be done after PR #340 is merged.

**Comment by agladstein** [comment]
I can work on this

**Comment by petrelharp** [comment]
Hopefully, #460 fixes this? I'd appreciate someone looking at the big picture though.

**Comment by agladstein** [comment]
I think it's improved in https://github.com/popsim-consortium/stdpopsim/pull/460, but still think it should be changed a bit.

I think it makes sense to have the overall structure:
- Running stdpopsim with the command-line interface (CLI)
- Running stdpopsim with the Python interface
- Example analyses with stdpopsim

**Comment by agladstein** [comment]
Reminder to add response to reviewers.
