### ISSUE TITLE
Link to Wiki for model discussion

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#415]
Prompted by reviewer comments and discussed in the meeting 17/03, we decided to explore linking out to a Wiki to allow people to put in more detailed documentation of population models etc.

I'll look into this and report back.

**Comment by jeromekelleher** [comment]
I've turned on the wiki and populated it with a few stub pages. I'm not sure it's *quite* what we're looking for, tbh. It's going to be a lot of work filling out all these pages (although I'm sure we could automate adding stub pages) and it's all quite... static.

Here's an example page: https://github.com/popsim-consortium/stdpopsim/wiki/HomSap-demographic_models-OutOfAfrica_3G09

I'm not sure who has write access to this wiki also: can a few people try to edit the wiki and report back here please? Part of the idea is to dynamically crowdsource knowledge about these models, so we need to make it super easy to edit.

I'm starting to think that we'd need a more dynamic catalog that has this sort of functionality built-in. This would be quite a lot of work though, so I'd be tempted to drop this from the next release and push to make a significant project (like GSOC or something).

**Comment by ndukler** [comment]
I can edit it, but I agree, this is a significant undertaking in it's own right. It feels almost like it should be a partner project with a full group committed to it.

**Comment by agladstein** [comment]
I think we decided to hold off on this.

**Comment by jeromekelleher** [comment]
yes, closing for now.
