### ISSUE TITLE
Improve github initial user experience

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#417]
We can make the github user experience more friendly

- Improve the docs in the README.md (Hello! thanks for dropping by, here are some helpful links to the documentation)
- Add a CONTRIBUTING.md file (which would basically just link to the relevant place in the documentation)
- Add a [first interaction](https://github.com/marketplace/actions/first-interaction) github action which will point users to the relevant parts of the documentation

**Comment by grahamgower** [comment]
Maybe we could have more "good first issue" tags? Is it possible to give non-admins permission to add such tags (I can't currently)?

**Comment by jeromekelleher** [comment]
Good idea. Anyone know if we can let ``popgensims/all`` add labels etc? I've not understood GitHub's most recent permissions model.

**Comment by Chris1221** [comment]
The docs seem to indicate that you can give "triage" permissions on an individual/repository basis to manage issues without write access:

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization

> "Triage: Recommended for contributors who need to proactively manage issues and pull requests without write access"

**Comment by jeromekelleher** [comment]
Thanks @Chris1221, I think I've figured it out. Everyone in stdpopsim/all should have triage rights now for this repo. @grahamgower, can you update labels now?

**Comment by grahamgower** [comment]
Yep, that's done the trick. I now see the little cog to add "Labels", as well as for "Assignees" and "Milestone".

**Comment by nspope** [comment]
Closing this as we have lots of onboarding for new contributors in the docs, feel free to reopen
