### ISSUE TITLE
Statistical checks for SLiM engine

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#418]
We want to do a validation plot for the manuscript (https://github.com/popsim-consortium/manuscript/issues/150) but we also want to have some simple automated validation scripts we can do here. I'm imagining a much simpler version of msprime's verification.py statistical tests, we compare QQ-plots of tree sequence statistics when running a representative sample of models through both engines.

@grahamgower, have you had any thoughts about how to do this/what we should include?

**Comment by jeromekelleher** [comment]
Some discussion on whether migration rates need to be scaled or not on the call, so we should definitely include models with migration.

**Comment by grahamgower** [comment]
I think we should start by doing validation step-by-step on simple models. Something like these:
1. `PiecewiseConstantSize()` - single population.
2. `IsolationWithMigration()` - two populations with migration.
3. OutOfAfrica_3G09 - three populations with migration, and non-zero `growth_rate`.

And probably two more complex models.
1. AmericanAdmixture_4B11 - this confused me for a good while, and we should check that I didn't screw anything up.
2. AncientEurasia_9K19 - lots of populations, admixture pulses, and ancient sampling.

I suppose the relevant summary statistics might be different for different models. But probably some measures of diversity and Fst will be useful. A matrix of all F3 permutations for the complex models would be cool, but maybe not practical.

Are there any summary stats that we expect to be inherently differ between msprime and SLiM (and thus not constitute an implementation bug)?

**Comment by jeromekelleher** [comment]
Sounds good @grahamgower.  We should also consider using branch length stats to get rid of some noise, or maybe look directly at some tree sequence summaries (number of trees, number of edges, number of nodes).

> Are there any summary stats that we expect to be inherently different between msprime and SLiM (and thus not constitute an implementation bug)?

No idea; @petrelharp, any thoughts here?

**Comment by andrewkern** [comment]
i think any/all of the [branch stats in tskit](https://tskit.readthedocs.io/en/latest/stats.html#available-statistics) would be completely appropriate here.

**Comment by andrewkern** [comment]
in addition it would be good to summarize patterns of LD, perhaps by looking at the decay in LD with distance. we could use scikit-allel for that.

**Comment by jeromekelleher** [comment]
Tskit also computes LD: https://tskit.readthedocs.io/en/latest/python-api.html#linkage-disequilibrium

**Comment by grahamgower** [comment]
It might need to be scikit-allel. I get this error when trying to use tskit's r2_array.
`_tskit.LibraryError: Only infinite sites mutations are supported for this operation`

**Comment by jeromekelleher** [comment]
You're right, tskit's current LD calculation is very limited. Easier to use scikit-allel than to enforce the requirements.

**Comment by petrelharp** [comment]
If we are just using WF models in SLiM then it should all match msprime quite well... With small sample sizes anyhow.

**Comment by grahamgower** [comment]
The attached msprime/slim QQ plots should be up to date with git HEAD. (See validation.py for details on what slim1, slim2, etc. means).

[Africa_1T12_msprime1__Africa_1T12_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407521/Africa_1T12_msprime1__Africa_1T12_slim1.pdf)
[AmericanAdmixture_4B11_msprime1__AmericanAdmixture_4B11_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407522/AmericanAdmixture_4B11_msprime1__AmericanAdmixture_4B11_slim1.pdf)
[AncientEurasia_9K19_msprime1__AncientEurasia_9K19_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407523/AncientEurasia_9K19_msprime1__AncientEurasia_9K19_slim1.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407524/onepop_bottleneck_msprime1__onepop_bottleneck_slim1.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407525/onepop_bottleneck_msprime1__onepop_bottleneck_slim2.pdf)
[onepop_bottleneck_msprime1__onepop_bottleneck_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407526/onepop_bottleneck_msprime1__onepop_bottleneck_slim3.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407527/onepop_constantN_msprime1__onepop_constantN_slim1.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407528/onepop_constantN_msprime1__onepop_constantN_slim2.pdf)
[onepop_constantN_msprime1__onepop_constantN_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407529/onepop_constantN_msprime1__onepop_constantN_slim3.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407530/onepop_expgrowth_msprime1__onepop_expgrowth_slim1.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407531/onepop_expgrowth_msprime1__onepop_expgrowth_slim2.pdf)
[onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407532/onepop_expgrowth_msprime1__onepop_expgrowth_slim3.pdf)
[OutOfAfrica_3G09_msprime1__OutOfAfrica_3G09_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407533/OutOfAfrica_3G09_msprime1__OutOfAfrica_3G09_slim1.pdf)
[twopop_ancient_samples_msprime1__twopop_ancient_samples_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407534/twopop_ancient_samples_msprime1__twopop_ancient_samples_slim1.pdf)
[twopop_ancient_samples_msprime1__twopop_ancient_samples_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407535/twopop_ancient_samples_msprime1__twopop_ancient_samples_slim2.pdf)
[twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407536/twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim1.pdf)
[twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407537/twopop_asymmetric_migration_msprime1__twopop_asymmetric_migration_slim2.pdf)
[twopop_no_migration_msprime1__twopop_no_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407538/twopop_no_migration_msprime1__twopop_no_migration_slim1.pdf)
[twopop_no_migration_msprime1__twopop_no_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407539/twopop_no_migration_msprime1__twopop_no_migration_slim2.pdf)
[twopop_pulse_migration_msprime1__twopop_pulse_migration_slim1.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407540/twopop_pulse_migration_msprime1__twopop_pulse_migration_slim1.pdf)
[twopop_pulse_migration_msprime1__twopop_pulse_migration_slim2.pdf](https://github.com/popsim-consortium/stdpopsim/files/4407541/twopop_pulse_migration_msprime1__twopop_pulse_migration_slim2.pdf)

**Comment by petrelharp** [comment]
Damn, that's very nice. I say we put all those in a directory in the manuscript repo?

And, I don't see anything worrisome - do you? We don't expect `num_sites` to match, since SLiM retains some monomorphic sites. Same with `num_nodes` and `num_edges` if it's not simplified. (but these are simplified, right?)

**Comment by andrewkern** [comment]
can this be the first topic of conversation on the call in 20min?

**Comment by grahamgower** [comment]
Is there anything else folks want to see here, or can this issue be closed?

**Comment by jeromekelleher** [comment]
I'm happy to close.
