### ISSUE TITLE
the SLiM engine should print some details in the "Simulation information"

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#419]
As raised during @andrewkern's review of the SLiM engine in #409.
```
[...] also along these lines I think we want a message in the
"Simulation information:" stderr chunk that says if the slimulation
was run with burnin/recap
```
Maybe there are other relevant things to include too.

**Comment by petrelharp** [comment]
Already SLiM is printing more info that msprime; and recap happens all the time (isn't optional), while burn-in is user-specified; so I don't think this is necessary/helpful.
