### ISSUE TITLE
Add docstring for `Species.genetic_maps`.

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#423]
As pointed out in #422, the genetic_maps attribute for species is undocumented.

**Comment by grahamgower** [comment]
In #198 @jeromekelleher says that this undocumented on purpose.

**Comment by jeromekelleher** [comment]
Hmmm, tricky. The bad thing about documenting things is that you're then stuck with them forever. I'm not sure that the Python API is mature enough for this yet. However, changing ``genetic_maps`` to a dict mapping IDs to the maps seems like a logical enough thing (not sure why it's a list now).

**Comment by grahamgower** [comment]
Closing, as there are now comments in the code suggesting this is deliberatly undocumented.
https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/species.py#L135-L139
https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/species.py#L230-L244
