### ISSUE TITLE
Clean up remote resources handling/caching

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#424]
As I'm writing up the AWS documentation its reminding me of a few organizational things I wanted to get done to make it easier down the line and I was wondering what people thought of them.
- Reorganize the cache file structure (and the parallel AWS file structure) to be the following:
  - species <--- six character id
    - assembly_1 <-- (e.g. hg37, hg38, etc.)
      - chromInfo.txt <-- contains the chromosome lengths that are currently hardcoded
      - genetic_maps
        - chrA.txt
        - chrB.txt
        - README.md
      - mutation_maps <-- long term

I think this will smooth things over for transitioning to a more robust genome architecture and it is a bit easier to present in the documentation. This will require small alterations to the code but seeing as we only have one assembly per species for now we can hold off on some of the more involved bits. Regardless I would at least like to upload it to AWS in this form and we can make alterations to stdpopsim when we have time. What do you think @andrewkern @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Overall file structure looks just right to me.

**Comment by ndukler** [comment]
Can we close this @jeromekelleher ?

**Comment by jeromekelleher** [comment]
Yep, thanks @ndukler.
