### ISSUE TITLE
Tests throwing errors on windows

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#425]
I'm getting a decent number of errors when I run the test suite on windows 10. I've attached the output I get to this issue.
[test_error_log.txt](https://github.com/popsim-consortium/stdpopsim/files/4352300/test_error_log.txt)

**Comment by grahamgower** [comment]
The `test_all_engines` failure looks like the slim executable can't be found during version checking. And `test_tar_path_traversal_attack` is failing to create a symlink---googling suggests  symlinks need admin privileges on windows.

The first two failures might be related. They're probably more difficult to figure out without sitting down at a windows system.

**Comment by jeromekelleher** [comment]
Thanks @ndukler, we'll get these sorted out once we get Appveyor working again in #421.

**Comment by jeromekelleher** [comment]
Probably we'll just unittest.skip() most issues though.

**Comment by jeromekelleher** [comment]
Can you try this again with the latest updates @ndukler? We should have fixed most of the issues now.

**Comment by ndukler** [comment]
Ok, so I re-ran the tests on the new version in a console that had admin privileges and got the attached error log.
[test_error_log_2.txt](https://github.com/popsim-consortium/stdpopsim/files/4355184/test_error_log_2.txt)

**Comment by jeromekelleher** [comment]
OK, great, looks like we're down to one error. It's a weird one though. What version of Python are you on?

**Comment by ndukler** [comment]
Python: 3.7.1
Conda: 4.8.3

**Comment by ndukler** [comment]
python -m nose tests

**Comment by grahamgower** [comment]
Can you try ` python -m nose -s tests`?

**Comment by ndukler** [comment]
I just did and it produced no errors. That being said it's still writing warnings:

Warning: recombination map not found for chromosome: 'chr22' on map: 'HapMapII_GRCh37', substituting a flat map with chromosome recombination rate 1.4445022767788226e-08

UserWarning: Non-autosomal simulations are not yet supported. See https://github.com/popsim-consortium/stdpopsim/issues/383 and https://github.com/popsim-consortium/stdpopsim/issues/406

which I assume we don't want to actually see while running tests

**Comment by ndukler** [comment]
We also need to update the devdocs with the new test command if it is required.

**Comment by ndukler** [comment]
This is good enough for me to keep working though as I can easily tell which errors are due to my code now :)

**Comment by grahamgower** [comment]
Great! The dev docs should definitely mention using `-s`. I've never had the tests pass without it.

**Comment by ndukler** [comment]
Ok, I'll close this if there are no objections?

**Comment by jeromekelleher** [comment]
> Great! The dev docs should definitely mention using -s. I've never had the tests pass without it.

This is a bug, I didn't realise it. I'll open an issue.
