### ISSUE TITLE
Format code with Black?

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#433]
Anyone object if we start using [Black](https://black.readthedocs.io/en/stable/) for code formatting?

We moved over recently for [tskit](https://github.com/tskit-dev/tskit) and it's wonderful. No more decisions about how to format code, it's just done for you.

Having a clear and unambiguous policy about coding style is also an important part of being developer friendly, I think.

**Comment by grahamgower** [comment]
Yeah, sound like a great idea. There are some cases where the output is a bit ugly, but I guess we can live with that.

**Comment by andrewkern** [comment]
fine by me but any tips on how to use it? do you just set up a pre-commit hook?

**Comment by jeromekelleher** [comment]
Yeah, we've got it set up using [pre-commit](https://pre-commit.com/) for tskit and it's awesome. Can easily check a bunch of other stuff too.

**Comment by grahamgower** [comment]
#677 added the pre-commit config. We now need to integrate this into CI, and blacken all files in the codebase.

**Comment by grahamgower** [comment]
Closed by #677 and #685.
