### ISSUE TITLE
SLiM tree sequences have higher num_sites than msprime

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#434]
See validation plots ending in "_slim2.pdf": https://github.com/popsim-consortium/stdpopsim/pull/431#issuecomment-602589125
The _slim2.pdf comparisons are for slim simulations without recapitation and without rescaling time.

**Comment by grahamgower** [comment]
I think this has been resolved with the last rounds of changes. Not sure which specific thing helped, but I no longer see this artifact in https://github.com/popsim-consortium/stdpopsim/issues/418#issuecomment-606468748

**Comment by jeromekelleher** [comment]
Great, thanks @grahamgower. Closing.
