### ISSUE TITLE
SLiM engine doesn't pass Ne or migration_rates to `ts.recapitate()`.

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#437]
It's not immediately clear to me what the call to `ts.recapitate()` should look like in the slim engine, but I'm pretty sure its wrong right now.

* What should `Ne` be in our case, where we likely have a single ancestral population at time `ts.slim_generation`? Should it be the size of that ancestral population at time `ts.slim_generation`? How are the values in `population_configurations` used, if at all?
* At present, we only have demographic models with a single ancestral population. I suppose this won't always be the case. Under the assumption that we have multiple populations in existence for recapitation, how does the call to `ts.recapitate()` look then? Do we pass a modified population_configurations with the relevant population sizes for each of the remaining populations at time `ts.slim_generation`? Presumably `migration_rates` should be set following 
[the docs](https://msprime.readthedocs.io/en/latest/tutorial.html#sec-tutorial-simulate-from).

@petrelharp, it would be great to get your input here!
The relevant code is in `_SLiMEngine.simulate()`: https://github.com/popsim-consortium/stdpopsim/blob/e1d4125c64fad0bbb6bb3fd8b45f283cbbd2d6b2/stdpopsim/slim_engine.py#L557-L668

**Comment by petrelharp** [comment]
The arguments to recapitate are just as to `msprime.simulate`, but let's not worry about multiple ancestral pops for the moment if we don't have any need for it. So, we should just be able to pass `Ne` and the recomb map. Ne is the diploid pop size of the ancestral population.
