### ISSUE TITLE
When msprime 1.0 is released, we should use discrete recombination maps

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#441]
Also for the slim engine, see #438 and #439.

**Comment by mufernando** [comment]
hey, it turns out I'm running into this issue right now. any ideas how to deal with this?

**Comment by jeromekelleher** [comment]
What do you mean @mufernando?

**Comment by grahamgower** [comment]
We chatted about this on Slack, and it seems @mufernando had introduced the same change in #644 that was reverted to fix #439. I.e. doing recapitation with a recombination map. The solution is to either specify a recombination rate (rather than providing a map, uniform or otherwise), or to rely on msprime 1.0 features and recapitate with discrete=True. I think @mufernando is going to do the latter?

**Comment by jeromekelleher** [comment]
> or to rely on msprime 1.0 features and recapitate with discrete=True. I think @mufernando is going to do the latter?

Yes, that's the way to go all right. It would be best to start using [sim_ancestry](https://tskit-dev.github.io/msprime-docs/main/ancestry.html#msprime.sim_ancestry), as this has the discrete_genome=True as the default and we'll want to transition stdpopsim to using this when 1.0 is available.

**Comment by jeromekelleher** [comment]
#764 almost closes this, but I think we can only close when we've updated the SLiM engine recaptitate step.

**Comment by grahamgower** [comment]
The slim engine is using sim_ancestry() and sim_mutations() now. Anything specific we need to do to close out this issue? @jeromekelleher @mufernando 

https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/slim_engine.py#L1296-L1325

**Comment by petrelharp** [comment]
Well, (a) `msprime.simulate` only appears in testing code, and (b) the phrase `discrete_genome` doesn't appear in the repository, and we'd need to set `discrete_genome=False` to get sim_ancestry to be continuous. So I think we're good (although we should probably change the testing code, and also there is [this note](https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/slim_engine.py#L1296)).

**Comment by grahamgower** [comment]
Thanks @petrelharp. Looks like the test code is using msprime.simulate in quite reasonable ways (checking functions that do things with tree sequences), so I don't think we need to do anything there.
