### ISSUE TITLE
docs: manuscript citation

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#451]
Add biorxiv manuscript citation to read the docs https://stdpopsim.readthedocs.io/en/latest/introduction.html#citations

And maybe link to manuscript in README

**Comment by grahamgower** [comment]
Good idea. Probably this citation should be printed on stdout when doing simulations too.

**Comment by grahamgower** [comment]
I'm not sure. I guess as long as it gets tracked through the doi it won't matter much either away. What do others think?
