### ISSUE TITLE
add warning when using Q != 1

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#455]
Proposed rough text:

> You are using rescaled populations (setting Q not equal to 1). This should give similar results for many situations, but is not equivalent, especially in the presence of lots of selection. To use rescaling, you should be careful - do checks and compare results across different values of Q.

**Comment by jeromekelleher** [comment]
Can we turn this warning off then with `--quiet`? Having an option that always writes out warning text when you use it is pretty obnoxious.

**Comment by andrewkern** [comment]
can we change the phrase "of lots of selection" to "of selection"?

**Comment by petrelharp** [comment]
Please edit, this is a terrible first draft.

**Comment by grahamgower** [comment]
I'm having second thoughts about adding this warning. We already warn when population sizes get small (See https://github.com/popsim-consortium/stdpopsim/pull/478/commits/6662405dddf6d58804e809d0dbfa36b29f5ede7d and #456), which will be seen for many models and even moderate scaling. I wonder if that's enough?

Or maybe we could have this warning at the CLI, but not when using the Python API?

**Comment by petrelharp** [comment]
You're probably right - defaulting to Q=1 is probably enough. But, on the other hand, if it can be turned off with `quiet`, then it doesn't hurt.
