### ISSUE TITLE
User documentation for slim engine

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#457]
We need a couple of simple examples using the CLI, setting `--slim-scaling-factor`, and a big warning/discussion about some of the caveats discussed in #444 and #445. Probably the CLI warning one gets when using a scaling factor (see #455) should point at this section of the documentation.

**Comment by petrelharp** [comment]
This will be closed by #460.

**Comment by agladstein** [comment]
Should this be closed?

**Comment by andrewkern** [comment]
closing
