### ISSUE TITLE
generic models have no `generation_time`, so can't be run with the slim engine

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#459]
For instance:
```
import stdpopsim
species = stdpopsim.get_species("HomSap")
contig = species.get_contig("chr22")
model = stdpopsim.PiecewiseConstantSize(1e4)
samples = model.get_samples(200)
engine = stdpopsim.get_engine("slim")
ts = engine.simulate(model, contig, samples, slim_burn_in=0.1)
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/.local/lib/python3.7/site-packages/stdpopsim-0.1.2.dev72+ng59af5ea-py3.7.egg/stdpopsim/slim_engine.py", line 627, in simulate
  File "/home/peter/.local/lib/python3.7/site-packages/stdpopsim-0.1.2.dev72+ng59af5ea-py3.7.egg/stdpopsim/slim_engine.py", line 296, in slim_makescript
  File "/home/peter/.local/lib/python3.7/site-packages/stdpopsim-0.1.2.dev72+ng59af5ea-py3.7.egg/stdpopsim/slim_engine.py", line 296, in <listcomp>
AttributeError: 'PiecewiseConstantSize' object has no attribute 'generation_time'
```
Maybe the call to `PiecewiseConstantSize( )` needs another argument, `species`, so it can inherit properties like `generation_time`? Or, maybe we just need a `generation_time` argument to either `PiecewiseConstantSize( )` or `_SLiMEngine.simulate( )`?

**Comment by grahamgower** [comment]
I've just been setting that property of the model manually (like `cli.py` does when no demographic model is requested). Not sure what the best solution here is.

**Comment by jeromekelleher** [comment]
What do you set the value to @grahamgower? Perhaps we should make ``generation_time`` an attribute that is shared by all models, and is None by default. Therefore, if ``generation_time`` doesn't make sense but the engine has to set it, the engine can make the choice?

**Comment by grahamgower** [comment]
I set `model.generation_time = species.generation_time`. Certainly, we could move that into the slim engine's `simulate()` method.

**Comment by grahamgower** [comment]
Oh, actually, we can't. The engine doesn't get the species object.

**Comment by jeromekelleher** [comment]
I guess having the species as an optional second argument to ``PiecewiseConstantSize`` and other generic models is the best thing to do. Can you see any drawbacks?

**Comment by grahamgower** [comment]
How about having `generation_time` as the argument to `PiecewiseConstantSize` instead? It could default to 1, but it might be better to insist on a value being provided.

**Comment by jeromekelleher** [comment]
Yeah, that sounds sensible. We should make the engines consistent though, if we add a generation time argument we'd want to make sure that the msprime engine is using it also.

**Comment by grahamgower** [comment]
How about something like this (no engine changes)?

```
diff --git a/stdpopsim/models.py b/stdpopsim/models.py
index db11b71..6e98f48 100644
--- a/stdpopsim/models.py
+++ b/stdpopsim/models.py
@@ -2,6 +2,7 @@
 Common infrastructure for specifying demographic models.
 """
 import sys
+import warnings
 
 import attr
 import msprime
@@ -323,7 +324,11 @@ class PiecewiseConstantSize(DemographicModel):
     year = None
     doi = None
 
-    def __init__(self, N0, *args):
+    def __init__(self, N0, *args, generation_time=None):
+        if generation_time is None:
+            warnings.warn("No generation_time provided, using default of 1")
+            generation_time = 1
+        self.generation_time = generation_time
         self.population_configurations = [
             msprime.PopulationConfiguration(
                 initial_size=N0, metadata=self.populations[0].asdict())
```

**Comment by jeromekelleher** [comment]
I dunno about the warning - why not just make it a mandatory argument? Every warning you add means more tests have to be written, more corner cases to think about.

But the point remains about the msprime engine - it appears that this isn't using the generation_time while the slim engine is?

**Comment by grahamgower** [comment]
Sure, I agree that the argument should be mandatory. And yes, msprime doesn't use the generation_time, but the slim engine does. The slim engine uses the generation_time to write time to the script in years, in an attempt to make the script more standalone.

**Comment by jeromekelleher** [comment]
The script is still standalone if the output is in units of generations, isn't it? Seem artificial to force a generation time to me. On the other hand, maybe all the output from stdpopsim should be in years for consistency.

**Comment by grahamgower** [comment]
I can only think in terms of years, so I wrote the engine to output times in years to the slim script. The generation time is also included in the slim script to then convert from years to generations. So, if a user generates a slim script, it's easy to change the generation time in the stanza at the top of the script. It would, of course, be possible to change this behaviour so that times are written into the slim script in units of generations.

SLiM outputs tree sequences with node times in units of generations. I don't think this is directly configurable.

**Comment by jeromekelleher** [comment]
@petrelharp, have you any thoughts here. Would it be better to write the slim script in generations rather than years, given that the output is in generations?

**Comment by andrewkern** [comment]
> How about having `generation_time` as the argument to `PiecewiseConstantSize` instead? It could default to 1, but it might be better to insist on a value being provided.

I think this is a simple way to go that will by default give equivalent output between engines, but allows the user to change `generation_time` if they wish.

**Comment by petrelharp** [comment]
Well, I definately think we should output in the same time units from both SLiM and msprime. What else are we using `generation_time` for? Nothing, it looks lke from a quick grep.

 I'm generally in favor of returning things in real units, and "years" seems somewhat more real than "generations"... but, I'm not so sure in this case, because actual generation times are not that well known, so returning things in units of generations reduces some of the uncertainty, in some sense. I guess.  Hm, but when we add non-WF models in SLiM, we definately won't want to be returning things in generations at *that* point (since generation time is an emergent property of the simulation). I guess I am - somewhat reluctantly - in favor of rescaling all the outputs by `generation_time`, then. I could be talked out of this.

**Comment by petrelharp** [comment]
It seems maybe better to pass the species in to the generic model than just passing in generation time, since there may be other properties it'd be useful to get out of species in the future?

**Comment by andrewkern** [comment]
> but when we add non-WF models in SLiM, we definately won't want to be returning things in generations at _that_ point (since generation time is an emergent property of the simulation). 

yes when we get to non-WF models all bets are off here and I think we should punt on those design choices at the moment.
