### ISSUE TITLE
add a `dryrun` flag to the slim script for unit testing the slim engine

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#466]
The generated SLiM script should check for this flag at the end of the first generation and exit if the flag is set. This flag may be set by stdpopsim unit tests for quickly checking the validity of the generated SLiM code.

**Comment by jeromekelleher** [comment]
We already have a ``--dry-run`` option:

https://github.com/popsim-consortium/stdpopsim/blob/e3bc9a67c27551115894da039716f7db6353edbb/stdpopsim/cli.py#L344-L346

**Comment by grahamgower** [comment]
Yep. I probably wont reuse the name `dryrun`. I was just using it here as a analogy with the existing flag. This can be implemented without exposing anything new to the CLI or the Python API.

**Comment by grahamgower** [comment]
Although, maybe it should be connected to the `--dry-run` CLI parameter....?

**Comment by jeromekelleher** [comment]
Might as well connect to the existing parameter unless it's doing something dramatically different, right?
