### ISSUE TITLE
readthedocs build failing due to prerequisites

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#468]
Here's what's going on: does anyone know how to fix this?
![Screenshot from 2020-04-06 16-35-38](https://user-images.githubusercontent.com/1046249/78614899-cb1c3280-7824-11ea-805a-eaea0a44cfc8.png)

It looks like it's [been failing for a while](https://readthedocs.org/projects/stdpopsim/builds/). The last passing commit was [this one](https://readthedocs.org/projects/stdpopsim/builds/), and the first failing commit after that was [this one](https://readthedocs.org/projects/stdpopsim/builds/), but there were no changes to the requirements in the intervening commits, I think?

**Comment by petrelharp** [comment]
[The docs](https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#use-pip-when-possible) suggest using `pip` instead of `conda`, but give no guidance on how to do this?

**Comment by petrelharp** [comment]
Well, some flailing around over in #469 didn't get me anywhere. Switching to pip failed to install msprime because of not being able to find `gsl`. And we need to actually install stdpopsim for autodoc to work, and for stdpopsim we need msprime.

Not sure what to do: maybe whatever `msprime` does, but what's different about that is not clear to me.

**Comment by jeromekelleher** [comment]
It used to work before, and I've been hoping it would sort itself out (you get a fair amount of transient failures with conda, unfortunately). We have to use conda because we want to run msprime. This is different to the docs for msprime because we don't actually need to run msprime there, and the low-level module is never built.

I don't really know how to fix this, other than try to figure out what's using too much memory.

**Comment by jeromekelleher** [comment]
I guess a place to start is to try and figure out why our conda env is using so much memory. One possibility is that we're not being specific enough with our versioning and the solver is doing lots of work because of this.

Would it be possible for a conda user to try out this command:
```
conda env create --quiet --name latest --file requirements/rtd-conda-environment.yml
```

and report back on how much memory it uses please? We could then try pinning all the package versions and see if this helps.

**Comment by grahamgower** [comment]
```
$ /usr/bin/time conda env create --quiet --name stdpopsim-latest --file requirements/rtd-conda-environment.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
62.01user 9.60system 4:43.30elapsed 25%CPU (0avgtext+0avgdata 663880maxresident)k
234736inputs+765328outputs (14major+618645minor)pagefaults 0swaps
```
(`/usr/bin/time` has been patched on this system, and I have confirm the `maxresident` value is in the correct units)

```
$ cd ~/miniconda3/envs/
$ du -hs stdpopsim-latest
1.5G    stdpopsim-latest
```

**Comment by jeromekelleher** [comment]
Thanks @grahamgower! So, is that ~650M max resident? Not a huge amount, but not small either I guess.

**Comment by grahamgower** [comment]
Yeah, 650 mb doesn't seem high enough to cause failure to me. Here's the package list.
```
$ conda list --name stdpopsim-latest
# packages in environment at ~/miniconda3/envs/stdpopsim-latest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38hd463f26_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
commonmark                0.7.5                      py_0    conda-forge
cryptography              2.8              py38h766eaa4_2    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
h5py                      2.10.0          nompi_py38h513d04c_102    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
humanize                  2.2.0                      py_0    conda-forge
idna                      2.9                        py_1    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.6.0            py38h32f6830_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
msprime                   0.7.4            py38ha777a67_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.18.1           py38h8854b6b_1    conda-forge
openssl                   1.1.1f               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.2           h8356626_5_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
setuptools-scm            3.5.0                      py_1    conda-forge
setuptools_scm            3.5.0                         1    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sphinx                    3.0.0                      py_0    conda-forge
sphinx-argparse           0.2.5                      py_0    conda-forge
sphinx-issues             1.2.0                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-programoutput 0.16               pyh9f0ad1d_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
svgwrite                  1.4                        py_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tskit                     0.2.3            py38hc1659b7_0    conda-forge
urllib3                   1.25.7           py38h32f6830_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.4             h516909a_1002    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by jeromekelleher** [comment]
Would you mind checking if that comes down at all if you pin each of our packages at these versions? It's plausible RTD has a 500M upper bound on memory.

**Comment by grahamgower** [comment]
Do you mean just adding `==1.2.3` (or whatever) at the end of each line in `requirements/rtd-conda-environment.yml`?

**Comment by grahamgower** [comment]
I just tried that and got basically the same result.
```
$ /usr/bin/time conda env create --quiet --name stdpopsim-latest-pinned --file requirements/rtd-conda-environment.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
41.56user 6.42system 2:20.33elapsed 34%CPU (0avgtext+0avgdata 649604maxresident)k
47816inputs+602680outputs (13major+514655minor)pagefaults 0swaps
```

**Comment by jeromekelleher** [comment]
Yes, that's what I meant, thanks @grahamgower. Well, I'm stumped then - any ideas?

**Comment by grahamgower** [comment]
Pin everything (diff below)?
```
$ /usr/bin/time conda env create --quiet --name stdpopsim-latest-pin-everything --file requirements/rtd-conda-environment.yml     Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
20.97user 5.87system 1:56.73elapsed 22%CPU (0avgtext+0avgdata 572424maxresident)k
47816inputs+387960outputs (13major+376176minor)pagefaults 0swaps
```

```
diff --git a/requirements/rtd-conda-environment.yml b/requirements/rtd-conda-environment.yml
index 67f23a9..a805870 100644
--- a/requirements/rtd-conda-environment.yml
+++ b/requirements/rtd-conda-environment.yml
@@ -4,11 +4,79 @@ channels:
   - conda-forge
 
 dependencies:
-  - setuptools_scm
-  - attrs
-  - appdirs
-  - msprime
-  - sphinx-argparse
-  - sphinx-issues
-  - sphinxcontrib-programoutput
-  - humanize
+  - _libgcc_mutex==0.1
+  - _openmp_mutex==4.5
+  - alabaster==0.7.12
+  - appdirs==1.4.3
+  - attrs==19.3.0
+  - babel==2.8.0
+  - ca-certificates==2020.4.5.1
+  - certifi==2020.4.5.1
+  - cffi==1.14.0
+  - chardet==3.0.4
+  - commonmark==0.7.5
+  - cryptography==2.8
+  - docutils==0.16
+  - future==0.18.2
+  - gsl==2.6
+  - h5py==2.10.0
+  - hdf5==1.10.5
+  - humanize==2.2.0
+  - idna==2.9
+  - imagesize==1.2.0
+  - importlib-metadata==1.6.0
+  - importlib_metadata==1.6.0
+  - jinja2==2.11.1
+  - jsonschema==3.2.0
+  - ld_impl_linux-64==2.34
+  - libblas==3.8.0
+  - libcblas==3.8.0
+  - libffi==3.2.1
+  - libgcc-ng==9.2.0
+  - libgfortran-ng==7.3.0
+  - liblapack==3.8.0
+  - libopenblas==0.3.9
+  - libstdcxx-ng==9.2.0
+  - llvm-openmp==9.0.1
+  - markupsafe==1.1.1
+  - msprime==0.7.4
+  - ncurses==6.1
+  - numpy==1.18.1
+  - openssl==1.1.1f
+  - packaging==20.1
+  - pip==20.0.2
+  - pycparser==2.20
+  - pygments==2.6.1
+  - pyopenssl==19.1.0
+  - pyparsing==2.4.7
+  - pyrsistent==0.16.0
+  - pysocks==1.7.1
+  - python==3.8.2
+  - python_abi==3.8
+  - pytz==2019.3
+  - readline==8.0
+  - requests==2.23.0
+  - setuptools==46.1.3
+  - setuptools-scm==3.5.0
+  - setuptools_scm==3.5.0
+  - six==1.14.0
+  - snowballstemmer==2.0.0
+  - sphinx==3.0.0
+  - sphinx-argparse==0.2.5
+  - sphinx-issues==1.2.0
+  - sphinxcontrib-applehelp==1.0.2
+  - sphinxcontrib-devhelp==1.0.2
+  - sphinxcontrib-htmlhelp==1.0.3
+  - sphinxcontrib-jsmath==1.0.1
+  - sphinxcontrib-programoutput==0.16
+  - sphinxcontrib-qthelp==1.0.3
+  - sphinxcontrib-serializinghtml==1.1.4
+  - sqlite==3.30.1
+  - svgwrite==1.4
+  - tk==8.6.10
+  - tskit==0.2.3
+  - urllib3==1.25.7
+  - wheel==0.34.2
+  - xz==5.2.4
+  - zipp==3.1.0
+  - zlib==1.2.11
```

**Comment by grahamgower** [comment]
How about doing the conda bits in separate stages? E.g. I tried:

```
/usr/bin/time conda create --quiet --name rtd-test1 --yes python==3.8.2
...
12.19user 3.60system 1:14.30elapsed 21%CPU (0avgtext+0avgdata 323636maxresident)k
47472inputs+454968outputs (18major+229002minor)pagefaults 0swaps
```
And then
```
$ /usr/bin/time conda install --quiet --name rtd-test1 --yes setuptools_scm attrs appdirs msprime sphinx-argparse sphinx-issues sphinxcontrib-programoutput humanize
...
10.77user 7.47system 0:51.58elapsed 35%CPU (0avgtext+0avgdata 222276maxresident)k
```

Sorry, I really don't understand the rtd and yml integration stuff enough to propose a diff.

**Comment by grahamgower** [comment]
Of course, using older versions should also lower memory (e.g. due to fewer dependencies). So maybe pinning python 3.6 would be an even better starting point.

**Comment by jeromekelleher** [comment]
Pinning python 3.6 is a good idea. It probably was when conda-forge added 3.8 that this started breaking... I'll try it out on @petrelharp's branch

**Comment by jeromekelleher** [comment]
Well, I've tried all the combinations of  pinning package versions and we're still running out of memory. I don't really know what to do at this point. We can

- Ask RTD to increase our VM build size (2G is the maximum, apparently)
- Drop sphinxcontrib-programoutput and go back to the old non-conda way of doing it where we mock out msprime's compiled module.

Thoughts?

**Comment by jeromekelleher** [comment]
Others have hit this problem, see eg https://github.com/readthedocs/readthedocs.org/issues/5328

**Comment by grahamgower** [comment]
Can't we install a minimal conda (e.g. just python) and then install more packages in a separate step? That way the peak memory usage is ~ 320mb.

**Comment by jeromekelleher** [comment]
You don't get much control with conda on rtd AFAIK, just the ability to specify the environment file: https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

**Comment by grahamgower** [comment]
Ok. What about installing a minimal conda with gsl (the bit that couldn't be pip installed successfully), and then pip installing the rest?

**Comment by jeromekelleher** [comment]
Can you specify pip in the env file? It's one-or-the-other with RTD.

**Comment by grahamgower** [comment]
No idea. But isn't that what is being done in the `environment.yml` file?

(To digress: I think there needs to be a list of all these `{environment,appveyor,.travis,requirements/rtd-conda-environment}.yml` files somewhere and a short note explaining what they each are for.)

**Comment by jeromekelleher** [comment]
> No idea. But isn't that what is being done in the environment.yml file?

Yes, good call.

**Comment by jeromekelleher** [comment]
OK, I've boiled it down to just installing the msprime package at a pinned version and it's still failing. I don't know WTF conda is doing to use so much memory here.

**Comment by jeromekelleher** [comment]
Progress over in #470. Latest failure [here](https://readthedocs.org/api/v2/build/10784868.txt)

**Comment by grahamgower** [comment]
In my offline tests, I noticed that if I called `conda env create` with stdpopsim's toplevel folder as my working directory, it seemed to parse the `environment.yml` file despite this not being explicitly used in the conda command. (I say "it seemed to" because I got a warning about "pip being used in the environment but not requested as a dependency", which went away when I called `conda env create` from another folder). Maybe there's something funny going on with the environment.yml file?

**Comment by grahamgower** [comment]
Maybe using a conda metachanel is a solution? https://github.com/regro/conda-metachannel

**Comment by petrelharp** [comment]
I think it's time to email rtd or file an issue.

**Comment by petrelharp** [comment]
Whoah I rebuilt it and it worked!!

**Comment by andrewkern** [comment]
how?

**Comment by petrelharp** [comment]
Well, @grahamgower pinned the sphinx version - maybe that fixed it - but also apparently RTD can be unpredictable that way - maybe I happened to click at a low-load time.

**Comment by jeromekelleher** [comment]
Yep, it's [working now](https://readthedocs.org/projects/stdpopsim/builds/10795887/). I'm guessing RTD must have increased our memory limit - we tried pinning all sorts of stuff in #518 and nothing worked. Hopefully this will stick!

**Comment by jeromekelleher** [comment]
And this is [failing again](https://readthedocs.org/projects/stdpopsim/builds/10879949/). Sigh.

**Comment by jeromekelleher** [comment]
Trying to figure out what the correct channel to ask for more memory is. refs

https://github.com/readthedocs/readthedocs.org/issues/4573
https://github.com/readthedocs/readthedocs.org/issues/5215
https://github.com/readthedocs/readthedocs.org/issues/6446

It looks like they do have a way of running these high-resource builds, but there's no documented way of applying for it.

I think the path of least resistance/highest reliability here is to ditch conda. Perhaps we could build a an experimental binary wheel for msprime, and pip install that from some custom location? We should be able to go back to a standard pip install then.

**Comment by grahamgower** [comment]
This stuff is all still very confusing to me (mostly due to lack of documentation from rtd regarding, well, anything), but I've been looking through @petrelharp's attempt to switch from conda to pip. I think this is on the right track. The changes [here](https://github.com/popsim-consortium/stdpopsim/pull/469/files/f845b4e6f566a73c6cb3da1a689dfa661e9f22b4..5b1ba9fc3324e70f002e0f4488f57e5bfcd35812) resulted in [this rtd build failure](https://readthedocs.org/api/v2/build/10781213.txt). The failure is caused by the toolchain not finding gsl headers, and an rtd issue has a [discussion of a similar failure, with potential fixes linked](https://github.com/readthedocs/readthedocs.org/issues/2707#issuecomment-291663591). If I read the build failure and the linked fixes correctly, this would require some small changes to msprime's setup.py.

**Comment by jeromekelleher** [comment]
Building a manylinux binary wheel for msprime sounds easier than working around the lack of GSL on RTD to be honest @grahamgower - I've spent a fair bit of time fiddling with this in the past.

@molpopgen, you've been through the wars here - any thoughts?

**Comment by molpopgen** [comment]
That was my issue that @grahamgower linked to in fact....

The out of memory thing has two causes:  one is that using conda to install dependencies takes a good bit of RAM, and more dependencies means more RAM.  The second cause is random-ish, and due to issues in the RTD infrastructure, some of which have been fixed recently.  The randomness is why @petrelharp was able to manually rebuild and it worked.

To apply for more memory, you file an issue.  I think I've been bumped to 1G maybe a year ago? There's also some way to become a paying supporter, which gives you more resources, too.

As for an mprime wheel, does that imply that GSL is statically linked in somehow?  I've never found a good explanation of how to deal with wheels containing compiled extension modules linked to system libraries.  (Doing this would also be a workaround for that annoying conda issue where GSL is silently linked to openblas (or libblas?) instead of gslcblas, which can be problematic on HPC setups.)

I've had no choice but to stick with conda, as fwdpy11 needs GSL to be built and the examples in the docs are "live" from the sphinx iPython directive.

**Comment by jeromekelleher** [comment]
> As for an mprime wheel, does that imply that GSL is statically linked in somehow? I've never found a good explanation of how to deal with wheels containing compiled extension modules linked to system libraries. (Doing this would also be a workaround for that annoying conda issue where GSL is silently linked to openblas (or libblas?) instead of gslcblas, which can be problematic on HPC setups.)

I think there's been some recent improvements in wheel infrastructure that make putting libraries into the wheel more feasible. I haven't kept up though, and this is a discussion for the msprime repo really. It would be a nice thing to do for 1.0 though, would really help people with installation problems (even if it is inherently icky).

**Comment by grahamgower** [comment]
According to the [rtd docs](https://docs.readthedocs.io/en/stable/builds.html), they currently have a 1 GB limit. I note that the most recent rtd build passed, so the previous failure must have been a transient one. I think we will continue to experience random failures, because conda's memory usage is non-deterministic. Eg. I just tried `for i in $(seq 5) ; do /usr/bin/time conda env create -n foo$i gsl=2.6 ; done` and saw between 400 MB and 450 MB ram being used. Memory use is variable even with pinned versions, but seems lower on average.

What about trying something like the diff below? It should install a conda environment containing just gsl (and dependencies), and then rtd can install everything else in the requirements.txt using pip. I'm unable to trigger an rtd build to test though.

```
diff --git a/.readthedocs.yml b/.readthedocs.yml
index 8253845..cf20318 100644
--- a/.readthedocs.yml
+++ b/.readthedocs.yml
@@ -16,5 +16,6 @@ conda:
 python:
   # Install the local package using pip so that stdpopsim is in the path.
   install:
+    - requirements: requirements/development.txt
     - method: pip 
       path: .
diff --git a/requirements/rtd-conda-environment.yml b/requirements/rtd-conda-environment.yml
index 67f23a9..66bccdb 100644
--- a/requirements/rtd-conda-environment.yml
+++ b/requirements/rtd-conda-environment.yml
@@ -4,11 +4,12 @@ channels:
   - conda-forge
 
 dependencies:
-  - setuptools_scm
-  - attrs
-  - appdirs
-  - msprime
-  - sphinx-argparse
-  - sphinx-issues
-  - sphinxcontrib-programoutput
-  - humanize
+  - _libgcc_mutex=0.1
+  - _openmp_mutex=4.5
+  - gsl=2.6
+  - libblas=3.8.0
+  - libcblas=3.8.0
+  - libgcc-ng=9.2.0
+  - libgfortran-ng=7.3.0
+  - libopenblas=0.3.9
+  - llvm-openmp=10.0.0
```

**Comment by molpopgen** [comment]
> According to the [rtd docs](https://docs.readthedocs.io/en/stable/builds.html), they currently have a 1 GB limit. I note that the most recent rtd build passed, so the previous failure must have been a transient one. I think we will continue to experience random failures, because conda's memory usage is non-deterministic. Eg. I just tried `for i in $(seq 5) ; do /usr/bin/time conda env create -n foo$i gsl=2.6 ; done` and saw between 400 MB and 450 MB ram being used. Memory use is variable even with pinned versions, but seems lower on average.
> 
> What about trying something like the diff below? It should install a conda environment containing just gsl (and dependencies), and then rtd can install everything else in the requirements.txt using pip. I'm unable to trigger an rtd build to test though.
> 
> ```
> diff --git a/.readthedocs.yml b/.readthedocs.yml
> index 8253845..cf20318 100644
> --- a/.readthedocs.yml
> +++ b/.readthedocs.yml
> @@ -16,5 +16,6 @@ conda:
>  python:
>    # Install the local package using pip so that stdpopsim is in the path.
>    install:
> +    - requirements: requirements/development.txt
>      - method: pip 
>        path: .
> diff --git a/requirements/rtd-conda-environment.yml b/requirements/rtd-conda-environment.yml
> index 67f23a9..66bccdb 100644
> --- a/requirements/rtd-conda-environment.yml
> +++ b/requirements/rtd-conda-environment.yml
> @@ -4,11 +4,12 @@ channels:
>    - conda-forge
>  
>  dependencies:
> -  - setuptools_scm
> -  - attrs
> -  - appdirs
> -  - msprime
> -  - sphinx-argparse
> -  - sphinx-issues
> -  - sphinxcontrib-programoutput
> -  - humanize
> +  - _libgcc_mutex=0.1
> +  - _openmp_mutex=4.5
> +  - gsl=2.6
> +  - libblas=3.8.0
> +  - libcblas=3.8.0
> +  - libgcc-ng=9.2.0
> +  - libgfortran-ng=7.3.0
> +  - libopenblas=0.3.9
> +  - llvm-openmp=10.0.0
> ```

This is a good idea.  Try pulling in the conda gcc alias instead of a specific version, too.  See here: https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html

**Comment by jeromekelleher** [comment]
Would you mind doing a PR for your changes @grahamgower? We can merge and try it out for a bit. Since the failures are transient this might do the trick.

**Comment by jeromekelleher** [comment]
#485 and #486 seem to have fixed things for now. Let's see how it goes.

**Comment by grahamgower** [comment]
If problems remain, one last thing we could try is detecting installation from rtd in the `setup.py` (e.g.  `"readthedocs.org" in os.getcwd()`) and in this case add `"sphinx-argparse", sphinx-issues", "sphinxcontrib-programoutput"` to `install_requires`. Then we could get away with not having conda install python at all, saving around 200 MB ram. Its nasty, but should work.
