### ISSUE TITLE
Behaviour of `-v`, `-q`, and the use of print(), logging or warnings

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#473]
I think there's some room for confusion regarding the `-v` and `-q` CLI parameters. And it would also be nice to have a policy/guidelines on the use of `print()`, `logging`, or `warnings` in different cases. Without a clear policy, these are likely to become less coherent over time when more terminal messages get added.

At the CLI, one can request verbose output by using `-v`/`--verbosity` before the species designation. This can be used multiple times to further increase verbosity. In the code, the verbosity flag is linked to the logger level for the `logging` import, and it's also (ab)used in the slim engine to print debug messages when SLiM runs. The use of `logging` messages are sporadic throughout the stdpopsim code base, and it's not clear (to me at least) where logging should be used.

There is also a `-q`/`--quiet` CLI flag that can be used after the species designation to suppress some output. The CLI help says this suppresses the citations, but it also suppresses the "simulation summary" stanza. In the code, this flag directs whether `write_simulation_summary()` and `write_citations()` are called in the `cli.py` module.

In the code, the `warnings` import has been used to print warnings to the user. E.g. when chrX is requested (the default for DroMel!). Personally, I think these warnings are easily lost in the output, at least in part because the warning format is terrible. These warnings cannot be suppressed by the user at the CLI.
```
$ stdpopsim DroMel -o /dev/null -D 10
/home/grg/src/stdpopsim/stdpopsim/species.py:140: UserWarning: Non-autosomal simulations are not yet supported. See https://github.com/popsim-consortium/stdpopsim/issues/383 and https://github.com/popsim-consortium/stdpopsim/issues/406
  warnings.warn(
Simulation information:
    Engine: msprime (0.7.4)
    Model id: PiecewiseConstant
    Model desciption: Piecewise constant size population model over multiple epochs.
    Population: number_samples (sampling_time_generations):
        pop0: 10 (0)
Contig Description:
    Contig length: 23542271.0
    Mean recombination rate: 8.4e-09
    Mean mutation rate: 5.49e-09
    Genetic map: None

If you use this simulation in published work, please cite:
[simulation engine]
  Kelleher et al., 2016: https://doi.org/10.1371/journal.pcbi.1004842
[genome assembly]
  dos Santos et al., 2015: https://doi.org/10.1093/nar/gku1099
[mutation rate]
  Schrider et al., 2013: https://doi.org/10.1534/genetics.113.151670
[population size, generation time]
  Li et al., 2006: https://doi.org/10.1371/journal.pgen.0020166
```

**Comment by jeromekelleher** [comment]
Yep, good call. Perhaps we should use logging for everything? It's the only way to have consistent behaviour I think.

**Comment by grahamgower** [comment]
I do like the idea of setting `logger.captureWarnings(True)`. Maybe we could also tweak the LOG_FORMAT though? For `write_simulation_summary()` and `write_citations()` I don't think we'll want anything prepended to the output.

**Comment by jeromekelleher** [comment]
Sure, tweak away. Consider the current log format an early proposal.
