### ISSUE TITLE
Add a section to the docs on "adding to stdpopsim"

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#480]
It'd be nice to collect all these things in one place? Right now we only have a section on adding demographic models under Development, I think.  Other topics include:

- adding a new species
- adding a new recombination map
- adding a new generic model
- writing tests for new additions.

Even short checklists would be helpful.

**Comment by apragsdale** [comment]
This evening I've been working on a section "Adding a new demographic model" (see #162) that for now I've slotted between the GitHub workflow and Model review process sections in the development docs. It does make sense to have all the different ways of contributing collected together in there.

We could even add

- adding to/improving the existing documentation

to that list :)

**Comment by agladstein** [comment]
I think that's a good idea.

**Comment by agladstein** [comment]
Now that we have a few sections that would belong under this section, I can do some reorganizing of the docs.

**Comment by grahamgower** [comment]
We've got a whole lot of stuff in the [dev docs](https://stdpopsim.readthedocs.io/en/latest/development.html) these days. Anything actionable here that we should think about @petrelharp?

**Comment by petrelharp** [comment]
Looks like we've got all or most of this. Yay! I'll close.
