### ISSUE TITLE
make section on generic models in the catalog?

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#481]
A reviewer suggests that

> I like the inclusion of the "zigzag" history, as well as generic piecewise constant models and IM models (page 7). I wonder if these could be included in a separate section (not organism specific) in the documentation and software (and then in Table 1). Right now the zigzag model is under humans in the catalog.

I think this is a good idea: any objections?

**Comment by jeromekelleher** [comment]
We went back and forth on this. We ended up putting the Zigzag in under humans as that was how it was originally defined. I don't have a strong opinion either way.

**Comment by agladstein** [comment]
there is this hanging PR https://github.com/popsim-consortium/stdpopsim/pull/351

**Comment by agladstein** [comment]
Should this be closed now?

**Comment by andrewkern** [comment]
yeah it should. closing.
