### ISSUE TITLE
Steal sphinx configuration ideas from python.org

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#484]
I've noticed that on python.org, code blocks often have a ">>>" button which toggles visibility of the interactive prompt (e.g. see code blocks [here](https://docs.python.org/3/tutorial/introduction.html#numbers)). As far as I can tell, python.org are just using sphinx like we are, so there must be a way to configure this. So far I didn't stumble upon the correct search terms to figure it out, so I've started looking in the python source distribution...

Lo and behold, [the python source distribution's `Doc` folder](https://github.com/python/cpython/tree/master/Doc) contains a bunch of goodies that we might consider stealing! E.g. [rstlint](https://github.com/python/cpython/tree/master/Doc/tools/rstlint.py
).

**Comment by grahamgower** [comment]
The `>>>` button for code blocks is part of https://github.com/python/python-docs-theme. The easiest way for us to get it, would be to use this theme (it's an additional dependency, but only for developers and rtd). Alternately, the relevant code is a short [javascript file](https://github.com/python/python-docs-theme/blob/master/python_docs_theme/static/copybutton.js) that could be copied into our tree and included in the `extrahead` block of the `layout.html` part of a cusom template, like this: https://github.com/python/python-docs-theme/blob/master/python_docs_theme/layout.html#L41

/me removes detective hat, and leaves the job to someone else

**Comment by jeromekelleher** [comment]
It's a nice feature, but I quite like the rtd theme and I'm sure the catalog rendering would break under a different theme.

Since we're removing the ``>>>`` bits anyway, is there much to be gained?

**Comment by grahamgower** [comment]
I think the `>>>` aids readability. But not being able to copy/paste is a total pain. I can see other projects that have cake and are eating it too, which gives me cake envy!

I found this too:
https://github.com/readthedocs/sphinx_rtd_theme/issues/167
So it should be workable by copy/pasting the `copybutton.js` and adding a line or two into `conf.py`.

**Comment by grahamgower** [comment]
Minimal working diff below. I only tried converting one of the examples in `tutorial.rst`, but it works splendidly.
```
diff --git a/docs/_static/copybutton.js b/docs/_static/copybutton.js
new file mode 100644
index 0000000..f5960d2
--- /dev/null
+++ b/docs/_static/copybutton.js
@@ -0,0 +1,64 @@
+$(document).ready(function() {
+    /* Add a [>>>] button on the top-right corner of code samples to hide
+     * the >>> and ... prompts and the output and thus make the code
+     * copyable. */
+    var div = $('.highlight-python .highlight,' +
+                '.highlight-python3 .highlight,' +
+                '.highlight-pycon .highlight,' +
+                '.highlight-default .highlight');
+    var pre = div.find('pre');
+
+    // get the styles from the current theme
+    pre.parent().parent().css('position', 'relative');
+    var hide_text = 'Hide the prompts and output';
+    var show_text = 'Show the prompts and output';
+    var border_width = pre.css('border-top-width');
+    var border_style = pre.css('border-top-style');
+    var border_color = pre.css('border-top-color');
+    var button_styles = {
+        'cursor':'pointer', 'position': 'absolute', 'top': '0', 'right': '0',
+        'border-color': border_color, 'border-style': border_style,
+        'border-width': border_width, 'color': border_color, 'text-size': '75%',
+        'font-family': 'monospace', 'padding-left': '0.2em', 'padding-right': '0.2em',
+        'border-radius': '0 3px 0 0'
+    }
+
+    // create and add the button to all the code blocks that contain >>>
+    div.each(function(index) {
+        var jthis = $(this);
+        if (jthis.find('.gp').length > 0) {
+            var button = $('<span class="copybutton">&gt;&gt;&gt;</span>');
+            button.css(button_styles)
+            button.attr('title', hide_text);
+            button.data('hidden', 'false');
+            jthis.prepend(button);
+        }
+        // tracebacks (.gt) contain bare text elements that need to be
+        // wrapped in a span to work with .nextUntil() (see later)
+        jthis.find('pre:has(.gt)').contents().filter(function() {
+            return ((this.nodeType == 3) && (this.data.trim().length > 0));
+        }).wrap('<span>');
+    });
+
+    // define the behavior of the button when it's clicked
+    $('.copybutton').click(function(e){
+        e.preventDefault();
+        var button = $(this);
+        if (button.data('hidden') === 'false') {
+            // hide the code output
+            button.parent().find('.go, .gp, .gt').hide();
+            button.next('pre').find('.gt').nextUntil('.gp, .go').css('visibility', 'hidden');
+            button.css('text-decoration', 'line-through');
+            button.attr('title', show_text);
+            button.data('hidden', 'true');
+        } else {
+            // show the code output
+            button.parent().find('.go, .gp, .gt').show();
+            button.next('pre').find('.gt').nextUntil('.gp, .go').css('visibility', 'visible');
+            button.css('text-decoration', 'none');
+            button.attr('title', hide_text);
+            button.data('hidden', 'false');
+        }
+    });
+});
+
diff --git a/docs/conf.py b/docs/conf.py
index f50e425..2b06284 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -203,3 +203,7 @@ todo_include_todos = True
 
 # Github repo
 issues_github_path = "popsim-consortium/stdpopsim"
+
+# Add `>>>` button to toggle visibility of prompts in code blocks.
+def setup(app):
+    app.add_javascript('copybutton.js')

```

**Comment by jurasofish** [comment]
I've made this available as a sphinx extension if you're interested - saves you having to copy the js in manually and works nicely with the sphinx-copybutton extension https://github.com/jurasofish/sphinx-toggleprompt

**Comment by jeromekelleher** [comment]
Very cool, thanks @jurasofish!

**Comment by jeromekelleher** [comment]
I think we can close this @grahamgower, as we're probably aiming to go with JupyterBook at some point?

**Comment by grahamgower** [comment]
Yep.
