### ISSUE TITLE
github alerts

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#488]
Hey, I'm just wondering if anyone knows if there is a way to get alerts from GitHub of certain types of issues.
For example, say you are a new person and want to get involved, can you set it up so you get a ping every time there is an issue tagged as "good first issue". 
Or say you want to be active in the model QC processes, can you get a ping every time there is a new model issue?
I know you can follow a repository and get pinged for all activity, but since this is a pretty active repo, I think that could get overwhelming.

**Comment by jeromekelleher** [comment]
Good idea, but no, I don't know. You can filter things a bit, but not that level of granularity AFAIK

**Comment by agladstein** [comment]
If there is a way to do this, we should add it to the docs. I'll do a little bit of digging on this. Would be nice...

If not, MAYBE we could have a list somewhere of community members who want to pinged for certain things, that you can add yourself to and take off of. That way when someone makes an issue or PR they have an idea of who to ping (if anyone wants to be pinged). That may be a good use of the wiki, or maybe just have a md file in the repo that people can add to via github interface.

**Comment by agladstein** [comment]
Should look into new notifications view with filtering.
