### ISSUE TITLE
how to implement models that have different species parameters

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#501]
In general how should we deal with published models that have parameter estimates that do not match up with species values in stdpopsim.

Concrete example is mutation rate. Parameters in paper could be inferred with a different mutation rate than is used in stdpopsim. mutation rate can effect time estimates and other parameters.

**Comment by apragsdale** [comment]
I agree with the general idea from the call that demographic parameters, if given in physical units in the published paper, should be implemented exactly as reported (as in, we do not do any rescaling). Any rescaling we do I think would just cause confusion for users ("why don't the model parameters match what I expect from the paper??") and issues with backward compatibility if we update a species' recombination rate. I don't know if any of the models currently implemented were inferred using the default mutation rate (at least for humans).

Two possible solutions:
1. Demographic models also are given mutation rate attributes, which could default to the species default if not specified in the model.
2. Like recombination maps, we have a collection of mutation rates for each species, with their appropriate citations, that can be chosen from when simulating. It would make the user think a bit more about what parameters they simulate under (recombination _and_ mutation rates), but that might not be a bad thing.

I like the second option, but maybe it's just extra maintenance and features that we don't want to deal with. But on the other hand, if we're still planning on implementing more complex features like mutation maps or spatially correlated mutation rates, this might be the way to go.

**Comment by agladstein** [comment]
I like option 2.

**Comment by mufernando** [comment]
Do we want to maintain multiple rates for each species or are we satisfied (at least for now) that users can simulate with custom parameters? (see #530, #632)

**Comment by agladstein** [comment]
I think simulate with custom params is probably good.
