### ISSUE TITLE
parameter priors in demographic models

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#503]
Any thoughts on adding a new feature that defines demographic models with priors instead of parameter estimates? This would help with reproducing studies that priors for simulations.

**Comment by jeromekelleher** [comment]
I can imagine defining a distribution for each of the parameters in the models, which we then sample from when running simulations. Would this do it?

**Comment by grahamgower** [comment]
I think this is a duplicate of #299.

**Comment by jeromekelleher** [comment]
Agreed.
