### ISSUE TITLE
QC issue format docs

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#506]
I think it'd be helpful for new model contributors to have a fill in the blank form on the docs for what the model QC issue. Right now, [docs](https://stdpopsim.readthedocs.io/en/latest/development.html#demographic-model-review-process) are a bit loose on this.

I'll make a PR based on the model QC issues that have been submitted.

**Comment by agladstein** [comment]
Can someone with permission create a "model QC" label? Thanks!
Then we can label model QC issues and filter them!

And, if we do that, we can have a model QC issue template! I think that's the way to go!

https://help.github.com/en/github/managing-your-work-on-github/creating-a-label
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

@jeromekelleher

**Comment by jeromekelleher** [comment]
Done! Great idea for Model QC template - want to have a go? You should be able to just create them and open a PR.

**Comment by jeromekelleher** [comment]
How's the colo(u)r for the "Model QC" label? Feel free to suggest another.

**Comment by agladstein** [comment]
> How's the colo(u)r for the "Model QC" label?

LGTM :)

> You should be able to just create them and open a PR.

I don't think I have permission to. I don't have the settings option
<img width="1257" alt="Screen Shot 2020-04-30 at 11 01 21 AM" src="https://user-images.githubusercontent.com/26617086/80726425-5b6f2f80-8ad2-11ea-9a1a-21c7b2b4451a.png">

But, I was thinking something like this (that's what I was going to put in the docs):


**Issue Title:** 
```
QC for <<model_id>> (<<species>>)
```
**Issue comment:**
```
PR for new model: <<link to Pull Request>>
Original paper: <<link to original paper>>
Parameter values: <<reference to where parameter values can be found>>
Population indices: <<description of population indices>>

Potential issues that might lead to differences between the model implementations:
<<description of any potential issues>>

QC'er requests: <<tag potential developers to QC the model>>
```

**Comment by agladstein** [comment]
speaking of permissions... you could give me permission real quick while I do that and then take it away haha
Or someone else can spend 5 min doing that.

**Comment by agladstein** [comment]
Okay, see about https://github.com/popsim-consortium/stdpopsim/pull/507!

**Comment by jeromekelleher** [comment]
Merged - how does it look?

**Comment by agladstein** [comment]
Seems good to me. 
Now if you click "New Issue", you'll see an option for a Model QC template issue. 
Someone else should see what they think. maybe @apragsdale @gtsambos @ndukler?

**Comment by jeromekelleher** [comment]
Cool!

**Comment by agladstein** [comment]
@ndukler had an issue finding the full model in the Gladstein and Hammer 2019 paper (see https://github.com/popsim-consortium/stdpopsim/issues/511). Should we add another prompt in the QC issue format "Full model"?

**Comment by jeromekelleher** [comment]
I'm not clear what you mean by "full model" @agladstein - this is the exact model that was implemented in the original PR? Maybe a heading like "Any further information necessary to identify the exact model implemented" or something?

**Comment by agladstein** [comment]
@jeromekelleher That sounds good to me.
I'm think what @ndukler meant is the topology of the model. Or the exact implementation of the model in the original paper.
I guess there could be prompts for 
"Parameter values", 
"Model diagram (if available in paper)", 
"Section in paper with written description of model", 
"Original code used for specification of the model"  
I thought parameter values and model diagram (that have parameters labeled) are enough to recreate a model, but maybe not. 
@ndukler?

**Comment by ndukler** [comment]
I found it after more carefully re-reading what you wrote. I think this was a problem with me, not the existing setup.

**Comment by agladstein** [comment]
@ndukler haha
I mean, I thought it was obvious, but the setup should make it easy for anybody QC'ing.  We should be able to anticipate "problems with the user" and have a system in place so they are less likely to come up. You not being perfect is an example of how anyone QC'ing will be. So, I think it's better to make more obvious what you didn't find on your first pass.

**Comment by grahamgower** [comment]
Should add a note to "please insert caffienne before attempting QC"?

**Comment by grahamgower** [comment]
I think this was adequately resolved. Please reopen if that's not the case.
