### ISSUE TITLE
issue templates

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#510]
Any other issue templates we want to include?
So far we have 
- Model QC https://github.com/popsim-consortium/stdpopsim/pull/507
- bug report https://github.com/popsim-consortium/stdpopsim/pull/509

Feature request?
maybe something like usage help? for when someone is having issues using stdpopsim, but it's not necessarily a bug.

**Comment by petrelharp** [comment]
There is a feature request in #509 also.

**Comment by agladstein** [comment]
Oh great! I didn't notice.

**Comment by jeromekelleher** [comment]
I think 3 is probably good? We don't want people opening "general support query" issues, and I think bug report and feature request probably cover things we want on the issue tracker.
