### ISSUE TITLE
QC for AshkSub_7G19 (human)

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#511]
**PR for new model:** https://github.com/popsim-consortium/stdpopsim/pull/494
**Original paper:** https://doi.org/10.1093/molbev/msz047
**Parameter values:** Supp Table S3 and Supp Fig S3 of Gladstein and Hammer 2019 
**Population indices:** `YRI, CHB, CEU, M, J, WA, EA = 0, 1, 2, 3, 4, 5, 6`

**Potential issues that might lead to differences between the model implementations:**
The model parameters were inferred with ABC, and because there were so many and we didn't care about all of them, we left a few parameters as "free" parameters and did not infer them. The parameters that were not inferred (and left blank in Table S3) are:
- N_ANC (population size of Africans before reduction). I've taken the parameter value from Gutenkunst et al. 2009 Table 1.
- T_growth (time of population size change in Africa). I've taken the parameter value from Gutenkunst et al. 2009 Table 1.
- Tm (time of gene flow). For simplicity I just put it at one generation before TA
- TAg (time of growth in AJ). For simplicity I just put it at one generation before TAEW

**Comment by grahamgower** [comment]
Is there a volunteer to QC @agladstein's model? I can probably do this, but won't be able to get to it for at least another week. Ping @popsim-consortium/all.

**Comment by ndukler** [comment]
I'll do it before the end of the week

**Comment by ndukler** [comment]
@agladstein Just to clarify because I cannot find the full explicit demographic model in the paper, the model is Gutenkunst 2009 with the additional M, J, WA, EA populations grafted on? And you use all the Gutenkunst parameters for the populations described therein?

**Comment by agladstein** [comment]
The full model and original macs command is given in Table S5.
The model parameters are defined in Supp Table S3 and Supp Fig S3, with the mode as the ABC parameter estimates. 

Here, I am only using the Gutenkunst parameters for N_ANC and T_growth

**Comment by ndukler** [comment]
Ok
