### ISSUE TITLE
SLiM engine

### ISSUE THREAD

**Issue by eps28** [popsim-consortium/stdpopsim#512]
Hi, I've been using SLiM through the SLiMgui but I'm now looking to take advantage of the demographic models already implemented in stdpopsim. I have tried to run stdpopsim with the SLiM engine both from the command line and Python interface but can't get it to work. I keep getting the error that SLiM is not a valid choice of engine and that I should be using msprime instead. If there's any guidance you could give me to help correct this it would be greatly appreciated. I am new to Python so this could very well be the source of my issue.

Thanks

**Comment by petrelharp** [comment]
Hm, sorry to hear it is giving you trouble. Could you post which version of stdpopsim you are using (with `stdpopsim.__version__`), the code you ran, and the error?

**Comment by eps28** [comment]
Thanks for getting back so quickly,
I am using version 0.1.1
Using Python interface:
Code:
>>> engine = stdpopsim.get_engine("slim")
Error message:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/anaconda3/lib/python3.7/site-packages/stdpopsim/engines.py", line 27, in get_engine
    raise ValueError(f"Simulation engine '{id}' not registered")
ValueError: Simulation engine 'slim' not registered

Using Terminal:
Code:
stdpopsim -e slim HomSap -c chr22 -l 0.05 -o foo.ts -d OutOfAfrica_2T12 2 4
Error:
usage: stdpopsim [-h] [-V] [-v] [-c CACHE_DIR] [-e {msprime}]
                 {HomSap,AraTha,EscCol,DroMel,download-genetic-maps} ...
stdpopsim: error: argument -e/--engine: invalid choice: 'slim' (choose from 'msprime')

**Comment by grahamgower** [comment]
Hi @eps28, thanks for your interest in using stdpopsim with the slim engine! The slim engine has only recently been integrated into stdpopsim, and has not yet made it's way into a stdpopsim release (0.1.1 is the latest released version). So right now your choices are, either to wait for the next release, or [use the development version from the git repository](https://stdpopsim.readthedocs.io/en/latest/development.html).

**Comment by grahamgower** [comment]
I'm going to close this issue, @eps28. Feel free to reopen it if you don't feel that this has been resolved.
