### ISSUE TITLE
``download-genetic-maps`` cli broken

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#515]
```
$ python3 -m stdpopsim -vv download-genetic-maps
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jk/work/github/stdpopsim/stdpopsim/__main__.py", line 4, in <module>
    cli.stdpopsim_main()
  File "/home/jk/work/github/stdpopsim/stdpopsim/cli.py", line 619, in stdpopsim_main
    setup_logging(args)
  File "/home/jk/work/github/stdpopsim/stdpopsim/cli.py", line 63, in setup_logging
    if args.quiet:
```

**Comment by jeromekelleher** [comment]
I was going to sort this one out quickly @grahamgower, but it's not obvious how to fix it now that I look. We can add a ``--quiet`` flag at the top level parser (but it's not obvious how this maps to the current quiet/verbose semantics). As I looked at it it's not really clear to me what the quiet/verbose semantics actually are right now. 

What do you think we should do here?

**Comment by grahamgower** [comment]
At the moment, we have -v at the toplevel and -q on the subparser, and the two are not interchangable. Should we just add --verbose and --quiet to the toplevel parser and all subparsers, to cover every combination? That seems messy, but I'm not sure there's another solution which also maintains backwards compatibility.

**Comment by grahamgower** [comment]
Stackoverflow, you life saver... :) https://stackoverflow.com/questions/46962065/add-top-level-argparse-arguments-after-subparser-args

**Comment by jeromekelleher** [comment]
I think it's probably simpler to put -q and -v as top-level options, with the following interpretation. We have a ``verbosity`` variable that defaults to 1. Adding a "-v" increments that. Setting "-q" (which is mutually exclusive to "-v") sets ``verbosity`` = 0.

Verbosity = 0 means : Log level = ERROR
Verbosity = 1 means : Log level = WARNING
Verbosity = 2 means : Log level = INFO
Verbosity = 3 means : Log level = DEBUG

We then map the citation output to WARNING level (which is kind of true, "I'm warning you to cite these papers!"). 

I think this is more-or-less what's there now, right, we're just clarifying the mapping between quiet and verbose?

**Comment by grahamgower** [comment]
That sounds very reasonable. Currently it's possible to simultaneously use -v and -q; are you suggesting to "fix" that in a backwards-incompatible manner? (if so, I vote yes to that change)

**Comment by grahamgower** [comment]
Also, the docs probably use -v as a subcommand parameter.

**Comment by jeromekelleher** [comment]
> That sounds very reasonable. Currently it's possible to simultaneously use -v and -q; are you suggesting to "fix" that in a backwards-incompatible manner? (if so, I vote yes to that change)

Yes, let's make these breaking changes while we can.
