### ISSUE TITLE
URGENT: Non zero migration rates after population merges

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#516]
The issue that was brought up in #496 with regard to non-zero migration rates after population mass migrations is in other models as well. It wasn't caught by QC because it wasn't understood to make a difference. I'm fixing this now in the production models but someone else will have to fix the QC models

**Comment by apragsdale** [comment]
Oh no! Good catch, and I'm glad you thought to look at the other models for this issue. That hadn't occurred to me. I'll have a close look through the QC models to independently try to find any with this problem.

**Comment by ndukler** [comment]
So far I have only seen it once so fingers crossed. I think it's actually one of mine ...

**Comment by petrelharp** [comment]
Ack!! Good catch!

**Comment by jeromekelleher** [comment]
Jeez, good catch @ndukler!

**Comment by ndukler** [comment]
Did you finish your sweep of the QC models @apragsdale? If you did, I'll submit my fix and we can compare.

**Comment by apragsdale** [comment]
I have not. I'll do that this afternoon.

**Comment by apragsdale** [comment]
Ok, I only found one other case of old migration rates not being set to zero, in the homo sapiens Tennessen 2 pop. If you want to submit your fix, we can make sure that everything lines up now.

**Comment by petrelharp** [comment]
Are any of the other models in the paper affected?

**Comment by apragsdale** [comment]
I don't believe so.

**Comment by ndukler** [comment]
I found the same

**Comment by jeromekelleher** [comment]
Great work guys, thanks for going through this. Can we close this issue now?

**Comment by ndukler** [comment]
Sure
