### ISSUE TITLE
Update devdocs to detail data upload to AWS

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#517]
What the title says. (Reminder to self to do this)

**Comment by ndukler** [comment]
@grahamgower @jeromekelleher Is there somewhere in particular I should put this info? I don't see a natural spot in the documentation as it doesn't seem like there's a place where adding a new species/genetic map is documented.

**Comment by grahamgower** [comment]
The "how to add a species" docs don't yet exist. Maybe you could add a placeholder title, with a "TODO", and add your bits as a subsection of this?

**Comment by ndukler** [comment]
Sounds good!

**Comment by ndukler** [comment]
I actually just decided to wrote the docs for implementing a new species. That being said as I've never actually done it they might need some refining.

**Comment by ndukler** [comment]
I also really hate the sphinx `unexpected indentation` error message in the python code blocks. I cannot for the life of me figure out why it's unhappy and sometimes it just goes away after I do random stuff.

**Comment by grahamgower** [comment]
Closed by #534.
