### ISSUE TITLE
Inaccurate parameterization of the Browning America model

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/stdpopsim#519]
Demographic events in the Browning model have timings that are are artificially offset (T_event+0.0001, T_event+0.0002, etc), which I don't think is correct. If this is to ensure that events occur in a specific order, that should be handled just by the order of events in the `demographic_events` list.

**Comment by ndukler** [comment]
Yeah, we ran through this when it was first implemented. The reason that we did it this way was that this was how the model was implemented in the original paper and we wanted to be as faithful to that as possible. See discussion in #62 .

**Comment by apragsdale** [comment]
Oh weird! I thought we added that.. ok, going to close this then, sorry about that.
