### ISSUE TITLE
QC for AraTha

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#539]
The **AraTha** species definition has not yet been QCed!

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [x] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [x] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [x] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [x] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [x] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [x] Recombination map(s) (if relevant).
- [x] Population size.
- [x] Generation time.

**Comment by grahamgower** [comment]
I've recently reviewed some items on this list, and thus they're already checked.

**Comment by jeromekelleher** [comment]
Do you think we can push this back to version 0.1.3 @grahamgower? It'll take a while to get all these QC'd, and I'd like to get 0.1.2 out ASAP.

**Comment by grahamgower** [comment]
Yeah, I guess so. But we really should try to get some eyes on everything soon, so that if we find anything concerning we can push out 0.1.3 in a hurry. Note that there are still comments like this in the code: "Lengths from TAIR 10 although its unclear what reference the genetic map used   -- follow up on this with Salome 2012 authors".

**Comment by jeromekelleher** [comment]
I agree it's not ideal, but we don't *know* there are bugs in the species definitions. We do know that there are bugs in the currently released models, so we shouldn't delay getting a fix out for the models just to be sure that there aren't other problems. As you say, we can push out more 0.1 releases as we need.

**Comment by grahamgower** [comment]
Ok, I changed the milestone.

**Comment by izabelcavassim** [comment]
OK I will be QCing this and creating the tests.

**Comment by grahamgower** [comment]
This one also needs a recombination map lifted over.

**Comment by silastittes** [comment]
Zoom discussion consensus is the genetic map is on an older version of the genome. Haven't found which version yet, but I'm working on this to lift over the genetic map coords based on what chain files are currently available between genome versions on ensembl and what what used in [Salomé et al., 2012](https://doi.org/10.1038/hdy.2011.95).

**Comment by petrelharp** [comment]
This is happening in #1274.

**Comment by petrelharp** [comment]
Closed in #1274, thanks a ton to @silastittes!!
