### ISSUE TITLE
QC for DroMel

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#541]
The **DroMel** species definition has not yet been QCed!

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [x] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [x] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [x] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [x] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [x] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [x] Recombination map(s) (if relevant).
- [x] Population size.
- [x] Generation time.

**Comment by grahamgower** [comment]
I was unable to locate details regarding `population_size=1720600` in the [Li & Stephan](https://doi.org/10.1371/journal.pgen.0020166) citation. This appeared in commit 4e77225f0c52db351e11f0ff29ce8d53128e68e0. @andrewkern can you shed any light on how this number was calculated, or where it came from?

**Comment by grahamgower** [comment]
QC for DroMel is almost done. We still have this strange population size number though. Maybe it was a typo? Thoughts anyone?

**Comment by apragsdale** [comment]
That size is exactly 5x smaller than the reported effective population size of the African population in Li and Stephens (8.603e6). Not sure where the factor of five is coming from though...

**Comment by apragsdale** [comment]
It might be that because the Li and Stephens mutation rate is much lower than other estimates (by a factor of 4 or 5), the reported Ne was ad-hoc scaled by that factor to more closely match expected levels of diversity.

The perils of mix-and-matching parameter values!

**Comment by grahamgower** [comment]
Thanks @apragsdale! The factor of `5` is indeed the key here! Li and Stephan use a two-epoch model of expansion for the African population (`N_A0` and `N_A1`). They report the number `N_A0 = 8.603e6`, and it seems stdpopsim is using `N_A1` (the value for the earlier, pre-expansion, epoch). From Li and Stephan (see final sentence below):

> In the expansion model, the estimated θ_A0 (= 4 N_A0 μ) is 0.0499. θ_A0 is larger than the observed Watterson's θW (0.0126) because the population is not in mutation-drift equilibrium. Since the D. melanogaster lineage split from D. simulans approximately 2.3 million years ago [21] and the averaged divergence over loci is 0.0667,  is 1.450 × 10−9 per site per generation (assuming ten generations per year). Then N_A0 is 8.603 × 106, and the estimated time to the expansion in the past  is 60,000 y with a 95% confidence interval (CI) of 26 to 95 ky. **`The strength of the expansion, measured by the ratio of the current size to the size before the expansion, is 5.0 (3.5 – 8.5).`**

I'll add a comment in the code, and we can close out this QC.

**Comment by andrewkern** [comment]
wait so did I get it right the first time through? 😬

**Comment by grahamgower** [comment]
> wait so did I get it right the first time through?

Ha, yes. :) It just took a while to figure out where you got the number(s) from.
