### ISSUE TITLE
QC for EscCol

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#542]
The **EscCol** species definition has not yet been QCed!

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [x] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [x] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [x] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [x] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [x] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [x] Recombination map(s) (if relevant).
- [x] Population size.
- [x] Generation time.

**Comment by grahamgower** [comment]
I've recently reviewed some items on this list, and thus they're already checked.

**Comment by grahamgower** [comment]
We're using `recombination_rate=0` here, which I guess is ok. But the population size estimate seems ludicrous, in part because it was calculated using a mutation rate that is five orders of magnitude different to the mutation rate we're using to simulate. This seems wildly inconsistent.

Should we remove EscCol? I honestly don't see how this could be useful to anyone in its current form. Any E.coli experts in the audience interested in making this work (#593 might clean some of this up)? Ping @popsim-consortium/all

**Comment by jeromekelleher** [comment]
I think @fbaumdicker brought this in initially - any thoughts?

**Comment by fbaumdicker** [comment]
Yes, I brought this in! I am really convinced we should keep this in. If i remember correctly, @ndukler did the quality control back at the time when this was added. Not sure why this is not recorded in the repo??

In addition, with msprime 1.0 we are now able to include gene conversion instead of recombination = 0 to the model which will make it more realistic and applicable, compared to its admittedly rather simple form today.

Also, I have been in contact with Jean Cury who recently created a bunch of bacterial model recipes for slim, of which some could be added to the stdpopsim. Jean and I think it could be a cool subsection at the hackathon to include more of those bacterial models to stdpopsim. I was planning to suggest this at the next video call, but since this issue came up here I am suggesting it here now.

I suggest keeping EscCol, as it is currently the only representative of microbial populations and will get more applicable and useful soon alongside a bunch of more sophisticated microbial models.

**Comment by grahamgower** [comment]
Ok, great! It's certainly better to have this in, and make it work, than kick it out. But at a minimum, we'll need to have population prameters that can actually be simulated. Right now the mutation rate is `0.00021` and the population size is `1.8e8`, and I run out of ram on my 16GB laptop trying to simulate 10 samples.

**Comment by fbaumdicker** [comment]
How is this possible?? The time and memory to simulate this with msprime should not really depend on the pop_size and the mutation rate. As the recombination rate is zero, all it should do is sample a coalescent for the 10 individuals and put mutations upon it. This should be super fast and taking not much memory. Any ideas what could cause this @jeromekelleher ?

**Comment by grahamgower** [comment]
It's a 5Mb genome, so we have on the order of `5e6 * 1.8e8 * 0.00021 = 1.89e11` mutations, right?

**Comment by apragsdale** [comment]
Those are probably per-genome instead of per-bp mutation rates, so the mutation rate should be `0.0021 / 5e6`. At least the Perfeito et al paper reports the rate as 10^{-5} per genome per generation. So that's a bug in our species implementation.

**Comment by grahamgower** [comment]
Awesome, thanks for spotting that @apragsdale! So my next question is: which genome? Because the K-12 is 4641652 bytes and HUSEC2011 is 5277676 bytes.

**Comment by fbaumdicker** [comment]
You are right @apragsdale. I think the best solution would be to define the per bp per generation mutation rate as 8.9 x 10^-11 as in Wielgoss et al (https://doi.org/10.1534/g3.111.000406.) That way we do not depend on the genome size. Honestly, as we do not have a recombination map for those strains I would just stick to K-12. It is not a big difference once the per bp mutation rate is fixed.  I can create a pull request fixing this next week.

**Comment by grahamgower** [comment]
That looks a bit better!
```
$ time stdpopsim EscCol 10 -o /tmp/a.ts
Simulation information:
    Engine: msprime (0.7.4)
    Model id: PiecewiseConstant
    Model desciption: Piecewise constant size population model over multiple epochs.
    Population: number_samples (sampling_time_generations):
        pop0: 10 (0)
Contig Description:
    Contig length: 4641652.0
    Mean recombination rate: 0.0
    Mean mutation rate: 8.9e-11
    Genetic map: None

If you use this simulation in published work, please cite:
[stdpopsim]
Adrion et al., 2020: https://doi.org/10.7554/eLife.54967
[simulation engine]
Kelleher et al., 2016: https://doi.org/10.1371/journal.pcbi.1004842
[genome assembly]
Blattner et al., 1997: 10.1126/science.277.5331.1453
[mutation rate]
Wielgoss et al., 2011: https://doi.org/10.1534/g3.111.000406
[population size]
Hartl, Moriyama, and Sawyer, 1994: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1206133/
[generation time]
Sezonov et al., 2007: https://doi.org/10.1128/JB.01368-07

real    0m2,887s
user    0m2,717s
sys     0m0,763s
```
```
$ tskit info /tmp/a.ts
sequence_length:  4641652.0
trees:            1
samples:          10
individuals:      0
nodes:            19
edges:            18
sites:            1077679
mutations:        1077679
migrations:       0
populations:      1
provenances:      2

```

**Comment by fbaumdicker** [comment]
awesome!

**Comment by grahamgower** [comment]
QC complete following #593.
