### ISSUE TITLE
QC for HomSap

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#543]
The **HomSap** species definition has not yet been QCed!

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [x] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [x] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [x] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [x] Population size.
- [x] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [x] Genome reference assembly.
- [x] Mutation rate.
- [x] Recombination rate.
- [x] Recombination map(s) (if relevant).
- [x] Population size.
- [x] Generation time.

**Comment by petrelharp** [comment]
Over in #914 I'm finding the recombination rates *don't* match, eg:
```
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[13] - AssertionError: assert 1.0914860554958317e-08 == 1.3082718764398148e-08 ± 1.3e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[14] - AssertionError: assert 1.119730771394731e-08 == 1.3711030325976108e-08 ± 1.4e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[15] - AssertionError: assert 1.3835785893339787e-08 == 1.7197030015823156e-08 ± 1.7e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[17] - AssertionError: assert 1.582489036239487e-08 == 1.5435336515997285e-08 ± 1.5e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[18] - AssertionError: assert 1.5075956950023575e-08 == 1.4647379553777267e-08 ± 1.5e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[21] - AssertionError: assert 1.3045214034879191e-08 == 1.6862572870496712e-08 ± 1.7e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[X] - AssertionError: assert 1.164662223273842e-08 == 1.1793445889048436e-08 ± 1.2e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[20] - AssertionError: assert 1.7178269031631664e-08 == 1.6816238743401626e-08 ± 1.7e-10
FAILED tests/test_HomSap.py::TestGenome::test_recombination_rates[22] - AssertionError: assert 1.4445022767788226e-08 == 2.1066745562340675e-08 ± 2.1e-10
```
... so perhaps that first box should be un-checked.

**Comment by grahamgower** [comment]
Done! But I think these tests are going to be problematic because of the current vagueries associated with calculating rate averages across maps (we've changed how this could work several times in the past 12 months).

**Comment by petrelharp** [comment]
This one is up for grabs - and, it's almost done!

**Comment by grahamgower** [comment]
This one is not so easy, as it requires dealing with recombination map liftovers.

**Comment by petrelharp** [comment]
Ah. Darn it. Well, we've got docs for this: https://popsim-consortium.github.io/stdpopsim-docs/latest/development.html#lifting-over-a-genetic-map

**Comment by saurabhbelsare** [comment]
I've worked with recombination map liftovers before. Happy to work on this.

**Comment by petrelharp** [comment]
Did you get this lifted over, @saurabhbelsare?
