### ISSUE TITLE
docs for species QC

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#548]
Have we decided on a species QC strategy? I see some QC issues have been opened (e.g. https://github.com/popsim-consortium/stdpopsim/issues/544)

If so, is it time to add docs for "Species review process"?
@grahamgower

**Comment by grahamgower** [comment]
Yep! The process is: someone opens an issue using the species QC issue template, and then a volunteer runs through the checklist. For future species additions, this can be a hurdle for the new species PR to be merged.

**Comment by grahamgower** [comment]
Added in #591.
