### ISSUE TITLE
Infrastructure for handling assemblies

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#555]
As we add annotations and recombination maps to `stdpopsim` some will inevitably be built on different assemblies. Currently we have no ability to handle this. 

I think that we should implement an assembly object that contains an:
 - id
 - genome definition
 - citation info

Then modify the existing recombination maps to be tied to a specific assembly id. Furthermore, people should be able to list the assemblies and which recombination maps and annotations are tied to each one. Lastly there will have to be some error checking when people start using some of these things together to ensure that they are all from the same assembly. We'll also have defaults so this is backwards compatible.

This will also require a bit of reorganization of the AWS storage and the addition of the genome definitions there.

**Comment by jeromekelleher** [comment]
I think this is a duplicate of #385 @ndukler?

**Comment by ndukler** [comment]
Yeah, there is a bit more in here than in #385 so I'll just copy the text over and close this.
