### ISSUE TITLE
QC for BosTau

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#559]
**PR for new species:** #558

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [ ] Mutation rate.
- [ ] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [ ] Population size.
- [ ] Generation time.

**Comment by ndukler** [comment]
**PR for new species:** #558
 
 If you volunteer to QC this species, please use the checklist below.
 While this list is intended to be comprehensive, it may not be exhaustive.
 Where relevant, the QC reviewer should identify that parameter values match
 those given in the linked citation(s).
 
 * [ ]  Documented (e.g. comment, docstring) reference assembly/version that is being targeted.
 * [ ]  Number of chromosomes.
   
   * Non-autosomal chromosomes included? Should they be?
 * [ ]  Chromosome lengths.
 * [ ]  Recombination rate.
   
   * This might be genome-wide, or per-chromosome. Both are fine.
   * Check there's a comment describing where it came from, and/or how calculated.
   * From a publication? Check the value(s) match the publication.
   * Calculated somehow? Average over a recombination map? Redo the calculation.
 * [ ]  Mutation rate.
   
   * This might be genome-wide, or per-chromosome. Both are fine.
   * Check there's a comment describing where it came from, and/or how calculated.
   * From a publication? Check the value(s) match the publication.
   * Calculated somehow? Redo the calculation.
 * [ ]  Recombination map (if present).
   
   * Does it match the assembly? Liftover is fine, if clearly stated.
   * Is the description/long_description a good summary of how the map was created?
 * [ ]  Population size.
 * [ ]  Generation time.
 
 For each citation, check:
 
 * Doi link.
 * Is publication a preprint? Is there a peer-reviewed publication instead?
 * Is the year correct.
 * Is the author correct (spelling, accents/ligatures/etc.)
 
 Citations are required for:
 
 * [ ]  Genome reference assembly.
 * [ ]  Mutation rate.
 * [ ]  Recombination rate.
 * [ ]  Recombination map(s) (if relevant).
 * [ ]  Population size.
 * [ ]  Generation time.

**Comment by grahamgower** [comment]
Thanks @ndukler! Looks like the species QC is complete, so I'm going to close this.

**Comment by petrelharp** [comment]
Did you mean to close this, @grahamgower ?

**Comment by grahamgower** [comment]
> Did you mean to close this, @grahamgower ?

Yes, @ndukler's list is actually complete. The top three items are now taken care of by the maintenance infrastructure, and there's no recombination map included in the BosTau definition. I also went through and fixed a couple of things before merging the BosTau PR. More reviewing is always welcome though, so please open a ticket if you notice a problem!
