### ISSUE TITLE
compare checksums for downloaded files (genetic maps, annotations)

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#561]
The GeneticMap class should have a checksum attribute, against which downloaded files are checked. The Annotations class should have this too. Proabably sha256 is appropriate here.
https://docs.python.org/3/library/hashlib.html

**Comment by jeromekelleher** [comment]
Where do we store the checksums @grahamgower? Keep a text file on the server mapping file -> checksum seem like a reasonable option?

**Comment by grahamgower** [comment]
I was thinking more along the lines of just having a developer call `sha256` at the command line, and inserting the hex string in the genetic map definition (next to where the id, url, description, etc. are specified).

**Comment by jeromekelleher** [comment]
That's a much better idea.
