### ISSUE TITLE
engine.simulate() looks like msprime.simulate(), but isn't

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#567]
`engine.simulate()` for the msprime engine is a wrapper around `msprime.simulate()`, so naturally the engine API looks familiar to msprime users. However, we don't support all the parameters msprime supports, which can lead to surpising behaviour (e.g see #565). There are additional msprime parameters we may choose to support, such as `random_seed` and `num_replicates`. But it's unclear if additional parameters should be added for all engines, or just the msprime engine. How much divergence are we willing to accept between the accepted parameter lists for each engine?

Should we unify engine.simulate() to look/behave more like msprime.simulate()? Alternately, should we rename engine.simulate() to reduce potential surprises?

**Comment by jeromekelleher** [comment]
That's a tricky one. We want to be flexible, but not *too* flexible. We also don't want to add unnecessary code... I don't have a strong opinion either way.

**Comment by grahamgower** [comment]
Less code is more in this case, I think. Lets revisit any specific issues as they arise.
