### ISSUE TITLE
Add default synonyms for chromosome names

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#570]
Moving discussion from this [thread](https://github.com/popsim-consortium/stdpopsim/pull/563#discussion_r445637802) in #563 here.

Should we add synonyms for things like MT, chr1, etc to all species even if Ensembl doesn't support it? It's not a big deal to do, I guess, just a bit more manual curation of information in the species files.

**Comment by andrewkern** [comment]
i'm going to close this out, as for the time being we are using Ensembl only and have a handle on their chrom IDs I think. Feel free to reopen.
