### ISSUE TITLE
Replace hg19 version of pyrrho maps with hg38 versions

### ISSUE THREAD

**Issue by ndukler** [popsim-consortium/stdpopsim#573]
Oops, I missed that we are officially on hg38 now. Need to replace hg19 versions with hg38 versions for the new pyrrho maps. Can you send me the hg38 maps @jeffspence ? Sorry for wasting your effort from before. As a note, if you can send me them such that each map is it's own flat tarball (no directory substructure upon extraction), that would be great!

**Comment by jeffspence** [comment]
Sure -- thanks for letting me know.  I'll try to get this to you ASAP.

**Comment by jeromekelleher** [comment]
Thanks @ndukler and @jeffspence!

**Comment by jeffspence** [comment]
@ndukler -- I think I sent you an email, but my email client was a bit touchy yesterday, so let me know if you didn't get it.

**Comment by ndukler** [comment]
I have not received it yet.

**Comment by ndukler** [comment]
I just saw it. We just got power back less than an hour ago (after it being out since Tuesday) but I'll have it up as soon as possible.

**Comment by jeffspence** [comment]
@ndukler, awesome!  Thanks!  Let me know when it's up and i'll submit my PR

**Comment by ndukler** [comment]
Files are up. Ready when you are @jeffspence

**Comment by jeffspence** [comment]
Awesome -- thanks! PR #575 should do the trick!

**Comment by ndukler** [comment]
Closed by #575
