### ISSUE TITLE
finalise the selection API

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#584]
#462 added support for doing single locus selection in a flexible way, and DFEs in an inflexible way. Probably the API for using this will need to change as we demand more, or more complex, features. @jeromekelleher has expressed concern over the location of this code (it currently lives in the `ext` submodule, which is unecessary), and the ExtendedEvents objects.

**Comment by mufernando** [comment]
why do you think the DFE API is inflexible?

**Comment by grahamgower** [comment]
Possibly just a poor choice of words. :) Combining the `MutationType` class with a new `GenomicElementType` class would certainly make it more flexible though.

**Comment by izabelcavassim** [comment]
I agree with @jeromekelleher that the ext module is unnecessary, maybe we could fix this @grahamgower and @petrelharp, before we push the [DFE_class](https://github.com/popsim-consortium/stdpopsim/pull/1002) PR?

**Comment by petrelharp** [comment]
Let's do it in a separate PR.

**Comment by nspope** [comment]
Closed by #1341. Selection-related functions are still living in `ext`, I'll make a new issue to track moving these somewhere more appropriate.
