### ISSUE TITLE
update citation in docs

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#589]
Docs need to be updated to cite the paper.
https://stdpopsim.readthedocs.io/en/latest/introduction.html#citations

**Comment by David-Peede** [comment]
Hi Dr. Gladstein! I have already finished steps 1 and 2 under the "Github workflow" and have done "make" in my "docs" directory. Is the next step to make a topic branch for this specific issue, edit the citation in "introduction.rst" and then submit a pull request?

**Comment by agladstein** [comment]
Yes it is! 
make a topic branch, edit the citation, commit, push to your branch, and submit a pull request.

Comment here if you have any problems with it or need any more guidance.

And if something in the dev docs isn't immediately clear you can make a new issue about that so we can make them better!

**Comment by David-Peede** [comment]
Thank you so much for your guidance Dr. Gladstein! I really appreciate it!

**Comment by agladstein** [comment]
No problem! 
btw, you can call me Ariella
