### ISSUE TITLE
dev docs organization

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#597]
The new docs for "Species review process" added in https://github.com/popsim-consortium/stdpopsim/pull/591 doesn't match the organization of "Demographic model review process".

Currently we have
```
- Development
     - Adding a new species
          - Species review process
     - Adding a new demographic model
     - Demographic model review process 
```

Do we want the review process docs to be a subsection of Adding a new species and Adding a new demographic model, or do we want them to be at the same level? Either way, I think they should have the same organization for species and demographic model.

@grahamgower ?

**Comment by grahamgower** [comment]
Good catch! Hmmm... I think it would be strange to have "species review process" at a higher level, given how short it is. And then there's the "adding a genetic map" section right after it. There's a lot more detail in the "adding a demographic model" section too, so how about we shuffle everything a little bit, and have the following structure?
```
- Development
    - Adding a new demographic model
        - ...
        - Demographic model review process 
    - Adding a new species
        - ...
        - Species review process
    - Adding a genetic map
```

**Comment by agladstein** [comment]
I think that sounds good.
