### ISSUE TITLE
TestGeneticMapDownload.test_download_over_cache() is our slowest test

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#599]
On my system this test takes about 50 seconds, out of 70 seconds for all tests. The test currently downloads and extracts all genetic map files (twice, usually from local cache). Probably we only need to do this for a couple of genetic maps.

**Comment by mufernando** [comment]
Not clear what should be done here?

**Comment by grahamgower** [comment]
If the test succeeds for one or two maps, it seems very unlikely to be problematic for others. After the inclusion of the larger and more numerous Pyrho maps, this test takes a long time for very little gain. And I think the actual presence of the map files is also tested elsewhere. Maybe be could replace the current loop which processes all genetic maps, with a tests for just one map from each of two species?

**Comment by jeromekelleher** [comment]
Yeah, agreed. Probably one map from one species is fine.
