### ISSUE TITLE
write parameter table for BosTau/HolsteinFriesian_1M13

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#606]
The BosTau/HolsteinFriesian_1M13 parameter table for the catalog is missing.
https://stdpopsim.readthedocs.io/en/latest/development.html#write-parameter-table

Needs #601 to be resolved first.

**Comment by gregorgorjanc** [comment]
@grahamgower Do you want to assign this to me?

**Comment by grahamgower** [comment]
Done. Thanks @gregorgorjanc!

**Comment by grahamgower** [comment]
Closed by #809.
