### ISSUE TITLE
slim engine doesn't apply scaling factor in `initializeMutationType()`

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#612]
**Short description of the problem:**
When asking for a `MutationType` with non-zero selection coefficient (e.g. gamma distributed), the selection coefficient is used directly, without scaling by the scaling factor `Q`. Found in discussions with @RasaMukti.

**How to reproduce the problem:**
The DFE example in `docs/selection_example.py` is affected by this bug (but the adaptive introgression example is not).

**Suggested fixes:**
Generate SLiM code that multiplies the selection coefficient in the call to `initializeMutationType()`. This would need to do different things for, e.g. fixed selection-ceof types (`distrubtionType='f'`) versus gamma distributed selection-ceof types (`distributionType='g'`; multiply the mean value by the scaling factor here?).

Ping @petrelharp. Thoughts? Does this fix sound sane in general? (I know you don't like scaling, particularly for non-neutral sims!)

**Comment by petrelharp** [comment]
Well, according to [our documentation](https://stdpopsim.readthedocs.io/en/latest/tutorial.html#sec-slim-scaling-factor):

> A model with selection would need to have selection coefficients multiplied by the factor as well.

Going by that, then: yes, we should multiply all the selection coefficients by something, and as you say, the distributions can be scaled also. For gamma or exponential, we'd multiply the mean; for normal we'd multiply the SD; and for weibull we'd multiply the scale.

And, let's check this makes sense: in the rescaled simulation, one "generation" in fact stands in for Q generations. Now, a mutation with selection coefficient s present in n copies is expected to have `n * (1 + s)^t ~ n exp(st)` copies after `t` generations; let's let T = t/Q be time in the rescaled simulation; so if we let S = sQ be rescaled selection coefficients, then this is maintained: `n * exp(st) = n * (ST)`.  (Some other properties of selection are not conserved, but ah well.)
