### ISSUE TITLE
stdpopsim slack channel

### ISSUE THREAD

**Issue by mufernando** [popsim-consortium/stdpopsim#614]
I think we need a space for more informal conversations/community building in stdpopsim. This cannot be done solely through the mail listserv and GitHub.

Slack is ideal for this, I think!

**Comment by mufernando** [comment]
@agladstein do you have access to the old one so we can revive it?

**Comment by agladstein** [comment]
It's called popsimgroup.slack.com
Here is the invite link https://join.slack.com/t/popsimgroup/shared_invite/zt-i5j1y2ut-Idu4EELImP3Q4_X9DkjHwQ
It expires in 30 days

**Comment by andrewkern** [comment]
awesome! who is the admin? would be great to get our sweet logo in there

**Comment by agladstein** [comment]
No idea.

**Comment by agladstein** [comment]
Who wants to be on call for adding people who request to join?
@andrewkern @petrelharp?

**Comment by andrewkern** [comment]
sure yeah sign us both up 😝

**Comment by petrelharp** [comment]
The admin is Adam Siepel.
