### ISSUE TITLE
add maintenance folder to `flake8` lines in continuous integration checks

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#615]
I think this needs to go in `.circleci/config.yml`. It looks like there are a couple of minor lint things that need fixing in the maintenance folder to go along with this change.

**Comment by platipo** [comment]
Hi @grahamgower, I noticed that the CircleCI configuration can be optimized, do you want me to take over?

**Comment by grahamgower** [comment]
Hi @platipo. Yes, if you think things can be improved, pull requests would be most welcome!
