### ISSUE TITLE
support multiple annotation versions?

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#618]
as we are working to finish #560 the question occurs to me: do we want to support multiple versions of the annotation? 

not sure how much value there is for our project in holding on to too many annotation versions for a given genome but throwing the question out there

**Comment by grahamgower** [comment]
That's a good question... probably not? But enseml releases new versions fairly regularly, so to avoid the burden of frequent maintenance maybe we want to be somewhat conservative about how frequently we update?

**Comment by andrewkern** [comment]
okay that definitely works for me.

**Comment by jeromekelleher** [comment]
I'd say "no" unless we have a compelling reason - we have quite enough complexity to manage as it is. Also agreed on updating the emsembl version (although, a lot of updates seem to be silent as far as we're concerned)
