### ISSUE TITLE
rename master branch to main

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#626]
See, e.g.
https://github.com/tskit-dev/tskit/issues/680
https://github.com/github/renaming

**Comment by andrewkern** [comment]
yeah let's do it

**Comment by grahamgower** [comment]
I'm happy to hold off until github gives us a big easy button to push that makes most of the necessary changes. The second link above suggests that will exist by the end of the year. The other things we'll need to do is are: (1) update references to master in the docs, and (2) advertise the change to users and provide instructions for how users should update their local repositories.

**Comment by grahamgower** [comment]
It might be good to do the master->main rename soonish while the PR queue is quiet. It seems like github hasn't/can't automate this any more than they've already done.

**Comment by jeromekelleher** [comment]
SGTM. Are you happy to take the reigns on this one, or would you like me to do it?

**Comment by grahamgower** [comment]
I don't think there's too much to be done, so I'm happy to do it.
