### ISSUE TITLE
averaged recombination rates for some species are wrong

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#630]
**Short description of the problem:**
Some species definitions (such as `HomSap`) use incorrect per-chromosome recombination rates. I suppose these were calculated using `msprime.RecombinationMap.mean_recombination_rate`. Unfortunately, [msprime versions <= 0.7.4 give an incorrect value](https://github.com/tskit-dev/msprime/issues/844) because they assume the genetic map starts at position 0.

**How to reproduce the problem:**
```Python
$ python
Python 3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime, stdpopsim
>>> msprime.__version__
'0.7.4'

>>> human = stdpopsim.get_species("HomSap")
>>> chr1 = human.get_contig("1", genetic_map="HapMapII_GRCh37")
>>> chr1.recombination_map.mean_recombination_rate
1.1487055306951004e-08

>>> chr22 = human.get_contig("22", genetic_map="HapMapII_GRCh37")
>>> chr22.recombination_map.mean_recombination_rate
1.4466102768915285e-08
```

This is not so much of a problem with chr1.
```
$ head -n 2 ~/.cache/stdpopsim/genetic_maps/HomSap/HapMapII_GRCh37/genetic_map_GRCh37_chr1.txt
Chromosome      Position(bp)    Rate(cM/Mb)     Map(cM)
chr1    55550   2.981822        0.000000

$ tail -n 1 ~/.cache/stdpopsim/genetic_maps/HomSap/HapMapII_GRCh37/genetic_map_GRCh37_chr1.txt
chr1    249218992       0.000000        286.279234

$ python -c "print(286.279234 / (249218992 - 55550) / 100)"
1.1489616281669442e-08
```

But some chromosomes (e.g. human chr22) have a large telomere at the start, and hence the map starts well into the chromosome.
```
$ head -n 2 ~/.cache/stdpopsim/genetic_maps/HomSap/HapMapII_GRCh37/genetic_map_GRCh37_chr22.txt
Chromosome      Position(bp)    Rate(cM/Mb)     Map(cM)
chr22   16051347        8.096992        0.000000

$ tail -n 1 ~/.cache/stdpopsim/genetic_maps/HomSap/HapMapII_GRCh37/genetic_map_GRCh37_chr22.txt
chr22   51229805        0.000000        74.109562

$ python -c "print(74.109562 / (51229805 - 16051347) / 100)"
2.106674544972949e-08
```

**Suggested fixes:**
Check which species definitions are affected, and fix accordingly.
Also see discussion of recombination rate calculations [over here](https://github.com/popsim-consortium/stdpopsim/issues/540#issuecomment-711139517).

**Comment by nspope** [comment]
Fixed this for HomSap, using the liftover to HapMapII_GrCh38. If this is comes up for other species, we'll make new issues.
