### ISSUE TITLE
Unnecessary dependencies in setup.py

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#636]
Looks like we pulled in dependencies on scikit-allel in setup.py in #560. This (and any others we don't need for actual sims) should be removed.

I don't think we need scikit-allel here either, as normal stdpopsim users won't run the maintenance code.

_Originally posted by @grahamgower in https://github.com/popsim-consortium/stdpopsim/pull/560#r504176087_

**Comment by andrewkern** [comment]
ack my bad. i'll get right of this.

**Comment by jeromekelleher** [comment]
What about pandas, are we using this in production code?

**Comment by andrewkern** [comment]
yeah we are using this right now to read in annotations and put them in a table. we *may* migrate that over to `pyrange` objects.

**Comment by grahamgower** [comment]
Pyrange objects are a thin wrapper around pandas anyway. Certainly we could get away with not using pandas/pyranges at all if that was desirable. E.g. pandas dataframes don't give us anything we couldn't do with numpy recarrays; and pyranges uses ncls, which we could just use directly, as it works fine for numpy arrays and doesn't depend on anything other than cython and numpy.
