### ISSUE TITLE
question about species QC process

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#639]
I noticed that the dog generation time in the catalog isn't cited. I then went to check it's species QC and see that the species QC is still on going.
So, now I'm confused... are we merging species in before they get QC'd? or was that a one time thing because @grahamgower merged it in himself?

**Comment by grahamgower** [comment]
None of the species were formally QCed at the time that was merged. No, I'm not special. :) You'll also see QC issues remain open for a bunch of species!

**Comment by agladstein** [comment]
Okay cool. So, these original species were never formally QC'd before they were added. But, going forward species will be QC'd and then merged?

**Comment by grahamgower** [comment]
Yep. Given how many issues I found looking through the original set of species, I am firmly in favour of a formal QC process for all new species (and any new catalog-kinda-things).
