### ISSUE TITLE
add a new template for user help?

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#655]
@agladstein raised the issue of starting a "user help" Issues template during todays workshop.

**Comment by jeromekelleher** [comment]
Well there's the perennial question about whether we should do user support like this here on GitHub or we should try to set up some tags on biostars which people monitor. It'll be really hard to keep the issue tracker meaningful as a way of developing the software if it becomes a destination for user support.

**Comment by agladstein** [comment]
Unfortunately, I already said in the workshop to post a GitHub issue... but, we can still change it if we don't want users to do that. But, we should decide what we want and set it up soon.

If we can keep tags organized, then I don't think it would be too messy on GitHub... But, I also think it's fair to point users to a different public and persistent place to post questions.

**Comment by jeromekelleher** [comment]
Something to discuss at the meeting today I think - we really should just get the biostars tags set up I think.

**Comment by grahamgower** [comment]
We have GitHub "discussions" now. But most folks seem to be using the PopSim slack channel.
