### ISSUE TITLE
rename stdpopsim.ext.ExtendedEvents to ...SLiMEvents

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#656]
Also rename `extended_events` variables to `slim_events`. This more properly reflects what the events are and how they're used. Suggested by @petrelharp.

**Comment by jeromekelleher** [comment]
Agreed!

**Comment by nspope** [comment]
@grahamgower and @petrelharp, do you still prefer this naming scheme? I think we should settle on one or the other before the upcoming release.

**Comment by petrelharp** [comment]
Sounds good to me - but, I'm also voting to keep these out of the public API anyhow.

**Comment by nspope** [comment]
Decided to keep these as "ExtendedEvents" in #1341. The rationale is that we may support sweeps down the road in the msprime engine, but would likely still be using these "Event" classes to define single site mutation models.
