### ISSUE TITLE
error if convert_to_substitution=True for a DrawnMutation

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#658]
One can specify that SLiM should set `convertToSubstitution=F` for a mutation type, using the `convert_to_substitution` attribute of `stdpopsim.ext.MutationType`. ~~Substitutions do not appear in the tree sequence file, so the `convertToSubstitution` option dictates whether a mutation appears in the final tree sequence, or not, on the event that the mutation becomes fixed.~~

It seems unlikely that a user will want this set to true (the default) if they are going to draw a mutation of this type with `stdpopsim.ext.DrawMutation`. We should probably have a warning if `convert_to_substitution == True` for the mutation type of a drawn mutation.

**Comment by petrelharp** [comment]
I believe substitutions *do* appear in the tree sequence?

**Comment by grahamgower** [comment]
> I believe substitutions _do_ appear in the tree sequence?

Ah, you're right! I should read the docs instead of guessing the behaviour! But I think the warning should be inserted anyway, for a different reason. We need the mutation to remain in the simulation for allele frequency conditioning---if the mutation is converted to a substitution, then we can't calculate its allele frequency by calling `sim.mutationFrequencies()`.

**Comment by grahamgower** [comment]
Actually, it should be an error instead, since the simulation will be unlikely to match the intended behaviour. And maybe we shouldn't expose `convert_to_substitution` in the API at all?

**Comment by petrelharp** [comment]
I'll close it; re-open if you disagree, Graham.
