### ISSUE TITLE
#CHROM in vcf file

### ISSUE THREAD

**Issue by pc-emory** [popsim-consortium/stdpopsim#694]
Hi,

Not sure if it's a mistake on my part, but when I try to run the basic commands, the vcf file always has '1' in the #CHROM field. For example (from the docs):

> stdpopsim HomSap -c chr22 -o foo.ts 2
> tskit vcf foo.ts > foo.vcf

The vcf file is:

##fileformat=VCFv4.2
##source=tskit 0.3.2
##FILTER=<ID=PASS,Description="All filters passed">
##contig=<ID=1,length=51304566>
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  tsk_0   tsk_1
1   1343    .   0   1   .   PASS    .   GT  1   0
1   1614    .   0   1   .   PASS    .   GT  1   0
1   1768    .   0   1   .   PASS    .   GT  0   1
1   1977    .   0   1   .   PASS    .   GT  0   1
1   4175    .   0   1   .   PASS    .   GT  0   1

Shouldn't the first column say chr22? Or did I miss an option?

thanks!

**Comment by jeromekelleher** [comment]
Thanks for the report @pc-emory, this is a great point.

There's no information about chromosome names stored in the simulated tree sequence currently @pc-emory, so we revert use the default ``contig_id`` of "1" in the [write_vcf](https://tskit.readthedocs.io/en/latest/python-api.html#tskit.TreeSequence.write_vcf) function. 

So, you can change the contig name using the Python API, but there's no way to do it from the CLI currently. I've opened an issue on the tskit repo to track this: https://github.com/tskit-dev/tskit/blob/main/python/tests/test_cli.py

In terms of automatically detected the "right" contig_id for the VCF, we would need do some standardisation in the metadata, and we're a ways away from that at the moment.

**Comment by pc-emory** [comment]
Thanks!

**Comment by jeromekelleher** [comment]
Since this isn't something we can resolve in stdpopsim at the moment I'm going to close the issue.
