### ISSUE TITLE
update msprime mutation step in the SLiM engine

### ISSUE THREAD

**Issue by mufernando** [popsim-consortium/stdpopsim#698]
As of msprime 1.0, you can use a SLiM mutation model to add the neutral mutations. There is one kink to figure out: we need to specify a mutation type, but I'm not sure if we should always add a new type on top of all the existing. This could be confusing because the returned tree sequence would have more types than were specified by the user. We could always require that a neutral type be defined (the first in the list) and that will be used when overlaying mutations with msprime.

further, we should probably update to use `sim_mutations`, and we can't forget to set `kept_mutations_before_end_time=True`

related to #644

**Comment by grahamgower** [comment]
Can this be closed now @mufernando, or does something still need to be changed?

**Comment by mufernando** [comment]
I think this can be closed, but it wouldn't hurt for @petrelharp to take a look at this:

https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/slim_engine.py#L1263

**Comment by petrelharp** [comment]
It looks good to me. The conclusion was to [add a new mutation type](https://github.com/popsim-consortium/stdpopsim/blob/de8c2150b4f569b6a3ed1bd7d6d9d2e12b02ba82/stdpopsim/slim_engine.py#L1314), it looks like - is that as you expect?

**Comment by mufernando** [comment]
I guess that seemed the least bad option, though I haven't documented that anywhere.

I thought that was the least bad option. We could look for a mutation type that is neutral and reuse it in the overlay/recapitation, but these could be being tracked by the user in their extended events. Also it might be useful to want to subset the mutations added with msprime vs within SLiM.

**Comment by grahamgower** [comment]
Sounds good! I can't think of any immediate downside to using a new mutation type.
