### ISSUE TITLE
modify DrawMutation and ConditionOnAlleleFrequency API

### ISSUE THREAD

**Issue by mufernando** [popsim-consortium/stdpopsim#699]
The DrawMutation and ConditionOnAlleleFrequency API does not mesh super well with recent changes to the SLiM engine API (#644). 

What is most weird about these is that they can use a MutationType that is not associated to any GenomicElementTypes. So we should move those to live within `Contig` and provide better user interface in `Contig` to deal with mutation types.

**Comment by nspope** [comment]
I think this is resolved by #1306 @mufernando? In that we're now working with "single sites" with string IDs rather than requiring that the user manually pull out the mutation type id to supply to the extended events. Also related is #1329.

**Comment by mufernando** [comment]
yep!
