### ISSUE TITLE
CicleCI should use a pinned version of SLiM

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#708]
SLiM 3.5 just got released, and this broke CircleCI tests for an unrelated PR (presumably the issue here is that pyslim must be updated *before* updating SLiM).
https://app.circleci.com/pipelines/github/popsim-consortium/stdpopsim/1611/workflows/cf56e409-1157-4ca1-91dc-1d8283c760c7/jobs/2681

We currently have CI using pinned versions of almost everything. This avoids problems whereby an upstream dependency releases a new version which breaks our builds. And for pip-installable dependencies, @dependabot will open a PR to bump the version shortly after the new release occurs. So, great! The potential build failures are isolated and we also get notified about them.

However... We also have SLiM as a dependency, and it's not pip-installable. We should pin the version (it currently is in github actions, but not in CircleCI). Unfotunately we then won't get notified about potential problems with newer versions. (Note that SLiM is conda-installable, but dependabot doesn't know about conda requirements files, which have a subtly different format to pip requirements files).

**Comment by jeromekelleher** [comment]
Closed in #777 (pinned to 3.5)
