### ISSUE TITLE
Review externally documented Python API

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#714]
#710 made it clear that people are writing code against the Python APIs that we document. We should be very careful about what is actually documented and not, as this is a contract for long-term support and will significantly limit our ability to refactor and develop the code.

As a general principle, we should only document APIs that we're happy will be stable for 5 years or more. We should review the current Python documentation and take out any classes etc that aren't necessary for the core workflow of (a) get a species; (b) get a contig; and (c) run a simulation.

**Comment by petrelharp** [comment]
I think we're good here?
