### ISSUE TITLE
too low mutation rate in low recombination regions when using HapMap

### ISSUE THREAD

**Issue by fbaumdicker** [popsim-consortium/stdpopsim#716]
There might be a problem with zero recombination areas that affects the number of mutations in this area.

I am trying to simulate a constant population with constant mutation rate for chromosome 9 of homo sapiens.
(But the same issue occurs e.g. in chromosome 1)
When I am using the HapMapII_GRCh37 recombination map the mutation rate in the low recombination area is no longer correct.
I am not sure if this is an issue solely of stdpopsim or already occurs in msprime.

The following drop in the mutation rate should not occur:

![average_num_mutations_along_chr](https://user-images.githubusercontent.com/13665835/101919827-54151600-3bcb-11eb-8a93-797584dfd437.png)
![recombination_rate_along_chr](https://user-images.githubusercontent.com/13665835/101919861-5d9e7e00-3bcb-11eb-8eaa-7400d3240eab.png)

This is how I produced the upper figure:

```python
import numpy as np
import scipy.stats
import stdpopsim
import matplotlib.pyplot as pyplot

species = stdpopsim.get_species("HomSap")

#lower mutation rates in low recombination region
contig = species.get_contig("chr9", genetic_map = "HapMapII_GRCh37")
#contig = species.get_contig("chr1", genetic_map = "HapMapII_GRCh37")

#normal mutation rates in low recombination region
#contig = species.get_contig("chr9", genetic_map = "PyrhoCEU_GRCh38")

model = stdpopsim.PiecewiseConstantSize(species.population_size)

num_samples = 40

samples = model.get_samples(num_samples)
engine = stdpopsim.get_engine("msprime")

ts = engine.simulate(model, contig, samples, seed = 42)


mut_positions = np.empty(ts.num_mutations)
for i, variant in enumerate(ts.variants()):
    mut_positions[i] = variant.position

num_bins = 2000
s, mut_bin_edges, _ = scipy.stats.binned_statistic(
    mut_positions, range(ts.num_mutations), bins=num_bins, statistic='count')

fig, ax1 = pyplot.subplots(figsize=(16, 6))
ax1.plot(s, color="red")
ax1.set_ylabel("number of mutations")
ax1.set_xlabel("Chromosome bin")
fig.savefig("average_num_mutations_along_chr")
```

**Comment by jeromekelleher** [comment]
Interesting, thanks for the report @fbaumdicker. One question: is this robust to different random seeds? I'm wondering if there just happens to be a tree with very recent TMRCA crossing the centromere here.

**Comment by fbaumdicker** [comment]
Stupid me! That might be the case. Let me check.

**Comment by fbaumdicker** [comment]
Everything is fine here. I got just confused because the behavior of the recombination maps "HapMapII_GRCh37" and "PyrhoCEU_GRCh38" is so different in this region. Maybe this just means we don't know the recombination rate in this region.
What are people doing with this data normally? Is the variation around the centromere ignored?

**Comment by petrelharp** [comment]
I think that everything being messed up near centromeres is normal....

**Comment by petrelharp** [comment]
I think that everything being messed up near centromeres is normal....
