### ISSUE TITLE
QC for OutOfAfrica_4J17 (HomSap)

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#733]
**PR for new model:** #726
**Original paper:** https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5500150/
**Parameter values:** table 4 in the main text.
**Population indices:** YRI=0, CEU=1, CHB=2, JPT=3

**Potential issues that might lead to differences between the model implementations:**
Nothing known apriori.

**Comment by jeffspence** [comment]
I'll work on QCing this model.  I'll shoot to be done by 5/16/22

**Comment by jeffspence** [comment]
I'll QC this model.  I'll get to it on or before 5/16/22
