### ISSUE TITLE
Pyrho genetic map error

### ISSUE THREAD

**Issue by David-Peede** [popsim-consortium/stdpopsim#734]
**Genetic map 'HomSap/Pyrho"POP"_GRCh38' not in catalog**
I am trying to specifically load the PyrhoMXL_GRCh38 gentic map, but I keep on receiving a `not in catalog` error. I tried other Pyrho maps and received the same errors, however, I did not get any errors when loading DeCodeSexAveraged_GRCh36 or HapMapII_GRCh37. 

**How to reproduce the problem:**
`contig = species.get_contig("chr6", genetic_map="PyrhoMXL_GRCh38")`
`Traceback (most recent call last):`
  `File "<stdin>", line 1, in <module>`
  `File "/users/dpeede/anaconda/stdpopsimenv/lib/python3.9/site-packages/stdpopsim/species.py", line 154, in get_contig
    gm = self.get_genetic_map(genetic_map)`
  `File "/users/dpeede/anaconda/stdpopsimenv/lib/python3.9/site-packages/stdpopsim/species.py", line 191, in get_genetic_map
    raise ValueError(f"Genetic map '{self.id}/{id}' not in catalog")`
`ValueError: Genetic map 'HomSap/PyrhoMXL_GRCh38' not in catalog`

**Comment by grahamgower** [comment]
Works for me. These maps were only added after the last stable release of stdpopsim. Are you sure you're running stdpopsim from the HEAD of the master branch?

```
$ python -m stdpopsim -V
__main__.py 0.1.3.dev153+g6774997
```
```
$ python -m stdpopsim HomSap -c 22 -g PyrhoMXL_GRCh38 10 > /tmp/a
Simulation information:
    Engine: msprime (0.7.4)
    Model id: PiecewiseConstant
    Model desciption: Piecewise constant size population model over multiple epochs.
    Population: number_samples (sampling_time_generations):
        pop0: 10 (0)
Contig Description:
    Contig length: 50818468.0
    Mean recombination rate: 7.869382127398365e-09
    Mean mutation rate: 1.29e-08
    Genetic map: PyrhoMXL_GRCh38

If you use this simulation in published work, please cite:
[stdpopsim]
Adrion et al., 2020: https://doi.org/10.7554/eLife.54967
[simulation engine]
Kelleher et al., 2016: https://doi.org/10.1371/journal.pcbi.1004842
[genome assembly]
International Human Genome Sequencing Consortium, 2001: http://dx.doi.org/10.1038/35057062
[mutation rate]
Tian, Browning, and Browning, 2019: https://doi.org/10.1016/j.ajhg.2019.09.012
[recombination rate]
The International HapMap Consortium, 2007: https://doi.org/10.1038/nature06258
[genetic map]
Spence and Song, 2019: https://doi.org/10.1126/sciadv.aaw9206
[population size]
Takahata, 1993: https://doi.org/10.1093/oxfordjournals.molbev.a039995
[generation time]
Tremblay and Vézina, 2000: https://doi.org/10.1086/302770
```

```
$ python
Python 3.9.1 (default, Dec 13 2020, 11:55:53)
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stdpopsim
>>> stdpopsim.__version__
'0.1.3.dev153+g6774997'
>>> species = stdpopsim.get_species("HomSap")
>>> contig = species.get_contig("chr6", genetic_map="PyrhoMXL_GRCh38")
>>>
```

**Comment by David-Peede** [comment]
I am not on the developer version, I made a separate conda environment. I even tried to update the stdpopsim package itself and am still on version 0.1.2.

**Comment by David-Peede** [comment]
Hi @grahamgower it worked fine once I switched to the developer version, but if I am using stdpopsim for personal projects (and not for development purposes) is it ok to use the development version?

**Comment by jeromekelleher** [comment]
There's a "use at your own risk" warning if you do use the developer version @David-Peede ... stuff may break. We generally don't recommend "normal" users to work from GitHub, but, I think you graduated from normal user status a while back :wink:
