### ISSUE TITLE
kwargs for `simulate` functions

### ISSUE THREAD

**Issue by awohns** [popsim-consortium/stdpopsim#735]
I recently noticed that there's no option to set `record_migrations=True` when using `simulate()`.

Since this might be an issue if people want to use other options such as `record_full_arg `, I propose we use **kwargs with engine.simulate(), which would then be passed to the slim and msprime engines.

I'm happy to implement this if others agree it's a good idea!

**Comment by jeromekelleher** [comment]
Seems OK to me, once users are aware that extra kwargs might not work across different engines.

@grahamgower?

**Comment by grahamgower** [comment]
Closed by #736.
