### ISSUE TITLE
drop support for Python 3.6

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#738]
Python 3.6 will reach end of life this year. Msprime has just dropped 3.6, and we'll soon be moving to msprime 1.0, so it makes sense for stdpopsim to drop support too.

**Comment by jeromekelleher** [comment]
It's probably not worth doing the attrs -> dataclasses conversion, I think? Not much to be gained and likely quite a bit of work as we're using attrs specific functionality.

**Comment by grahamgower** [comment]
Yeah, I don't see any reason to stop using attrs. At least, that change would be orthogonal.
