### ISSUE TITLE
Error in description of four population out of africa model

### ISSUE THREAD

**Issue by awohns** [popsim-consortium/stdpopsim#757]
4 population out of africa lists "Epoch Time (generations)"  for the times of events. These should be "Epoch Time (thousands of years)". Confirmed that this is the case by looking at original paper: https://academic.oup.com/genetics/article/206/3/1549/6064248#222786736. Implementation looks correct though.

**Comment by grahamgower** [comment]
Nice catch, thanks @awohns. This model was only recently added, and as such it does not yet have a QC reimplementation (#733). Perhaps you'd be interested in adding this? https://stdpopsim.readthedocs.io/en/latest/development.html#so-the-model-is-implemented-what-next

**Comment by awohns** [comment]
Sure! sounds good to me, thanks @grahamgower

**Comment by grahamgower** [comment]
Closed by #918.
