### ISSUE TITLE
merge the msprime-1.0 feature branch into main

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#776]
Should be fairly straight forward to do this once #775 goes in.

**Comment by jeromekelleher** [comment]
@mufernando - I think the main changes in that branch are yours. Do you think we can make a PR to bring the changes into main now?

**Comment by grahamgower** [comment]
I'm planning to have look at merging this later today.

**Comment by mufernando** [comment]
thanks, @grahamgower!
