### ISSUE TITLE
Run unittest2pytest on suite

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#778]
After #777, we should make the minimal automatic changes needed to update the test suite. Looks like [unittest2pytest](https://github.com/pytest-dev/unittest2pytest) is a good option for this.

@grahamgower, should we wait until #776 is done first?

**Comment by grahamgower** [comment]
Cool! Yes, probably best to wait for #776.

**Comment by jeromekelleher** [comment]
Can I assign this to you? Having a bit of a CI heavy morning here.

**Comment by grahamgower** [comment]
> Can I assign this to you? Having a bit of a CI heavy morning here.

Sure. I'm unlikely to get to it in the next few days though.

**Comment by jeromekelleher** [comment]
No hurry, I'd imagine.
