### ISSUE TITLE
Refactor catalog code into submodules

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#785]
The ``__init__.py`` file in the catalog subpackages currently contains a lot of code, which will confuse contributors I think. It would be better if this was split into separate files, .e.g., ``__init__.py`` would become

```
from . import genome
from . import genetic_maps
from . import annotations
from . import demographic_models
```
This would probably help contributors see where their code is supposed to go and make things less confusing.

Thoughts @grahamgower? It's not hard to do, just a bit of file rejiggering.

**Comment by grahamgower** [comment]
Please do! That's much nicer!
