### ISSUE TITLE
update validation.py after demography API changes

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#786]
#764 made changes to the `DemographicModel` class, which very likely breaks the `validation.py` script.

**Comment by nspope** [comment]
@silastittes do you have time to look at this? I think someone just needs to check if `validation.py` runs, and investigate if not.

**Comment by petrelharp** [comment]
I'm running it (after that fix). Could you post its output here? (i.e., the `plots/`)

**Comment by silastittes** [comment]
Yes, but output is on talapas which is down for maintenance. Made a reminder in my calendar to post!

**Comment by silastittes** [comment]
Here's the output on my end.
[plots.tar.gz](https://github.com/user-attachments/files/17080139/plots.tar.gz)

**Comment by petrelharp** [comment]
Is that before or after the correction I made here?

**Comment by petrelharp** [comment]
(I was running these on my laptop but didn't realize how long it would take; I killed it after like half a day.)

**Comment by silastittes** [comment]
This is before. I assumed the goal was comparing before and after? 
Yes takes a while end-to-end!

**Comment by petrelharp** [comment]
I think what we should be doing is checking that validation still looks good after this PR - so, it should be 'after'? If it doesn't look good, probably that would be due to some other change somewhere else, rather than this PR, but this is still the place to validate.

**Comment by petrelharp** [comment]
Well, actually - those plots look reasonable; the only deviations I see is that there are fewer edges and nodes in rescaled SLiM simulations than msprime, which is I think not unexpected (due to the rescaling). I didn't even see the effect of the error which I fixed, but again that seems believable. I'll merge that. Thanks!
