### ISSUE TITLE
add .gitignore file

### ISSUE THREAD

**Issue by grahamgower** [popsim-consortium/stdpopsim#811]
I'm sure there's a sensible list of things to go in here for a python project. Or just copy some stuff from msprime or tskit.

**Comment by jeromekelleher** [comment]
Good call. Github does default ones AFAIK

**Comment by grahamgower** [comment]
https://github.com/github/gitignore

**Comment by jeromekelleher** [comment]
Probably good to just add this in asap @grahamgower, as it'll help us over the next few days.

**Comment by grahamgower** [comment]
Fixed already by #827.
