### ISSUE TITLE
Heliconius Melpomene

### ISSUE THREAD

**Issue by Vcaudill** [popsim-consortium/stdpopsim#835]
- **Heliconius melpomene:** scientific name of the species
- **Postman butterfly:**

**Description:** These butterflies are found in central and South America. There is no crossover during meiosis in females
[info](https://academic.oup.com/genetics/article/171/2/557/6060659?login=true)

**Demographic information:**

- [9.5/100] generation time in years: 35 days [Pardo-Diaz](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002752#pgen.1002752-Wahlberg1) They used this values in their demographic calculations  
- [2111109] "default" population size [Pardo-Diaz](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002752#pgen.1002752-Wahlberg1) Isolation with Migration model estimated a population size 

**Chromosome structure:**

- [[Heliconius_melpomene](https://metazoa.ensembl.org/Heliconius_melpomene/Info/Annotation/)] ensembl assembly ID 21 chromosomes 

**Recombination rates:**

- [[Table 3 has recombination rates by chromosome]](https://onlinelibrary.wiley.com/doi/full/10.1002/evl3.12) genetic map of recombination rates (as a hapmap or csv file)
- [] genome-wide mean recombination rate (which will be used as the default)

**Mutation rate:**

- [[2.9e-9]](https://academic.oup.com/mbe/article/32/1/239/2925597?login=true) genome-wide mean mutation rate
It is similar to "recent estimates in Drosophila melanogaster"

**Demographic model:**

- [] [Pardo-Diaz](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1002752#pgen.1002752.s005) estimates migration rates a list of population sizes, growth rates, migration rates, etcetera. **(optional)**
- [] [Paper about Inversion](https://onlinelibrary.wiley.com/doi/full/10.1002/evl3.12)
- [] [Genetic Linkage map](https://academic.oup.com/genetics/article/171/2/557/6060659?login=true)
- [] [Cool info about population structure](https://academic.oup.com/genetics/article/203/1/525/5930346?login=true)

**Other information:**

These are things we don't currently use, but will want to use in the future:

- [ZW] sex determination system, and which chromosomes are the sex chromosome(s)
- [diploid] ploidy

**Comment by percyfal** [comment]
The recombination maps in [Davey et al](https://onlinelibrary.wiley.com/doi/full/10.1002/evl3.12) are based on Heliconius assembly Hmel2 (http://ensembl.lepbase.org/Heliconius_melpomene_melpomene_hmel2/Info/Index). Hmel1 (the ensembl version) consists of ~1700 scaffolds assigned to chromosomes, but the stdpopsim maintenance script returns an empty chromosome table. It seems though that there is no REST interface for Hmel2.

**Comment by petrelharp** [comment]
You can go ahead and add Heliconius with Hmel2 - just enter the chromosome length information manually (and put in the comments what you're doing). We'll need to generalize our maintenance scripts to deal with this (see #850) but we can do that down the road after we've got a few more examples.

**Comment by grahamgower** [comment]
Closed by #870.
