### ISSUE TITLE
Incorrect citation information for Browning American Admixture model

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/stdpopsim#841]
The demographic model for American admixture from Browning et al has the id "AmericanAdmixture_4B11" and the year is given as 2011. But this is a 2018 paper that is based on the Gravel et al 2011 model (which is maybe where the year confusion came from).

**Comment by jeromekelleher** [comment]
Should be change the name and the citation then? Could keep the 4B11 version around as a synonym, raising a FutureWarning?

**Comment by apragsdale** [comment]
Another small issue with Browning America model: mismatch between generation time in model vs QC model. Don't think it affected any conversions to generation time units luckily. Adding a test that checks that generation times match between model and the qc model.

**Comment by petrelharp** [comment]
The generation time mismatch has been fixed, at some point.
