### ISSUE TITLE
[Bacteria] Streptococcus agalactiae CC 17

### ISSUE THREAD

**Issue by jeanrjc** [popsim-consortium/stdpopsim#843]
Question : Should I add this clone as if I were adding a species, or should I proceed differently ?

- **Name:** Streptococcus agalactiae CC 17
- **Common name:** Group B Streptococcus (GBS) Clonal Complex 17

**Description:** Virulent strain responsible for most of GBS late onset infection in neonates.

**Demographic information:**

- [x] generation time in years : 365 generations per year (1 per day). 
No estimation was done for S agalactiae, but we can use estimates from E coli, which ranges from around 0.5 to 20 generations per day. The standard generation time used is 1. 
    - ref for lower range estimates : Michael A. Savageau, « Escherichia coli habitats, cell types, and molecular mechanisms of gene control », The american naturalist 122, nᵒ 6 (1983): 732–744.
    - ref for higher range estimates :  Mohamed Ghalayini et al., « Evolution of a Dominant Natural Isolate of Escherichia Coli in the Human Gut over the Course of a Year Suggests a Neutral Evolution with Reduced Effective Population Size », Applied and Environmental Microbiology 84, nᵒ 6 (5 janvier 2018): e02377-17, https://doi.org/10.1128/AEM.02377-17.
- [x] "default" population size : Estimated with estimates of the mutation rate through the Watterson estimator: Ne = 140k
Ranges depending on the range of mutation rate estimates : ~[80k; 3M]
ref for estimation of mutation rate: Da Cunha et al. "Streptococcus agalactiae clones infecting humans were selected and fixed through the extensive use of tetracycline", 2014, Nat. Comm., 10.1038/ncomms5544
  

**Chromosome structure:**

*Note:* The assembly should be *chromosome-level*, i.e., not composed of thousands of scaffolds.

- [x] ensembl assembly ID *or*, if the assembly is not in Ensembl, a list of chromosomes with *name* and *length* (in bp)
- Chromosome 1 (only chromosome) : ~ 2 065 000 bp 
    - (Da Cunha et al, 2014), https://www.ncbi.nlm.nih.gov/assembly/GCF_000689235.1.

**Recombination rates:**

In Bacteria, recombination rate is the **gene conversion rate**, cross-over recombination rate is 0. 
It requires a parameter for the mean recombination track length.
 
- [] genetic map of recombination rates (as a hapmap or csv file)  : NA
- [] genome-wide mean recombination rate (which will be used as the default)
- 

**Mutation rate:**

- [x] genome-wide mean mutation rate : 1.53x10-9 snp/site/generation
    - in Da Cunha, 2014 paper : mutation rate estimated : 0.56 SNP/Mb/year 

**Demographic model:**

- [] as a list of population sizes, growth rates, migration rates, etcetera. **(optional)**
- [] citation

**Other information:**

These are things we don't currently use, but will want to use in the future:

- [] sex determination system, and which chromosomes are the sex chromosome(s)
- [] ploidy

**Comment by petrelharp** [comment]
> Question : Should I add this clone as if I were adding a species, or should I proceed differently ?

Yes? I don't see what else we'd do.

**Comment by jeanrjc** [comment]
> > Question : Should I add this clone as if I were adding a species, or should I proceed differently ?
> 
> Yes? I don't see what else we'd do.

We discussed this with Jerome and Franz, and we figure that we will do like this indeed. 

The issue that may come up at some point, is if people want to add another strain of the same species, especially if that strain is parametrized differently.

**Comment by jeromekelleher** [comment]
I think we'll start adding the strain suffix to the species ID then @jeanrjc - but for now, let's not worry about it.

**Comment by jeanrjc** [comment]
yes, it was my follow up question. But I'll stick to StrAga for now.

**Comment by jeromekelleher** [comment]
Closed in #854
