### ISSUE TITLE
include gene conversion feature of msprime/slim into stdpopsim 

### ISSUE THREAD

**Issue by fbaumdicker** [popsim-consortium/stdpopsim#846]
When we created stdpopsim, msprime did not have the gene conversion feature.
As gc is now possible in msprime as well as slim and gene conversion is a major factor of microbial evolution, it would be worth to include this as a possible parameter to the species models.

For E.Coli there might already be a commented part in the code that relates to the gene conversion of E.Coli.

Gene conversion can basically be handled like recombination. So if the parameter is not set, then gc is zero.
Otherwise, we have to specify a genome wide average for the gene conversion initiation rate and the mean tract length.

**Comment by jeromekelleher** [comment]
I propose we add a ``gene_conversion_rate`` and ``gene_conversion_tract_length`` parameters to the Chromosome class, which default to zero. This can then be picked up in the contig and then passed to the simulation engine.
