### ISSUE TITLE
Enter a fine-scale genetic map manually

### ISSUE THREAD

**Issue by attrna** [popsim-consortium/stdpopsim#867]
I would like to add a genetic map manually to a new species (_C. elegans_).

Please, could you tell me how to format the "_recombination_rate_data" in species.py to include the genome positions not only chromosomes?

Thank you!
Anastasia

**Comment by petrelharp** [comment]
Here's what's in the cache:
```
$ head ~/.cache/stdpopsim/genetic_maps/AraTha/SalomeAveraged_TAIR7/arab_chr1_map_loess.txt
Chromosome Position(bp) Rate(cM/Mb) Map(cM)
chr1 32807 5.016134 0
chr1 488426 4.579949 0
chr1 768865 4.021042 0
chr1 1149280 2.89238 0
chr1 1390502 2.53379 0
chr1 1411467 2.489886 0
chr1 1699236 2.266439 0
chr1 1865285 2.235896 0
chr1 2192374 2.09934 0
```

**Comment by petrelharp** [comment]
... but what's in `species.py` only has default chromosome-wide recombination rate values; the genetic map information is contained in `genetic_maps.py` - see for instance ``stdpopsim/catalog/AraTha/genetic_maps.py.

**Comment by petrelharp** [comment]
Ah - and, I think this is all documented in https://stdpopsim.readthedocs.io/en/latest/development.html#adding-a-genetic-map ?

**Comment by attrna** [comment]
Thank you!
