### ISSUE TITLE
update dev docs to main from master

### ISSUE THREAD

**Issue by agladstein** [popsim-consortium/stdpopsim#868]
The github workflow docs still says master. It should we switched to main. https://stdpopsim.readthedocs.io/en/latest/development.html#github-workflow
We should also include instructions for how to switch fix your fork if it's old.

**Comment by agladstein** [comment]
```
git branch -m master main
git push -u origin main
git fetch upstream
```

**Comment by grahamgower** [comment]
The `readthedocs` (RTD) page hasn't been updated from the repository for a long time --- IIRC we had long-standing issues with RTD running out of memory when setting up the conda env to build the docs.

**Comment by apragsdale** [comment]
The development docs also don't explain the new process of adding species (no longer have an `update_ensembl_data.py` function, for example). There's been a bit of movement in the API (e.g. #839 updates a bunch of the tutorial). Until the memory issue is resolved, are we able to at least manually trigger builds of the docs when we merge PRs that update them? The last update was 2 1/2 months ago...

**Comment by agladstein** [comment]
I don't know if this is related at all, but I tried to build locally, didn't get any error, but it didn't include any updates. I was very confused. Seemed like I was on the wrong branch... But, I wasn't.

**Comment by apragsdale** [comment]
Hmm - yeah, I've been able to build locally as well without issues, but the updates I wrote do show up in my local build/html outputs. Not sure why they wouldn't be updating locally

**Comment by agladstein** [comment]
same... I was very confused and thought I was doing something dumb... But, maybe it's not me

**Comment by jeromekelleher** [comment]
@grahamgower - what's the new docs URL? We should just do the redirect from rtd to there, it's going to cause more and more confusion.

**Comment by grahamgower** [comment]
Currently living at: https://popsim-consortium.github.io/stdpopsim-docs/

**Comment by jeromekelleher** [comment]
Ben did some versioning for the tskit docs, is that any use?

**Comment by grahamgower** [comment]
> Ben did some versioning for the tskit docs, is that any use?

I see
https://tskit.dev/tskit/docs/stable/
and
https://tskit.dev/tskit/docs/latest/

But nothing like https://tskit.dev/tskit/docs/0.3.5/ and no menu with links to the various versions. But maybe I missed it? We can certainly upload tagged versions of the docs onto github.io, it's really just doing the javascript bit to insert a menu which is lacking. The menu's contents should be populated from a file, as it needs to be updated with each new tagged release. I haven't done any javascript since ~1999, so would be grateful if someone else has a pre-canned solution, or could otherwise figure it out.

**Comment by jeromekelleher** [comment]
I don't think it really matters if we have a menu, just ``stable`` and ``latest`` links is fine I think.

**Comment by agladstein** [comment]
Maybe I missed something. Is something different happening with how the docs are built?

**Comment by jeromekelleher** [comment]
Sorry @agladstein - local builds should work just fine, I've no idea what's happening there.

**Comment by grahamgower** [comment]
RTD is back now, and the docs say `main` and not `master`.
