### ISSUE TITLE
Anolis carolinensis

### ISSUE THREAD

**Issue by Vcaudill** [popsim-consortium/stdpopsim#869]
- **Anolis carolinensis:** scientific name of the species
- **Green anole:**

**Description:** Lizard that lives in the southeastern United States. These lizards can change color. 

**Demographic information:**

- [1.5] generation time in years [Lovern et al. 2004](https://academic.oup.com/ilarjournal/article/45/1/54/700334?login=true)
- [2e6] "default" population size predicted by [Bourgeois](https://academic.oup.com/gbe/article/11/7/2009/5499074?login=true) Fig 2a

**Chromosome structure:**

- [Anolis_carolinensis] ensembl assembly ID 

**Recombination rates:**

- [] genetic map of recombination rates (as a hapmap or csv file)
- [] genome-wide mean recombination rate (which will be used as the default)
tbd

**Mutation rate:**

- [ 2.1e−10 ] genome-wide mean mutation rate [Bourgeois](https://academic.oup.com/gbe/article/11/7/2009/5499074?login=true)

**Demographic model:**

- [] as a list of population sizes, growth rates, migration rates, etcetera. **(optional)**
- [] citation

**Other information:**
Cool paper about recombination might also have a demographic model [Bourgeois](https://academic.oup.com/gbe/article/11/7/2009/5499074?login=true)

These are things we don't currently use, but will want to use in the future:

- [XY] sex determination system, and which chromosomes are the sex chromosome(s)
- [diploid] ploidy

**Comment by petrelharp** [comment]
Looks good! Next thing is to start a pull request?
