### ISSUE TITLE
Species QC for StrAga

### ISSUE THREAD

**Issue by jeromekelleher** [popsim-consortium/stdpopsim#881]
**PR for new species:** #854

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [ ] Mutation rate.
- [ ] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [ ] Population size.
- [ ] Generation time.

**Comment by igronau** [comment]
I will start QC-ing this species

**Comment by vitorpavinato** [comment]
Do we need to parametrize this species with "mean gene conversion rate and gene conversion tract length" as mentioned here #1106?

**Comment by petrelharp** [comment]
Hi, @igronau @vitorpavinato - are you planning to do this or should someone else do it?

**Comment by vitorpavinato** [comment]
When I was doing it, I wasn't sure about adding gene conversion parameterization, so I looked at the parameters. I guess I can't do this QC anymore.

**Comment by petrelharp** [comment]
Ah, ok, thanks. About the GC rates: currently they're commented out, so don't need QC'ing, but the GC stuff will be merged in soon, so: maybe? (And: I'm not sure what you mean by "I guess I can't do this", but if you want to continue here we'd be happy to have you, but that's probably not what you mean.)

**Comment by igronau** [comment]
I didn't really dive into this one yet, so I prefer if someone else will QC this one.

**Comment by petrelharp** [comment]
> But I guess someone else should also do it?

We only need one person to QC - what do you mean?

**Comment by petrelharp** [comment]
Closed in #1251
