### ISSUE TITLE
QC for Chlamydomonas reinhardtii

### ISSUE THREAD

**Issue by aays** [popsim-consortium/stdpopsim#890]
**PR for new species:** #863

IMPLEMENTER'S NOTE: The recombination rates are from Hasan and Ness 2020, but the raw values were not published as part of the manuscript - per @jeromekelleher's advice I'll be uploading them to figshare and updating the doi.

The per-chromosome mutation rates will also hopefully be added in as a separate PR (I was just sent the data late yesterday) and I'll be asking about whether I can make those public as well - though it's not my data, so TBD! 

---

If you volunteer to QC this species, please use the checklist below.
While this list is intended to be comprehensive, it may not be exhaustive.
Where relevant, the QC reviewer should identify that parameter values match
those given in the linked citation(s).

The QC reviewer should start a pull request that fills out the test stubs
with independently obtained values. The reviewer may look at the python code
for rationale provided in comments, but should ignore the actual code
as much as possible - comments in the code should give enough information
that it's obvious how to get the correct value from the provided references.
(In particular, we shouldn't copy-paste the value from the code into the test!)

- [ ] Recombination rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Average over a recombination map? Redo the calculation.
- [ ] Mutation rate.
  - This might be genome-wide, or per-chromosome. Both are fine.
  - Check there's a comment describing where it came from, and/or how calculated.
  - From a publication? Check the value(s) match the publication.
  - Calculated somehow? Redo the calculation.
- [ ] Recombination map (if present).
  - Does it match the assembly? Liftover is fine, if clearly stated.
  - Is the description/long_description a good summary of how the map was created?
- [ ] Population size.
- [ ] Generation time.

For each citation, check:
- Doi link.
- Is publication a preprint? Is there a peer-reviewed publication instead?
- Is the year correct.
- Is the author correct (spelling, accents/ligatures/etc.)

Citations are required for:
- [ ] Genome reference assembly.
- [ ] Mutation rate.
- [ ] Recombination rate.
- [ ] Recombination map(s) (if relevant).
- [ ] Population size.
- [ ] Generation time.

The final PR should:
- [ ] fill out the test stubs
- [ ] delete the `pytest.mark.skip` lines that make the tests not run
- [ ] make sure they pass, talking to the original author to figure out discrepancies

**Comment by aays** [comment]
Thanks for the heads up @petrelharp - I've added an explanation on the PR!

**Comment by izabelcavassim** [comment]
can you close this @petrelharp? sorry forgot to mention in my other PR

**Comment by petrelharp** [comment]
Yes! And gee you should be able to also. I've sent you an invite that *should* get you those permissions...
