### ISSUE TITLE
catalog documentation and new species

### ISSUE THREAD

**Issue by andrewkern** [popsim-consortium/stdpopsim#900]
do we have a plan for adding new species to the documentation at scale? is there a way we can automate this?

**Comment by jeromekelleher** [comment]
No, I hadn't thought of that step. Simplest just to add them in by hand for now, I guess we can figure out a way to automate it later when we have a ``qc_complete`` flag on species (or something).

**Comment by andrewkern** [comment]
closing this down... i think the process is working just fine at this point.
