### ISSUE TITLE
Not all genomes have chromosome synonyms

### ISSUE THREAD

**Issue by apragsdale** [popsim-consortium/stdpopsim#902]
While updating some of the docs, realized that the tutorial section "Calculating the allele frequency spectrum" would not run as written, as "chr4" does not exist as a synonym for chromosome 4. We should probably include these basic synonyms for all species genomes.

**Comment by jeromekelleher** [comment]
This is a function of the upstream data repos @apragsdale - no would be the short answer. 

They should exist for humans though - do the synonyms exist for the other chrs?

**Comment by apragsdale** [comment]
I see. That's too bad - as far as I can see, it's only humans that have synonyms. This means that while we previously could specify chr2L for DroMel and chr4 for AraTha (as the docs currently do), these are errors now. I think it's worth adding these obvious synonyms by hand for all species.

**Comment by jeromekelleher** [comment]
Well, feel free (but in a way that doesn't get clobbered by automatic updates from the repository).

**Comment by apragsdale** [comment]
Closed by #912
