### ISSUE TITLE
start selection docs

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#944]
- [x] add the autogenerated docs for `GenomicElementTypes`, `MutationTypes`, and new stuff to [`Contig`](https://stdpopsim.readthedocs.io/en/latest/api.html#stdpopsim.Contig)
- [x] fix `selection.py` examples (fixed in #945)
- [x] move the `selection.py` examples to a section in `tutorials` (this is #949)
- [ ] write an example pulling in an annotation

*Edit:* the Contig stuff is there, just not building - see #946 and build docs locally in the meantime.

**Comment by nspope** [comment]
It looks like there is documentation in place about combining DFEs and annotations [here](https://popsim-consortium.github.io/stdpopsim-docs/latest/tutorial.html#simulating-selection-on-exons), which should check the last box. Mind if I close this @petrelharp?

**Comment by nspope** [comment]
Closing as resolved, all these boxes are ticked afaict
