### ISSUE TITLE
RTD not updating

### ISSUE THREAD

**Issue by petrelharp** [popsim-consortium/stdpopsim#946]
The documentation on readthedocs is not building because it's trying to build from `master`, not `main`. This is a [known issue](https://github.com/readthedocs/readthedocs.org/issues/7907) but is supposed to be fixed by changing the "default branch" in Advanced Settings: 
![Screenshot from 2021-05-25 09-35-35](https://user-images.githubusercontent.com/1046249/119535180-9925a280-bd3c-11eb-8670-273d8de4ced2.png)

However, I can't change that setting (and, a number of other settings) - I click on them and nothing happens. Maybe I don't have the correct permissions? @jeromekelleher - maybe you are the one with the secret keys? If you can't do it I think we need to ask RTD.

**Comment by petrelharp** [comment]
Note that "default branch" is not something you can set in `.readthedocs.yml`.

**Comment by jeromekelleher** [comment]
Fixed now? https://stdpopsim.readthedocs.io/en/latest/

**Comment by petrelharp** [comment]
I think so! Thanks.
