### ISSUE TITLE
Add length property to contigs

### ISSUE THREAD

**Issue by mufernando** [popsim-consortium/stdpopsim#947]
I think length is a pretty useful property to have in `Contig`. At first I thought this could simply be a wrapper around `contig.recombination_map.sequence_length`, but it is possible to define contigs withot a recombination map, in which case I'm not sure how the msprime engine deals with this.

See #945 #930

**Comment by apragsdale** [comment]
For generic contigs that are not specified using a cached recombination map, the `get_contig` method builds a `msprime.RateMap.uniform` genetic map. So the same properties, such as `contig.recombination_map.sequence_length`, should be available from both generic and chromosome contigs, right?

**Comment by grahamgower** [comment]
Yep, that sounds right @apragsdale. Perhaps there's come confusion because the `Contig` class uses `default=None` for the arrtribs. Probably the default=None should be removed --- maybe a test or two is using it without a recombination map and needs to be fixed?

**Comment by apragsdale** [comment]
Yeah, that makes sense to me as the source of some of the confusion. Not sure what the default should be otherwise though. Since it takes a string as the identifier of the genetic map to load, the default could be the string "uniform", or something like that, instead of None, so instead of checking `genetic_map is None`, we check `genetic_map == "uniform"`. Not sure...

**Comment by mufernando** [comment]
Ah, great. Thanks @apragsdale and @grahamgower 

> Yep, that sounds right @apragsdale. Perhaps there's come confusion because the `Contig` class uses `default=None` for the attribs. Probably the default=None should be removed --- maybe a test or two is using it without a recombination map and needs to be fixed?
That's definitely where the confusion arised for me.

**Comment by grahamgower** [comment]
Fixed in #959 (length property added, and `Contig`s always have a recombination map).
